import { Facturador } from './facturador';
import { Titular } from '../../tsr/model/titular';
import { Usuario } from '../../../shared/model/usuario';
import { PuntoEmision } from './puntos-emision';
import { FormaPagoFactura } from './forma-pago-factura';

export interface FacturaEmitir {
  id: number;
  tipoComprobante: string;
  facturador: Facturador;
  titular: Titular;
  tipoDoc: string;
  numero: string;
  numEstablecimiento: string;
  numPtoEmision: string;
  secuencial: string;
  ambiente: number;
  clave: string;
  fecha: Date;
  observacion: string;
  subtotal: number;
  subtotal5: number;
  subtotal8: number;
  subcero: number;
  pIVA: number;
  vIVA: number;
  vIVA5: number;
  vIVA8: number;
  vICE: number;
  vIRBPNR: number;
  descuento: number;
  porDescuento: number;
  propina: number;
  subsidio: number;
  totalSinSub: number;
  ahorroSub: number;
  total: number;
  ptoEmision: PuntoEmision;
  usuario: Usuario;
  pathGen: string;
  autorizacion: string;
  fechaAutorizacion: string;
  formaPago: number;
  estado: number;
  estadoEmision: number;
  motivoAnulacion?: string | null;
  fechaAnulacion?: string | null;
  usuarioAnulacion?: string | null;
  formaPagosFactura?: FormaPagoFactura[];  // Relación 1:N con formas de pago
}
