-- =====================================================
-- MODULO: RHH (Recursos Humanos) - TABLAS DE PARAMETRIZACION
-- DESCRIPCION: Catalogos configurables del motor de nomina.
--              Ninguna regla ni valor normativo se codifica en Java:
--              todo vive en estas tablas o en SCP.PRBR/SCP.PDTR.
-- ORDEN DE EJECUCION: 1 de 6
-- BASE DE DATOS: Oracle (probado sobre 23ai/26ai)
-- FECHA: 2026-08-19
-- =====================================================
-- NOTA SOBRE FK A EMPRESA:
--   La entidad Empresa se mapea a SCP.PJRQ (Jerarquia), por lo que
--   todas las FK de empresa apuntan a SCP.PJRQ(PJRQCDGO).
-- NOTA SOBRE CUENTAS CONTABLES:
--   Las columnas PLNNCDGO / DTPLCDGO se crean NULLABLE a proposito.
--   Se completan con el script 06_CONFIGURAR_CUENTAS.sql cuando el
--   cliente entregue su plan de cuentas. La carga historica de nomina
--   NO las necesita; solo la contabilizacion.
-- =====================================================


-- =====================================================
-- TABLA: RHH.CFNM (ConfiguracionNomina)
-- DESCRIPCION: Configuracion del modulo por empresa. Es la que decide
--              que plantillas contables se usan y que funcionalidades
--              estan habilitadas (utilidades, centro de costo, etc.).
-- =====================================================
CREATE TABLE RHH.CFNM (
    CFNMCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    -- FK a Empresa
    PJRQCDGO NUMBER NOT NULL,

    -- CODIGOS ALTERNOS DE LAS PLANTILLAS CONTABLES (CNT.PLNS.PLNSCDAL)
    CFNMPLRL NUMBER, -- Codigo alterno de la plantilla del asiento de rol de pagos
    CFNMPLPR NUMBER, -- Codigo alterno de la plantilla del asiento de provisiones
    CFNMPLPG NUMBER, -- Codigo alterno de la plantilla del asiento de pago
    CFNMPLLQ NUMBER, -- Codigo alterno de la plantilla del asiento de liquidacion

    -- CODIGOS ALTERNOS DE LOS TIPOS DE ASIENTO (CNT.PLNT.PLNTCDAL)
    CFNMTARL NUMBER, -- Codigo alterno del tipo de asiento de rol de pagos
    CFNMTAPR NUMBER, -- Codigo alterno del tipo de asiento de provisiones
    CFNMTAPG NUMBER, -- Codigo alterno del tipo de asiento de pago
    CFNMTALQ NUMBER, -- Codigo alterno del tipo de asiento de liquidacion

    -- BANDERAS DE FUNCIONALIDAD
    CFNMDCCS VARCHAR2(1) DEFAULT 'N', -- Desglosa por centro de costo (S/N)
    CFNMAPUT VARCHAR2(1) DEFAULT 'N', -- Aplica reparto de utilidades (S/N). ASOPREP='N'
    CFNMAPJP VARCHAR2(1) DEFAULT 'N', -- Aplica provision de jubilacion patronal (S/N)
    CFNMAPDS VARCHAR2(1) DEFAULT 'N', -- Aplica provision de desahucio (S/N)
    CFNMRDND VARCHAR2(1) DEFAULT 'S', -- Redondea cada renglon a 2 decimales (S/N)
    CFNMTLCD NUMBER(18,2) DEFAULT 0.05, -- Tolerancia de cuadre del asiento

    -- AUDITORIA
    CFNMESTD NUMBER DEFAULT 1,
    CFNMFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CFNMUSRR VARCHAR2(60),

    CONSTRAINT PK_CFNM PRIMARY KEY (CFNMCDGO),
    CONSTRAINT UQ_CFNM_PJRQ UNIQUE (PJRQCDGO),
    CONSTRAINT FK_CFNM_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO)
);

-- SIN INDICE EXPLICITO SOBRE PJRQCDGO A PROPOSITO:
-- la restriccion UQ_CFNM_PJRQ ya crea un indice unico sobre esa misma
-- columna. Crear otro con la lista de columnas identica da ORA-01408
-- ("esta lista de columnas ya esta indexada").
-- Es el unico caso del modulo: las demas restricciones UNIQUE son
-- compuestas, y Oracle si permite un indice de una columna junto a uno
-- compuesto que la contenga.

COMMENT ON TABLE  RHH.CFNM IS 'Configuracion del modulo de nomina por empresa: plantillas contables, tipos de asiento y banderas de funcionalidad';
COMMENT ON COLUMN RHH.CFNM.CFNMCDGO IS 'Codigo unico de la configuracion (PK autoincremental)';
COMMENT ON COLUMN RHH.CFNM.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.CFNM.CFNMPLRL IS 'Codigo alterno de la plantilla contable del asiento de rol de pagos (CNT.PLNS.PLNSCDAL)';
COMMENT ON COLUMN RHH.CFNM.CFNMPLPR IS 'Codigo alterno de la plantilla contable del asiento de provisiones';
COMMENT ON COLUMN RHH.CFNM.CFNMPLPG IS 'Codigo alterno de la plantilla contable del asiento de pago de nomina';
COMMENT ON COLUMN RHH.CFNM.CFNMPLLQ IS 'Codigo alterno de la plantilla contable del asiento de liquidacion de haberes';
COMMENT ON COLUMN RHH.CFNM.CFNMTARL IS 'Codigo alterno del tipo de asiento de rol de pagos (CNT.PLNT.PLNTCDAL)';
COMMENT ON COLUMN RHH.CFNM.CFNMTAPR IS 'Codigo alterno del tipo de asiento de provisiones';
COMMENT ON COLUMN RHH.CFNM.CFNMTAPG IS 'Codigo alterno del tipo de asiento de pago de nomina';
COMMENT ON COLUMN RHH.CFNM.CFNMTALQ IS 'Codigo alterno del tipo de asiento de liquidacion de haberes';
COMMENT ON COLUMN RHH.CFNM.CFNMDCCS IS 'Indica si el asiento se desglosa por centro de costo (S/N)';
COMMENT ON COLUMN RHH.CFNM.CFNMAPUT IS 'Indica si la empresa reparte utilidades del 15 por ciento (S/N)';
COMMENT ON COLUMN RHH.CFNM.CFNMAPJP IS 'Indica si se provisiona jubilacion patronal (S/N)';
COMMENT ON COLUMN RHH.CFNM.CFNMAPDS IS 'Indica si se provisiona desahucio (S/N)';
COMMENT ON COLUMN RHH.CFNM.CFNMRDND IS 'Indica si cada renglon se redondea a 2 decimales antes de sumar (S/N)';
COMMENT ON COLUMN RHH.CFNM.CFNMTLCD IS 'Tolerancia maxima de descuadre del asiento que se ajusta automaticamente';
COMMENT ON COLUMN RHH.CFNM.CFNMESTD IS 'Estado del registro (rubro Estado: 1=ACTIVO, 0=INACTIVO)';
COMMENT ON COLUMN RHH.CFNM.CFNMFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.CFNM.CFNMUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.PRNM (ParametroNomina)
-- DESCRIPCION: Parametros normativos vigentes por anio y empresa.
--              SBU, porcentajes IESS, fondos de reserva, canasta basica,
--              topes de horas extra y bases de calculo.
--              UN REGISTRO POR ANIO. Nada de esto va en codigo Java.
-- =====================================================
CREATE TABLE RHH.PRNM (
    PRNMCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL, -- FK a Empresa
    PRNMANOO NUMBER NOT NULL, -- Anio de vigencia

    -- VALORES BASE
    PRNMSBUU NUMBER(18,2) NOT NULL, -- Salario Basico Unificado del anio
    PRNMCNBS NUMBER(18,2),          -- Canasta familiar basica (enero del anio)

    -- PORCENTAJES IESS
    PRNMAPPR NUMBER(18,6), -- Aporte personal IESS (%)
    PRNMAPPT NUMBER(18,6), -- Aporte patronal IESS (%)
    PRNMIECE NUMBER(18,6), -- Aporte IECE (%)
    PRNMSCAP NUMBER(18,6), -- Aporte SECAP (%)
    PRNMFNRS NUMBER(18,6), -- Fondos de reserva (%)

    -- IMPUESTO A LA RENTA
    PRNMTPGP NUMBER(18,6), -- Porcentaje de rebaja por gastos personales (%)
    PRNMCNCT NUMBER,       -- Numero de canastas para enfermedad catastrofica

    -- UTILIDADES
    PRNMUTPR NUMBER(18,6), -- Porcentaje total de utilidades (%)
    PRNMUTDI NUMBER(18,6), -- Porcentaje de utilidades por dias trabajados (%)
    PRNMUTCG NUMBER(18,6), -- Porcentaje de utilidades por cargas familiares (%)
    PRNMUTSB NUMBER,       -- Tope de utilidades por trabajador, en numero de SBU

    -- BASES DE CALCULO
    PRNMDIAS NUMBER DEFAULT 30,  -- Dias base del mes comercial
    PRNMDANO NUMBER DEFAULT 360, -- Dias base del anio comercial
    PRNMHRMS NUMBER DEFAULT 240, -- Horas base del mes
    PRNMHRDI NUMBER DEFAULT 8,   -- Horas de la jornada ordinaria diaria

    -- HORAS EXTRA
    PRNMRCSP NUMBER(18,6), -- Recargo de horas suplementarias (%)
    PRNMRCEX NUMBER(18,6), -- Recargo de horas extraordinarias (%)
    PRNMRCNC NUMBER(18,6), -- Recargo nocturno (%)
    PRNMHRMX NUMBER,       -- Maximo de horas extra por dia
    PRNMHRSX NUMBER,       -- Maximo de horas extra por semana

    -- VACACIONES
    PRNMDIVC NUMBER, -- Dias de vacaciones base por anio
    PRNMANVC NUMBER, -- Anio a partir del cual se suma un dia adicional
    PRNMMXVC NUMBER, -- Maximo de dias de vacaciones acumulables por periodo
    PRNMCDVC NUMBER, -- Anios tras los cuales caduca el saldo de vacaciones

    -- INDEMNIZACIONES
    PRNMDSPR NUMBER(18,6), -- Porcentaje de bonificacion por desahucio (%)
    PRNMDIMN NUMBER,       -- Meses minimos de indemnizacion por despido intempestivo
    PRNMDIMX NUMBER,       -- Meses maximos de indemnizacion por despido intempestivo
    PRNMDIAN NUMBER,       -- Anios de antiguedad bajo los cuales aplica el minimo

    -- AUDITORIA
    PRNMESTD NUMBER DEFAULT 1,
    PRNMFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRNMUSRR VARCHAR2(60),

    CONSTRAINT PK_PRNM PRIMARY KEY (PRNMCDGO),
    CONSTRAINT UQ_PRNM_ANIO UNIQUE (PJRQCDGO, PRNMANOO),
    CONSTRAINT FK_PRNM_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO)
);

CREATE INDEX IDX_PRNM_PJRQ ON RHH.PRNM(PJRQCDGO);

COMMENT ON TABLE  RHH.PRNM IS 'Parametros normativos de nomina vigentes por anio y empresa. Fuente unica de SBU, porcentajes IESS y bases de calculo';
COMMENT ON COLUMN RHH.PRNM.PRNMCDGO IS 'Codigo unico del parametro (PK autoincremental)';
COMMENT ON COLUMN RHH.PRNM.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.PRNM.PRNMANOO IS 'Anio de vigencia de los parametros';
COMMENT ON COLUMN RHH.PRNM.PRNMSBUU IS 'Salario Basico Unificado vigente en el anio';
COMMENT ON COLUMN RHH.PRNM.PRNMCNBS IS 'Valor de la canasta familiar basica de enero, base del tope de gastos personales';
COMMENT ON COLUMN RHH.PRNM.PRNMAPPR IS 'Porcentaje de aporte personal al IESS';
COMMENT ON COLUMN RHH.PRNM.PRNMAPPT IS 'Porcentaje de aporte patronal al IESS';
COMMENT ON COLUMN RHH.PRNM.PRNMIECE IS 'Porcentaje de aporte al IECE';
COMMENT ON COLUMN RHH.PRNM.PRNMSCAP IS 'Porcentaje de aporte al SECAP';
COMMENT ON COLUMN RHH.PRNM.PRNMFNRS IS 'Porcentaje de fondos de reserva';
COMMENT ON COLUMN RHH.PRNM.PRNMTPGP IS 'Porcentaje de rebaja aplicable sobre los gastos personales declarados';
COMMENT ON COLUMN RHH.PRNM.PRNMCNCT IS 'Numero de canastas basicas de tope para enfermedades catastroficas';
COMMENT ON COLUMN RHH.PRNM.PRNMUTPR IS 'Porcentaje total de utilidades a repartir';
COMMENT ON COLUMN RHH.PRNM.PRNMUTDI IS 'Porcentaje de utilidades que se reparte en funcion de dias trabajados';
COMMENT ON COLUMN RHH.PRNM.PRNMUTCG IS 'Porcentaje de utilidades que se reparte en funcion de cargas familiares';
COMMENT ON COLUMN RHH.PRNM.PRNMUTSB IS 'Tope de utilidades por trabajador expresado en numero de SBU; el excedente va al IESS';
COMMENT ON COLUMN RHH.PRNM.PRNMDIAS IS 'Dias base del mes comercial para prorrateos';
COMMENT ON COLUMN RHH.PRNM.PRNMDANO IS 'Dias base del anio comercial para prorrateos';
COMMENT ON COLUMN RHH.PRNM.PRNMHRMS IS 'Horas base del mes para el calculo del valor hora';
COMMENT ON COLUMN RHH.PRNM.PRNMHRDI IS 'Horas de la jornada ordinaria diaria';
COMMENT ON COLUMN RHH.PRNM.PRNMRCSP IS 'Porcentaje de recargo de las horas suplementarias';
COMMENT ON COLUMN RHH.PRNM.PRNMRCEX IS 'Porcentaje de recargo de las horas extraordinarias';
COMMENT ON COLUMN RHH.PRNM.PRNMRCNC IS 'Porcentaje de recargo por jornada nocturna';
COMMENT ON COLUMN RHH.PRNM.PRNMHRMX IS 'Maximo legal de horas extra por dia';
COMMENT ON COLUMN RHH.PRNM.PRNMHRSX IS 'Maximo legal de horas extra por semana';
COMMENT ON COLUMN RHH.PRNM.PRNMDIVC IS 'Dias de vacaciones que se acreditan por anio cumplido';
COMMENT ON COLUMN RHH.PRNM.PRNMANVC IS 'Anio de servicio a partir del cual se acredita un dia adicional de vacaciones';
COMMENT ON COLUMN RHH.PRNM.PRNMMXVC IS 'Maximo de dias de vacaciones acreditables en un periodo';
COMMENT ON COLUMN RHH.PRNM.PRNMCDVC IS 'Numero de anios tras los cuales caduca el saldo de vacaciones no gozado';
COMMENT ON COLUMN RHH.PRNM.PRNMDSPR IS 'Porcentaje de la ultima remuneracion por anio de servicio para la bonificacion por desahucio';
COMMENT ON COLUMN RHH.PRNM.PRNMDIMN IS 'Numero minimo de remuneraciones de indemnizacion por despido intempestivo';
COMMENT ON COLUMN RHH.PRNM.PRNMDIMX IS 'Numero maximo de remuneraciones de indemnizacion por despido intempestivo';
COMMENT ON COLUMN RHH.PRNM.PRNMDIAN IS 'Anios de antiguedad bajo los cuales se aplica la indemnizacion minima';
COMMENT ON COLUMN RHH.PRNM.PRNMESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.PRNM.PRNMFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.PRNM.PRNMUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.TBIR (TablaImpuestoRenta)
-- DESCRIPCION: Tabla progresiva del impuesto a la renta de personas
--              naturales, por anio y tramo. Publicada anualmente por el SRI.
-- =====================================================
CREATE TABLE RHH.TBIR (
    TBIRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL, -- FK a Empresa
    TBIRANOO NUMBER NOT NULL, -- Anio fiscal
    TBIRORDN NUMBER NOT NULL, -- Orden del tramo (1 = primero)

    TBIRFRBS NUMBER(18,2) NOT NULL, -- Fraccion basica del tramo
    TBIREXCS NUMBER(18,2),          -- Exceso hasta (NULL en el ultimo tramo)
    TBIRIMFB NUMBER(18,2) NOT NULL, -- Impuesto sobre la fraccion basica
    TBIRPRCN NUMBER(18,6) NOT NULL, -- Porcentaje sobre la fraccion excedente

    TBIRESTD NUMBER DEFAULT 1,
    TBIRFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TBIRUSRR VARCHAR2(60),

    CONSTRAINT PK_TBIR PRIMARY KEY (TBIRCDGO),
    CONSTRAINT UQ_TBIR_TRAMO UNIQUE (PJRQCDGO, TBIRANOO, TBIRORDN),
    CONSTRAINT FK_TBIR_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO)
);

CREATE INDEX IDX_TBIR_PJRQ ON RHH.TBIR(PJRQCDGO);
CREATE INDEX IDX_TBIR_ANIO ON RHH.TBIR(TBIRANOO);

COMMENT ON TABLE  RHH.TBIR IS 'Tabla progresiva del impuesto a la renta de personas naturales por anio y tramo, segun resolucion anual del SRI';
COMMENT ON COLUMN RHH.TBIR.TBIRCDGO IS 'Codigo unico del tramo (PK autoincremental)';
COMMENT ON COLUMN RHH.TBIR.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.TBIR.TBIRANOO IS 'Anio fiscal al que corresponde la tabla';
COMMENT ON COLUMN RHH.TBIR.TBIRORDN IS 'Orden del tramo dentro de la tabla, ascendente';
COMMENT ON COLUMN RHH.TBIR.TBIRFRBS IS 'Fraccion basica del tramo';
COMMENT ON COLUMN RHH.TBIR.TBIREXCS IS 'Limite superior del tramo; NULL indica el ultimo tramo sin limite';
COMMENT ON COLUMN RHH.TBIR.TBIRIMFB IS 'Impuesto que se paga sobre la fraccion basica del tramo';
COMMENT ON COLUMN RHH.TBIR.TBIRPRCN IS 'Porcentaje que se aplica sobre la fraccion excedente del tramo';
COMMENT ON COLUMN RHH.TBIR.TBIRESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.TBIR.TBIRFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.TBIR.TBIRUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.TPGP (TopeGastoPersonal)
-- DESCRIPCION: Numero de canastas basicas de tope para la rebaja por
--              gastos personales, segun el numero de cargas familiares.
-- =====================================================
CREATE TABLE RHH.TPGP (
    TPGPCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL, -- FK a Empresa
    TPGPANOO NUMBER NOT NULL, -- Anio fiscal
    TPGPNCRG NUMBER NOT NULL, -- Numero de cargas familiares
    TPGPNCAN NUMBER(18,2) NOT NULL, -- Numero de canastas basicas de tope

    TPGPESTD NUMBER DEFAULT 1,
    TPGPFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TPGPUSRR VARCHAR2(60),

    CONSTRAINT PK_TPGP PRIMARY KEY (TPGPCDGO),
    CONSTRAINT UQ_TPGP_CARGAS UNIQUE (PJRQCDGO, TPGPANOO, TPGPNCRG),
    CONSTRAINT FK_TPGP_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO)
);

CREATE INDEX IDX_TPGP_PJRQ ON RHH.TPGP(PJRQCDGO);

COMMENT ON TABLE  RHH.TPGP IS 'Tope de canastas basicas para la rebaja por gastos personales, segun numero de cargas familiares y anio';
COMMENT ON COLUMN RHH.TPGP.TPGPCDGO IS 'Codigo unico del tope (PK autoincremental)';
COMMENT ON COLUMN RHH.TPGP.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.TPGP.TPGPANOO IS 'Anio fiscal al que aplica el tope';
COMMENT ON COLUMN RHH.TPGP.TPGPNCRG IS 'Numero de cargas familiares; el ultimo registro aplica de ese numero en adelante';
COMMENT ON COLUMN RHH.TPGP.TPGPNCAN IS 'Numero de canastas basicas que constituyen el tope de gasto deducible';
COMMENT ON COLUMN RHH.TPGP.TPGPESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.TPGP.TPGPFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.TPGP.TPGPUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.CSTR (CausalTerminacion)
-- DESCRIPCION: Causales de terminacion de la relacion laboral, con su
--              articulo del Codigo del Trabajo y sus efectos economicos.
-- =====================================================
CREATE TABLE RHH.CSTR (
    CSTRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL,        -- FK a Empresa
    CSTRNMBR VARCHAR2(150) NOT NULL, -- Nombre de la causal
    CSTRALTR NUMBER NOT NULL,        -- Codigo alterno (rubro RHH_CAUSAL_TERMINACION)
    CSTRARTC VARCHAR2(50),           -- Articulo del Codigo del Trabajo

    -- EFECTOS ECONOMICOS
    CSTRDSHC VARCHAR2(1) DEFAULT 'N', -- Genera bonificacion por desahucio (S/N)
    CSTRDSPD VARCHAR2(1) DEFAULT 'N', -- Genera indemnizacion por despido intempestivo (S/N)
    CSTRVCPR VARCHAR2(1) DEFAULT 'S', -- Paga vacaciones proporcionales (S/N)
    CSTRDCPR VARCHAR2(1) DEFAULT 'S', -- Paga decimos proporcionales (S/N)
    CSTRJBPT VARCHAR2(1) DEFAULT 'N', -- Genera jubilacion patronal (S/N)
    CSTRAVSL VARCHAR2(1) DEFAULT 'S', -- Requiere aviso de salida al IESS (S/N)
    CSTRACSU VARCHAR2(1) DEFAULT 'S', -- Requiere acta de finiquito en el SUT (S/N)

    CSTRESTD NUMBER DEFAULT 1,
    CSTRFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CSTRUSRR VARCHAR2(60),

    CONSTRAINT PK_CSTR PRIMARY KEY (CSTRCDGO),
    CONSTRAINT UQ_CSTR_ALTR UNIQUE (PJRQCDGO, CSTRALTR),
    CONSTRAINT FK_CSTR_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO)
);

CREATE INDEX IDX_CSTR_PJRQ ON RHH.CSTR(PJRQCDGO);

COMMENT ON TABLE  RHH.CSTR IS 'Causales de terminacion de la relacion laboral con su articulo legal y sus efectos economicos sobre la liquidacion';
COMMENT ON COLUMN RHH.CSTR.CSTRCDGO IS 'Codigo unico de la causal (PK autoincremental)';
COMMENT ON COLUMN RHH.CSTR.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.CSTR.CSTRNMBR IS 'Nombre descriptivo de la causal';
COMMENT ON COLUMN RHH.CSTR.CSTRALTR IS 'Codigo alterno del detalle del rubro RHH_CAUSAL_TERMINACION';
COMMENT ON COLUMN RHH.CSTR.CSTRARTC IS 'Articulo del Codigo del Trabajo que sustenta la causal';
COMMENT ON COLUMN RHH.CSTR.CSTRDSHC IS 'Indica si la causal genera bonificacion por desahucio (S/N)';
COMMENT ON COLUMN RHH.CSTR.CSTRDSPD IS 'Indica si la causal genera indemnizacion por despido intempestivo (S/N)';
COMMENT ON COLUMN RHH.CSTR.CSTRVCPR IS 'Indica si se pagan vacaciones proporcionales (S/N)';
COMMENT ON COLUMN RHH.CSTR.CSTRDCPR IS 'Indica si se pagan decimos proporcionales (S/N)';
COMMENT ON COLUMN RHH.CSTR.CSTRJBPT IS 'Indica si la causal genera derecho a jubilacion patronal (S/N)';
COMMENT ON COLUMN RHH.CSTR.CSTRAVSL IS 'Indica si requiere aviso de salida al IESS (S/N)';
COMMENT ON COLUMN RHH.CSTR.CSTRACSU IS 'Indica si requiere registro de acta de finiquito en el SUT (S/N)';
COMMENT ON COLUMN RHH.CSTR.CSTRESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.CSTR.CSTRFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.CSTR.CSTRUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.CPNM (ConceptoNomina)
-- DESCRIPCION: PIEZA CENTRAL DEL MOTOR. Catalogo configurable de todos
--              los conceptos del rol: ingresos, egresos, aportes
--              patronales y provisiones. El rol de pago se construye
--              recorriendo esta tabla; no hay conceptos en codigo Java.
--              Lleva planCuenta directo, igual que PGS.GRPP (GrupoProductoPago).
-- =====================================================
CREATE TABLE RHH.CPNM (
    CPNMCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL,        -- FK a Empresa
    CPNMNMBR VARCHAR2(100) NOT NULL, -- Nombre del concepto
    CPNMABRV VARCHAR2(20),           -- Abreviatura para el rol de pago
    CPNMALTR NUMBER NOT NULL,        -- Codigo alterno estable del concepto

    -- CLASIFICACION (todas apuntan a detalles de rubros)
    CPNMTPCN NUMBER NOT NULL, -- Tipo de concepto (rubro RHH_TIPO_CONCEPTO_NOMINA)
    CPNMTPCL NUMBER NOT NULL, -- Tipo de calculo (rubro RHH_TIPO_CALCULO_CONCEPTO)
    CPNMBSCL NUMBER,          -- Base de calculo (rubro RHH_BASE_CALCULO)
    CPNMTPRL NUMBER,          -- Relacion laboral a la que aplica (rubro RHH_TIPO_RELACION_LABORAL); NULL = todas
    CPNMROLM NUMBER,          -- Rol del concepto en el motor (rubro RHH_ROL_CONCEPTO_MOTOR); NULL = concepto ordinario

    -- VALORES DE CALCULO
    CPNMVLRR NUMBER(18,2),  -- Valor fijo, cuando el tipo de calculo es VALOR_FIJO
    CPNMPRCN NUMBER(18,6),  -- Porcentaje, cuando el tipo de calculo es PORCENTAJE_SOBRE_BASE
    CPNMFRML VARCHAR2(500), -- Expresion de la formula, cuando el tipo de calculo es FORMULA

    -- BANDERAS DE AFECTACION
    CPNMIMIE VARCHAR2(1) DEFAULT 'N', -- Es imponible IESS (S/N)
    CPNMIMIR VARCHAR2(1) DEFAULT 'N', -- Es gravado para impuesto a la renta (S/N)
    CPNMAPFR VARCHAR2(1) DEFAULT 'N', -- Forma parte de la base de fondos de reserva (S/N)
    CPNMBSDT VARCHAR2(1) DEFAULT 'N', -- Forma parte de la base del decimo tercero (S/N)
    CPNMBSDC VARCHAR2(1) DEFAULT 'N', -- Forma parte de la base del decimo cuarto (S/N)
    CPNMBSVC VARCHAR2(1) DEFAULT 'N', -- Forma parte de la base de vacaciones (S/N)
    CPNMBSUT VARCHAR2(1) DEFAULT 'N', -- Forma parte de la base de utilidades (S/N)
    CPNMPTRN VARCHAR2(1) DEFAULT 'N', -- Es costo patronal y no afecta el neto (S/N)
    CPNMPRVS VARCHAR2(1) DEFAULT 'N', -- Genera provision contable (S/N)
    CPNMOBLG VARCHAR2(1) DEFAULT 'N', -- Se aplica automaticamente a todo contrato vigente (S/N)
    CPNMRCRT VARCHAR2(1) DEFAULT 'S', -- Puede recortarse ante neto negativo (S/N); los de ley van en 'N'

    -- MAPEO A SALIDAS OFICIALES
    CPNMRDEP VARCHAR2(10), -- Casillero del anexo RDEP del SRI
    CPNMIESS VARCHAR2(10), -- Codigo del concepto en la planilla del IESS
    CPNMF107 VARCHAR2(10), -- Casillero del formulario 107

    -- CONTABILIDAD
    PLNNCDGO NUMBER, -- FK a PlanCuenta: cuenta propia del concepto (gasto o pasivo especifico)
    DTPLCDGO NUMBER, -- FK a DetallePlantilla: linea de plantilla contable, si el concepto usa una

    CPNMORDN NUMBER, -- Orden de presentacion en el rol y prelacion ante neto negativo

    CPNMESTD NUMBER DEFAULT 1,
    CPNMFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CPNMUSRR VARCHAR2(60),

    CONSTRAINT PK_CPNM PRIMARY KEY (CPNMCDGO),
    CONSTRAINT UQ_CPNM_ALTR UNIQUE (PJRQCDGO, CPNMALTR),
    CONSTRAINT FK_CPNM_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_CPNM_PLNN FOREIGN KEY (PLNNCDGO) REFERENCES CNT.PLNN(PLNNCDGO),
    CONSTRAINT FK_CPNM_DTPL FOREIGN KEY (DTPLCDGO) REFERENCES CNT.DTPL(DTPLCDGO)
);

CREATE INDEX IDX_CPNM_PJRQ ON RHH.CPNM(PJRQCDGO);
CREATE INDEX IDX_CPNM_PLNN ON RHH.CPNM(PLNNCDGO);
CREATE INDEX IDX_CPNM_DTPL ON RHH.CPNM(DTPLCDGO);
CREATE INDEX IDX_CPNM_TPCN ON RHH.CPNM(CPNMTPCN);
-- El motor busca por rol en cada calculo: el indice unico ademas impide que dos
-- conceptos de la misma empresa reclamen el mismo rol, que romperia el calculo en
-- silencio. Los NULL no participan del unique en Oracle, asi que los conceptos
-- ordinarios conviven sin restriccion.
CREATE UNIQUE INDEX UQ_CPNM_ROLM ON RHH.CPNM(PJRQCDGO, CPNMROLM);

COMMENT ON TABLE  RHH.CPNM IS 'Catalogo configurable de conceptos de nomina. Define que se calcula, como, sobre que base, si es imponible y contra que cuenta contable';
COMMENT ON COLUMN RHH.CPNM.CPNMCDGO IS 'Codigo unico del concepto (PK autoincremental)';
COMMENT ON COLUMN RHH.CPNM.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.CPNM.CPNMNMBR IS 'Nombre del concepto tal como aparece en el rol de pago';
COMMENT ON COLUMN RHH.CPNM.CPNMABRV IS 'Abreviatura del concepto para reportes de ancho limitado';
COMMENT ON COLUMN RHH.CPNM.CPNMALTR IS 'Codigo alterno estable del concepto, usado por el codigo para referenciarlo sin depender de la PK';
COMMENT ON COLUMN RHH.CPNM.CPNMTPCN IS 'Tipo de concepto: detalle del rubro RHH_TIPO_CONCEPTO_NOMINA (ingreso, egreso, patronal, provision, informativo)';
COMMENT ON COLUMN RHH.CPNM.CPNMTPCL IS 'Tipo de calculo: detalle del rubro RHH_TIPO_CALCULO_CONCEPTO';
COMMENT ON COLUMN RHH.CPNM.CPNMBSCL IS 'Base sobre la que se calcula: detalle del rubro RHH_BASE_CALCULO';
COMMENT ON COLUMN RHH.CPNM.CPNMTPRL IS 'Relacion laboral a la que aplica el concepto; NULL significa que aplica a todas';
COMMENT ON COLUMN RHH.CPNM.CPNMVLRR IS 'Valor fijo del concepto cuando el tipo de calculo es VALOR_FIJO';
COMMENT ON COLUMN RHH.CPNM.CPNMPRCN IS 'Porcentaje del concepto cuando el tipo de calculo es PORCENTAJE_SOBRE_BASE';
COMMENT ON COLUMN RHH.CPNM.CPNMFRML IS 'Expresion de la formula cuando el tipo de calculo es FORMULA';
COMMENT ON COLUMN RHH.CPNM.CPNMIMIE IS 'Indica si el concepto es materia gravada del IESS (S/N)';
COMMENT ON COLUMN RHH.CPNM.CPNMIMIR IS 'Indica si el concepto es ingreso gravado de impuesto a la renta (S/N)';
COMMENT ON COLUMN RHH.CPNM.CPNMAPFR IS 'Indica si el concepto forma parte de la base de fondos de reserva (S/N)';
COMMENT ON COLUMN RHH.CPNM.CPNMBSDT IS 'Indica si el concepto forma parte de la base del decimo tercero (S/N)';
COMMENT ON COLUMN RHH.CPNM.CPNMBSDC IS 'Indica si el concepto forma parte de la base del decimo cuarto (S/N)';
COMMENT ON COLUMN RHH.CPNM.CPNMBSVC IS 'Indica si el concepto forma parte de la base de vacaciones (S/N)';
COMMENT ON COLUMN RHH.CPNM.CPNMBSUT IS 'Indica si el concepto forma parte de la base de utilidades (S/N)';
COMMENT ON COLUMN RHH.CPNM.CPNMPTRN IS 'Indica si el concepto es costo patronal, es decir no afecta el neto a pagar (S/N)';
COMMENT ON COLUMN RHH.CPNM.CPNMPRVS IS 'Indica si el concepto genera provision contable en lugar de renglon de rol (S/N)';
COMMENT ON COLUMN RHH.CPNM.CPNMOBLG IS 'Indica si el concepto se aplica automaticamente a todo contrato vigente (S/N)';
COMMENT ON COLUMN RHH.CPNM.CPNMRCRT IS 'Indica si el concepto puede recortarse cuando el neto resulta negativo (S/N); los descuentos de ley van en N';
COMMENT ON COLUMN RHH.CPNM.CPNMROLM IS 'Rol que cumple el concepto dentro del motor de calculo: detalle del rubro RHH_ROL_CONCEPTO_MOTOR. Es como el motor localiza el aporte personal, los decimos, las horas extra o los prestamos, sin depender del codigo alterno ni de la combinacion de tipo y base. NULL en los conceptos ordinarios, que el motor trata genericamente. Debe ser unico por empresa: dos conceptos con el mismo rol es un error de parametrizacion';
COMMENT ON COLUMN RHH.CPNM.CPNMRDEP IS 'Casillero del anexo RDEP del SRI al que se acumula el concepto';
COMMENT ON COLUMN RHH.CPNM.CPNMIESS IS 'Codigo del concepto en la planilla de aportes del IESS';
COMMENT ON COLUMN RHH.CPNM.CPNMF107 IS 'Casillero del formulario 107 al que se acumula el concepto';
COMMENT ON COLUMN RHH.CPNM.PLNNCDGO IS 'FK a CNT.PLNN: cuenta contable propia del concepto (gasto o pasivo especifico)';
COMMENT ON COLUMN RHH.CPNM.DTPLCDGO IS 'FK a CNT.DTPL: linea de plantilla contable asociada, cuando el concepto se contabiliza por plantilla';
COMMENT ON COLUMN RHH.CPNM.CPNMORDN IS 'Orden de presentacion en el rol; tambien define la prelacion de recorte ante neto negativo';
COMMENT ON COLUMN RHH.CPNM.CPNMESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.CPNM.CPNMFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.CPNM.CPNMUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.FMRC (FormatoArchivoMarcacion)
-- DESCRIPCION: Definicion del formato del archivo que exporta el reloj
--              biometrico. Permite soportar cualquier marca sin tocar codigo.
-- =====================================================
CREATE TABLE RHH.FMRC (
    FMRCCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL,        -- FK a Empresa
    FMRCNMBR VARCHAR2(100) NOT NULL, -- Nombre del formato
    FMRCMRCA VARCHAR2(100),          -- Marca y modelo del dispositivo
    FMRCTPFR NUMBER NOT NULL,        -- Tipo de formato (rubro RHH_FORMATO_ARCHIVO_MARCACION)

    FMRCDLMT VARCHAR2(5),   -- Caracter delimitador, en formatos delimitados
    FMRCLNCB NUMBER DEFAULT 0, -- Lineas de cabecera a saltar
    FMRCLNPI NUMBER DEFAULT 0, -- Lineas de pie a ignorar
    FMRCFRFC VARCHAR2(30),  -- Patron de formato de la fecha
    FMRCFRHR VARCHAR2(30),  -- Patron de formato de la hora
    FMRCFRFH VARCHAR2(50),  -- Patron de formato de fecha y hora combinadas
    FMRCCDFC VARCHAR2(30),  -- Codificacion del archivo

    FMRCESTD NUMBER DEFAULT 1,
    FMRCFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FMRCUSRR VARCHAR2(60),

    CONSTRAINT PK_FMRC PRIMARY KEY (FMRCCDGO),
    CONSTRAINT FK_FMRC_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO)
);

CREATE INDEX IDX_FMRC_PJRQ ON RHH.FMRC(PJRQCDGO);

COMMENT ON TABLE  RHH.FMRC IS 'Definicion del formato del archivo de marcaciones exportado por el reloj biometrico, parametrizable por marca y modelo';
COMMENT ON COLUMN RHH.FMRC.FMRCCDGO IS 'Codigo unico del formato (PK autoincremental)';
COMMENT ON COLUMN RHH.FMRC.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.FMRC.FMRCNMBR IS 'Nombre descriptivo del formato';
COMMENT ON COLUMN RHH.FMRC.FMRCMRCA IS 'Marca y modelo del dispositivo biometrico que genera el archivo';
COMMENT ON COLUMN RHH.FMRC.FMRCTPFR IS 'Tipo de formato: detalle del rubro RHH_FORMATO_ARCHIVO_MARCACION (ancho fijo, delimitado, CSV, Excel)';
COMMENT ON COLUMN RHH.FMRC.FMRCDLMT IS 'Caracter delimitador de campos en formatos delimitados';
COMMENT ON COLUMN RHH.FMRC.FMRCLNCB IS 'Numero de lineas de cabecera que se saltan al leer el archivo';
COMMENT ON COLUMN RHH.FMRC.FMRCLNPI IS 'Numero de lineas de pie que se ignoran al leer el archivo';
COMMENT ON COLUMN RHH.FMRC.FMRCFRFC IS 'Patron de formato de la fecha, compatible con DateTimeFormatter';
COMMENT ON COLUMN RHH.FMRC.FMRCFRHR IS 'Patron de formato de la hora, compatible con DateTimeFormatter';
COMMENT ON COLUMN RHH.FMRC.FMRCFRFH IS 'Patron de formato de fecha y hora combinadas cuando vienen en un solo campo';
COMMENT ON COLUMN RHH.FMRC.FMRCCDFC IS 'Codificacion de caracteres del archivo, por ejemplo UTF-8 o ISO-8859-1';
COMMENT ON COLUMN RHH.FMRC.FMRCESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.FMRC.FMRCFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.FMRC.FMRCUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.DFMR (DetalleFormatoMarcacion)
-- DESCRIPCION: Mapeo campo a campo del archivo del biometrico.
-- =====================================================
CREATE TABLE RHH.DFMR (
    DFMRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    FMRCCDGO NUMBER NOT NULL, -- FK a FormatoArchivoMarcacion
    DFMRCMPO NUMBER NOT NULL, -- Campo logico (rubro RHH_CAMPO_ARCHIVO_MARCACION)
    DFMRORDN NUMBER NOT NULL, -- Orden del campo en la linea

    DFMRPSCN NUMBER,          -- Posicion del campo en formatos delimitados (base 1)
    DFMRINCO NUMBER,          -- Indice de inicio en formatos de ancho fijo (base 0)
    DFMRLNGT NUMBER,          -- Longitud del campo en formatos de ancho fijo
    DFMRMPEO VARCHAR2(500),   -- Mapeo de valores origen a codigos del sistema
    DFMROBLG VARCHAR2(1) DEFAULT 'S', -- Campo obligatorio (S/N)

    DFMRESTD NUMBER DEFAULT 1,
    DFMRFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DFMRUSRR VARCHAR2(60),

    CONSTRAINT PK_DFMR PRIMARY KEY (DFMRCDGO),
    CONSTRAINT FK_DFMR_FMRC FOREIGN KEY (FMRCCDGO) REFERENCES RHH.FMRC(FMRCCDGO)
);

CREATE INDEX IDX_DFMR_FMRC ON RHH.DFMR(FMRCCDGO);

COMMENT ON TABLE  RHH.DFMR IS 'Mapeo campo a campo del archivo de marcaciones: posicion, longitud y traduccion de codigos';
COMMENT ON COLUMN RHH.DFMR.DFMRCDGO IS 'Codigo unico del detalle (PK autoincremental)';
COMMENT ON COLUMN RHH.DFMR.FMRCCDGO IS 'FK a RHH.FMRC (formato al que pertenece el campo)';
COMMENT ON COLUMN RHH.DFMR.DFMRCMPO IS 'Campo logico que representa: detalle del rubro RHH_CAMPO_ARCHIVO_MARCACION';
COMMENT ON COLUMN RHH.DFMR.DFMRORDN IS 'Orden del campo dentro de la linea del archivo';
COMMENT ON COLUMN RHH.DFMR.DFMRPSCN IS 'Posicion del campo en formatos delimitados, comenzando en 1';
COMMENT ON COLUMN RHH.DFMR.DFMRINCO IS 'Indice de inicio del campo en formatos de ancho fijo, comenzando en 0';
COMMENT ON COLUMN RHH.DFMR.DFMRLNGT IS 'Longitud del campo en formatos de ancho fijo';
COMMENT ON COLUMN RHH.DFMR.DFMRMPEO IS 'Mapeo de valores del archivo a codigos del sistema, con formato origen=destino separado por punto y coma';
COMMENT ON COLUMN RHH.DFMR.DFMROBLG IS 'Indica si el campo es obligatorio; si falta, la linea se rechaza (S/N)';
COMMENT ON COLUMN RHH.DFMR.DFMRESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.DFMR.DFMRFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.DFMR.DFMRUSRR IS 'Usuario que registro';
