-- =====================================================
-- MODULO: RHH (Recursos Humanos) - TABLAS DEL MAESTRO DE PERSONAL
-- DESCRIPCION: Datos del colaborador que la normativa exige y que hoy
--              no existen: cargas familiares, cuentas bancarias, gastos
--              personales proyectados, conceptos fijos y novedades IESS.
-- ORDEN DE EJECUCION: 2 de 6
-- FECHA: 2026-08-19
-- =====================================================


-- =====================================================
-- TABLA: RHH.CRGF (CargaFamiliar)
-- DESCRIPCION: Dependientes del empleado. Determina el tope de la rebaja
--              por gastos personales y el reparto del 5% de utilidades.
-- =====================================================
CREATE TABLE RHH.CRGF (
    CRGFCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    MPLDCDGO NUMBER NOT NULL,        -- FK a Empleado
    CRGFPRNT NUMBER NOT NULL,        -- Parentesco (rubro RHH_PARENTESCO_CARGA)
    CRGFIDNT VARCHAR2(20),           -- Identificacion del dependiente
    CRGFAPLL VARCHAR2(100) NOT NULL, -- Apellidos del dependiente
    CRGFNMBR VARCHAR2(100) NOT NULL, -- Nombres del dependiente
    CRGFFCHN DATE,                   -- Fecha de nacimiento

    CRGFDSCP VARCHAR2(1) DEFAULT 'N', -- Tiene discapacidad (S/N)
    CRGFPRDS NUMBER(5,2),             -- Porcentaje de discapacidad
    CRGFIRRB VARCHAR2(1) DEFAULT 'S', -- Califica como carga para la rebaja de IR (S/N)
    CRGFUTIL VARCHAR2(1) DEFAULT 'S', -- Califica para el reparto de utilidades (S/N)
    CRGFDPEC VARCHAR2(1) DEFAULT 'S', -- Depende economicamente del empleado (S/N)

    CRGFFCIN DATE, -- Fecha desde la que rige como carga
    CRGFFCFN DATE, -- Fecha hasta la que rige como carga

    CRGFESTD NUMBER DEFAULT 1,
    CRGFFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CRGFUSRR VARCHAR2(60),

    CONSTRAINT PK_CRGF PRIMARY KEY (CRGFCDGO),
    CONSTRAINT FK_CRGF_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO)
);

CREATE INDEX IDX_CRGF_MPLD ON RHH.CRGF(MPLDCDGO);

COMMENT ON TABLE  RHH.CRGF IS 'Cargas familiares del empleado. Determinan el tope de la rebaja por gastos personales y el reparto del 5 por ciento de utilidades';
COMMENT ON COLUMN RHH.CRGF.CRGFCDGO IS 'Codigo unico de la carga familiar (PK autoincremental)';
COMMENT ON COLUMN RHH.CRGF.MPLDCDGO IS 'FK a RHH.MPLD (empleado titular)';
COMMENT ON COLUMN RHH.CRGF.CRGFPRNT IS 'Parentesco: detalle del rubro RHH_PARENTESCO_CARGA';
COMMENT ON COLUMN RHH.CRGF.CRGFIDNT IS 'Numero de identificacion del dependiente';
COMMENT ON COLUMN RHH.CRGF.CRGFAPLL IS 'Apellidos del dependiente';
COMMENT ON COLUMN RHH.CRGF.CRGFNMBR IS 'Nombres del dependiente';
COMMENT ON COLUMN RHH.CRGF.CRGFFCHN IS 'Fecha de nacimiento del dependiente; determina el limite de 21 anios para hijos';
COMMENT ON COLUMN RHH.CRGF.CRGFDSCP IS 'Indica si el dependiente tiene discapacidad (S/N); si la tiene no aplica el limite de edad';
COMMENT ON COLUMN RHH.CRGF.CRGFPRDS IS 'Porcentaje de discapacidad del dependiente';
COMMENT ON COLUMN RHH.CRGF.CRGFIRRB IS 'Indica si califica como carga para el tope de la rebaja por gastos personales (S/N)';
COMMENT ON COLUMN RHH.CRGF.CRGFUTIL IS 'Indica si califica para el reparto del 5 por ciento de utilidades (S/N)';
COMMENT ON COLUMN RHH.CRGF.CRGFDPEC IS 'Indica si depende economicamente del empleado (S/N)';
COMMENT ON COLUMN RHH.CRGF.CRGFFCIN IS 'Fecha desde la que rige como carga familiar';
COMMENT ON COLUMN RHH.CRGF.CRGFFCFN IS 'Fecha hasta la que rige como carga familiar';
COMMENT ON COLUMN RHH.CRGF.CRGFESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.CRGF.CRGFFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.CRGF.CRGFUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.CBEM (CuentaBancariaEmpleado)
-- DESCRIPCION: Cuentas de acreditacion del sueldo. Soporta reparto del
--              neto entre varias cuentas mediante porcentaje.
-- =====================================================
CREATE TABLE RHH.CBEM (
    CBEMCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    MPLDCDGO NUMBER NOT NULL,       -- FK a Empleado
    BNCOCDGO NUMBER,                -- FK a Banco (TSR.BNCO)
    CBEMTPCT NUMBER NOT NULL,       -- Tipo de cuenta (rubro RHH_TIPO_CUENTA_BANCARIA)
    CBEMNMCT VARCHAR2(30) NOT NULL, -- Numero de cuenta
    CBEMTTLR VARCHAR2(200),         -- Titular de la cuenta, si difiere del empleado
    CBEMIDTT VARCHAR2(20),          -- Identificacion del titular de la cuenta

    CBEMPRCP VARCHAR2(1) DEFAULT 'S', -- Es la cuenta principal (S/N)
    CBEMPRCN NUMBER(18,6),            -- Porcentaje del neto a acreditar en esta cuenta

    CBEMESTD NUMBER DEFAULT 1,
    CBEMFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CBEMUSRR VARCHAR2(60),

    CONSTRAINT PK_CBEM PRIMARY KEY (CBEMCDGO),
    CONSTRAINT FK_CBEM_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO)
);

CREATE INDEX IDX_CBEM_MPLD ON RHH.CBEM(MPLDCDGO);

COMMENT ON TABLE  RHH.CBEM IS 'Cuentas bancarias de acreditacion del sueldo del empleado, con soporte de reparto por porcentaje';
COMMENT ON COLUMN RHH.CBEM.CBEMCDGO IS 'Codigo unico de la cuenta (PK autoincremental)';
COMMENT ON COLUMN RHH.CBEM.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.CBEM.BNCOCDGO IS 'FK al banco (TSR.BNCO)';
COMMENT ON COLUMN RHH.CBEM.CBEMTPCT IS 'Tipo de cuenta: detalle del rubro RHH_TIPO_CUENTA_BANCARIA (ahorros, corriente)';
COMMENT ON COLUMN RHH.CBEM.CBEMNMCT IS 'Numero de la cuenta bancaria';
COMMENT ON COLUMN RHH.CBEM.CBEMTTLR IS 'Nombre del titular de la cuenta cuando no es el propio empleado';
COMMENT ON COLUMN RHH.CBEM.CBEMIDTT IS 'Identificacion del titular de la cuenta';
COMMENT ON COLUMN RHH.CBEM.CBEMPRCP IS 'Indica si es la cuenta principal de acreditacion (S/N)';
COMMENT ON COLUMN RHH.CBEM.CBEMPRCN IS 'Porcentaje del neto que se acredita en esta cuenta cuando el pago se reparte';
COMMENT ON COLUMN RHH.CBEM.CBEMESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.CBEM.CBEMFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.CBEM.CBEMUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.GSPR (GastoPersonalProyectado)
-- DESCRIPCION: Proyeccion anual de gastos personales que declara el
--              empleado. Insumo obligatorio de la rebaja del IR.
-- =====================================================
CREATE TABLE RHH.GSPR (
    GSPRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    MPLDCDGO NUMBER NOT NULL,       -- FK a Empleado
    GSPRANOO NUMBER NOT NULL,       -- Anio fiscal de la proyeccion
    GSPRTPGP NUMBER NOT NULL,       -- Tipo de gasto (rubro RHH_TIPO_GASTO_PERSONAL)
    GSPRVLOR NUMBER(18,2) NOT NULL, -- Valor proyectado del gasto

    GSPRFCPR DATE,                    -- Fecha de presentacion de la proyeccion
    GSPRVGNT VARCHAR2(1) DEFAULT 'S', -- Es la version vigente (S/N)

    GSPRESTD NUMBER DEFAULT 1,
    GSPRFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    GSPRUSRR VARCHAR2(60),

    CONSTRAINT PK_GSPR PRIMARY KEY (GSPRCDGO),
    CONSTRAINT FK_GSPR_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO)
);

CREATE INDEX IDX_GSPR_MPLD ON RHH.GSPR(MPLDCDGO);
CREATE INDEX IDX_GSPR_ANIO ON RHH.GSPR(GSPRANOO);

COMMENT ON TABLE  RHH.GSPR IS 'Proyeccion anual de gastos personales declarada por el empleado, por categoria. Insumo de la rebaja del impuesto a la renta';
COMMENT ON COLUMN RHH.GSPR.GSPRCDGO IS 'Codigo unico del gasto proyectado (PK autoincremental)';
COMMENT ON COLUMN RHH.GSPR.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.GSPR.GSPRANOO IS 'Anio fiscal al que corresponde la proyeccion';
COMMENT ON COLUMN RHH.GSPR.GSPRTPGP IS 'Categoria del gasto: detalle del rubro RHH_TIPO_GASTO_PERSONAL';
COMMENT ON COLUMN RHH.GSPR.GSPRVLOR IS 'Valor anual proyectado del gasto en esa categoria';
COMMENT ON COLUMN RHH.GSPR.GSPRFCPR IS 'Fecha en que el empleado presento la proyeccion';
COMMENT ON COLUMN RHH.GSPR.GSPRVGNT IS 'Indica si es la version vigente de la proyeccion (S/N); las anteriores quedan en N';
COMMENT ON COLUMN RHH.GSPR.GSPRESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.GSPR.GSPRFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.GSPR.GSPRUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.CPXM (ConceptoFijoEmpleado)
-- DESCRIPCION: Conceptos que se repiten todos los meses para un empleado
--              concreto (bonos de responsabilidad, movilizacion, etc.).
--              Se diferencian de RHH.NVNM, que son de un solo periodo.
-- =====================================================
CREATE TABLE RHH.CPXM (
    CPXMCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado
    CNTECDGO NUMBER,          -- FK a ContratoEmpleado
    CPNMCDGO NUMBER NOT NULL, -- FK a ConceptoNomina

    CPXMVLRR NUMBER(18,2), -- Valor fijo del concepto para este empleado
    CPXMPRCN NUMBER(18,6), -- Porcentaje, si el concepto es porcentual
    CPXMCANT NUMBER(18,4), -- Cantidad, si el concepto es por cantidad

    CPXMFCHI DATE NOT NULL, -- Vigente desde
    CPXMFCHF DATE,          -- Vigente hasta; NULL significa indefinido
    CPXMOBSR VARCHAR2(500), -- Observaciones

    CPXMESTD NUMBER DEFAULT 1,
    CPXMFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CPXMUSRR VARCHAR2(60),

    CONSTRAINT PK_CPXM PRIMARY KEY (CPXMCDGO),
    CONSTRAINT FK_CPXM_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO),
    CONSTRAINT FK_CPXM_CNTE FOREIGN KEY (CNTECDGO) REFERENCES RHH.CNTE(CNTECDGO),
    CONSTRAINT FK_CPXM_CPNM FOREIGN KEY (CPNMCDGO) REFERENCES RHH.CPNM(CPNMCDGO)
);

CREATE INDEX IDX_CPXM_MPLD ON RHH.CPXM(MPLDCDGO);
CREATE INDEX IDX_CPXM_CNTE ON RHH.CPXM(CNTECDGO);
CREATE INDEX IDX_CPXM_CPNM ON RHH.CPXM(CPNMCDGO);

COMMENT ON TABLE  RHH.CPXM IS 'Conceptos fijos que se aplican todos los meses a un empleado concreto, con su vigencia';
COMMENT ON COLUMN RHH.CPXM.CPXMCDGO IS 'Codigo unico del concepto fijo (PK autoincremental)';
COMMENT ON COLUMN RHH.CPXM.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.CPXM.CNTECDGO IS 'FK a RHH.CNTE (contrato al que se asocia)';
COMMENT ON COLUMN RHH.CPXM.CPNMCDGO IS 'FK a RHH.CPNM (concepto de nomina que se aplica)';
COMMENT ON COLUMN RHH.CPXM.CPXMVLRR IS 'Valor fijo del concepto para este empleado';
COMMENT ON COLUMN RHH.CPXM.CPXMPRCN IS 'Porcentaje del concepto para este empleado, si es porcentual';
COMMENT ON COLUMN RHH.CPXM.CPXMCANT IS 'Cantidad del concepto para este empleado, si es por cantidad';
COMMENT ON COLUMN RHH.CPXM.CPXMFCHI IS 'Fecha desde la que el concepto esta vigente para el empleado';
COMMENT ON COLUMN RHH.CPXM.CPXMFCHF IS 'Fecha hasta la que el concepto esta vigente; NULL significa indefinido';
COMMENT ON COLUMN RHH.CPXM.CPXMOBSR IS 'Observaciones sobre la asignacion del concepto';
COMMENT ON COLUMN RHH.CPXM.CPXMESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.CPXM.CPXMFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.CPXM.CPXMUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.NVIS (NovedadIess)
-- DESCRIPCION: Avisos de entrada, salida y modificacion de sueldo que
--              el empleador debe reportar al IESS dentro de plazo.
-- =====================================================
CREATE TABLE RHH.NVIS (
    NVISCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado
    CNTECDGO NUMBER,          -- FK a ContratoEmpleado
    NVISTPNV NUMBER NOT NULL, -- Tipo de novedad (rubro RHH_TIPO_NOVEDAD_IESS)

    NVISFCHC DATE NOT NULL, -- Fecha del hecho que se reporta
    NVISFCLM DATE,          -- Fecha limite legal para reportarlo
    NVISFCRP DATE,          -- Fecha en que efectivamente se reporto

    NVISSLAN NUMBER(18,2), -- Sueldo anterior, en modificaciones
    NVISSLNW NUMBER(18,2), -- Sueldo nuevo, en modificaciones
    NVISMDFR NUMBER,       -- Modalidad de fondos de reserva (rubro RHH_MODALIDAD_FONDOS_RESERVA)
    NVISCSTR NUMBER,       -- FK a CausalTerminacion, en avisos de salida

    NVISESTD NUMBER DEFAULT 1, -- Estado de envio (rubro RHH_ESTADO_NOVEDAD_IESS)
    NVISOBSR VARCHAR2(500),
    NVISFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NVISUSRR VARCHAR2(60),

    CONSTRAINT PK_NVIS PRIMARY KEY (NVISCDGO),
    CONSTRAINT FK_NVIS_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO),
    CONSTRAINT FK_NVIS_CNTE FOREIGN KEY (CNTECDGO) REFERENCES RHH.CNTE(CNTECDGO),
    CONSTRAINT FK_NVIS_CSTR FOREIGN KEY (NVISCSTR) REFERENCES RHH.CSTR(CSTRCDGO)
);

CREATE INDEX IDX_NVIS_MPLD ON RHH.NVIS(MPLDCDGO);
CREATE INDEX IDX_NVIS_CNTE ON RHH.NVIS(CNTECDGO);
CREATE INDEX IDX_NVIS_CSTR ON RHH.NVIS(NVISCSTR);

COMMENT ON TABLE  RHH.NVIS IS 'Novedades que el empleador debe reportar al IESS: avisos de entrada, de salida y modificaciones de sueldo, con su plazo legal';
COMMENT ON COLUMN RHH.NVIS.NVISCDGO IS 'Codigo unico de la novedad (PK autoincremental)';
COMMENT ON COLUMN RHH.NVIS.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.NVIS.CNTECDGO IS 'FK a RHH.CNTE (contrato relacionado)';
COMMENT ON COLUMN RHH.NVIS.NVISTPNV IS 'Tipo de novedad: detalle del rubro RHH_TIPO_NOVEDAD_IESS';
COMMENT ON COLUMN RHH.NVIS.NVISFCHC IS 'Fecha del hecho que se reporta (ingreso, salida o cambio de sueldo)';
COMMENT ON COLUMN RHH.NVIS.NVISFCLM IS 'Fecha limite legal para reportar la novedad al IESS';
COMMENT ON COLUMN RHH.NVIS.NVISFCRP IS 'Fecha en que la novedad fue efectivamente reportada';
COMMENT ON COLUMN RHH.NVIS.NVISSLAN IS 'Sueldo anterior, aplicable a novedades de modificacion de sueldo';
COMMENT ON COLUMN RHH.NVIS.NVISSLNW IS 'Sueldo nuevo, aplicable a novedades de modificacion de sueldo';
COMMENT ON COLUMN RHH.NVIS.NVISMDFR IS 'Modalidad de fondos de reserva declarada: detalle del rubro RHH_MODALIDAD_FONDOS_RESERVA';
COMMENT ON COLUMN RHH.NVIS.NVISCSTR IS 'FK a RHH.CSTR (causal de terminacion), aplicable a avisos de salida';
COMMENT ON COLUMN RHH.NVIS.NVISESTD IS 'Estado de envio: detalle del rubro RHH_ESTADO_NOVEDAD_IESS';
COMMENT ON COLUMN RHH.NVIS.NVISOBSR IS 'Observaciones sobre la novedad';
COMMENT ON COLUMN RHH.NVIS.NVISFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.NVIS.NVISUSRR IS 'Usuario que registro';
