-- =====================================================
-- MODULO: RHH (Recursos Humanos) - TABLAS DEL MOTOR DE NOMINA
-- DESCRIPCION: Novedades, provisiones, acumulados, proyeccion de IR,
--              beneficios sociales, descuentos recurrentes y horas extra.
-- ORDEN DE EJECUCION: 3 de 6
-- FECHA: 2026-08-19
-- =====================================================


-- =====================================================
-- TABLA: RHH.NVNM (NovedadNomina)
-- DESCRIPCION: Ingresos y descuentos puntuales de un solo periodo.
--              Es tambien la via por la que se cargan a mano los dias
--              trabajados de la nomina historica ene-jul 2026.
-- =====================================================
CREATE TABLE RHH.NVNM (
    NVNMCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PRDNCDGO NUMBER NOT NULL, -- FK a PeriodoNomina
    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado
    CPNMCDGO NUMBER NOT NULL, -- FK a ConceptoNomina

    NVNMCANT NUMBER(18,4),          -- Cantidad (horas, dias, unidades)
    NVNMVLRR NUMBER(18,2) NOT NULL, -- Valor de la novedad
    NVNMDSCR VARCHAR2(300),         -- Descripcion

    NVNMAPRB VARCHAR2(1) DEFAULT 'N', -- Aprobada para su inclusion en el calculo (S/N)
    NVNMUSAP VARCHAR2(60),            -- Usuario que aprobo
    NVNMFCAP DATE,                    -- Fecha de aprobacion

    NVNMESTD NUMBER DEFAULT 1,
    NVNMFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NVNMUSRR VARCHAR2(60),

    CONSTRAINT PK_NVNM PRIMARY KEY (NVNMCDGO),
    CONSTRAINT FK_NVNM_PRDN FOREIGN KEY (PRDNCDGO) REFERENCES RHH.PRDN(PRDNCDGO),
    CONSTRAINT FK_NVNM_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO),
    CONSTRAINT FK_NVNM_CPNM FOREIGN KEY (CPNMCDGO) REFERENCES RHH.CPNM(CPNMCDGO)
);

CREATE INDEX IDX_NVNM_PRDN ON RHH.NVNM(PRDNCDGO);
CREATE INDEX IDX_NVNM_MPLD ON RHH.NVNM(MPLDCDGO);
CREATE INDEX IDX_NVNM_CPNM ON RHH.NVNM(CPNMCDGO);

COMMENT ON TABLE  RHH.NVNM IS 'Novedades puntuales de un periodo de nomina: ingresos y descuentos que no se repiten. Tambien es la via de carga manual de la nomina historica';
COMMENT ON COLUMN RHH.NVNM.NVNMCDGO IS 'Codigo unico de la novedad (PK autoincremental)';
COMMENT ON COLUMN RHH.NVNM.PRDNCDGO IS 'FK a RHH.PRDN (periodo de nomina)';
COMMENT ON COLUMN RHH.NVNM.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.NVNM.CPNMCDGO IS 'FK a RHH.CPNM (concepto de nomina)';
COMMENT ON COLUMN RHH.NVNM.NVNMCANT IS 'Cantidad asociada a la novedad (horas, dias o unidades)';
COMMENT ON COLUMN RHH.NVNM.NVNMVLRR IS 'Valor monetario de la novedad';
COMMENT ON COLUMN RHH.NVNM.NVNMDSCR IS 'Descripcion o justificacion de la novedad';
COMMENT ON COLUMN RHH.NVNM.NVNMAPRB IS 'Indica si la novedad esta aprobada para entrar al calculo (S/N)';
COMMENT ON COLUMN RHH.NVNM.NVNMUSAP IS 'Usuario que aprobo la novedad';
COMMENT ON COLUMN RHH.NVNM.NVNMFCAP IS 'Fecha de aprobacion de la novedad';
COMMENT ON COLUMN RHH.NVNM.NVNMESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.NVNM.NVNMFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.NVNM.NVNMUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.ACMN (AcumuladoNomina)
-- DESCRIPCION: Acumulados por empleado, anio, mes y tipo de base. Es la
--              memoria del motor: de aqui salen los decimos, los fondos
--              de reserva y la proyeccion del impuesto a la renta.
--              SE ESCRIBE EN cerrarPeriodo, NUNCA en calcularPeriodo,
--              para que los recalculos no dupliquen valores.
-- =====================================================
CREATE TABLE RHH.ACMN (
    ACMNCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado
    PRDNCDGO NUMBER,          -- FK a PeriodoNomina; NULL en saldos de apertura
    ACMNANOO NUMBER NOT NULL, -- Anio
    ACMNMSEE NUMBER NOT NULL, -- Mes
    ACMNTPAC NUMBER NOT NULL, -- Tipo de acumulado (rubro RHH_TIPO_ACUMULADO)

    ACMNVLOR NUMBER(18,2) DEFAULT 0, -- Valor acumulado en el mes
    ACMNDIAS NUMBER(18,4) DEFAULT 0, -- Dias trabajados del mes
    ACMNAPRT VARCHAR2(1) DEFAULT 'N', -- Proviene de saldo de apertura (S/N)

    ACMNESTD NUMBER DEFAULT 1,
    ACMNFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACMNUSRR VARCHAR2(60),

    CONSTRAINT PK_ACMN PRIMARY KEY (ACMNCDGO),
    CONSTRAINT UQ_ACMN_MES UNIQUE (MPLDCDGO, ACMNANOO, ACMNMSEE, ACMNTPAC),
    CONSTRAINT FK_ACMN_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO),
    CONSTRAINT FK_ACMN_PRDN FOREIGN KEY (PRDNCDGO) REFERENCES RHH.PRDN(PRDNCDGO)
);

CREATE INDEX IDX_ACMN_MPLD ON RHH.ACMN(MPLDCDGO);
CREATE INDEX IDX_ACMN_PRDN ON RHH.ACMN(PRDNCDGO);
CREATE INDEX IDX_ACMN_ANIO ON RHH.ACMN(ACMNANOO, ACMNMSEE);

COMMENT ON TABLE  RHH.ACMN IS 'Acumulados de nomina por empleado, anio, mes y tipo de base. Memoria del motor para decimos, fondos de reserva y proyeccion de impuesto a la renta';
COMMENT ON COLUMN RHH.ACMN.ACMNCDGO IS 'Codigo unico del acumulado (PK autoincremental)';
COMMENT ON COLUMN RHH.ACMN.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.ACMN.PRDNCDGO IS 'FK a RHH.PRDN (periodo que lo genero); NULL cuando proviene de un saldo de apertura';
COMMENT ON COLUMN RHH.ACMN.ACMNANOO IS 'Anio al que corresponde el acumulado';
COMMENT ON COLUMN RHH.ACMN.ACMNMSEE IS 'Mes al que corresponde el acumulado';
COMMENT ON COLUMN RHH.ACMN.ACMNTPAC IS 'Tipo de base acumulada: detalle del rubro RHH_TIPO_ACUMULADO';
COMMENT ON COLUMN RHH.ACMN.ACMNVLOR IS 'Valor acumulado en el mes para ese tipo de base';
COMMENT ON COLUMN RHH.ACMN.ACMNDIAS IS 'Dias trabajados en el mes, base de los prorrateos';
COMMENT ON COLUMN RHH.ACMN.ACMNAPRT IS 'Indica si el acumulado proviene de un saldo de apertura de la migracion (S/N)';
COMMENT ON COLUMN RHH.ACMN.ACMNESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.ACMN.ACMNFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.ACMN.ACMNUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.PVNM (ProvisionNomina)
-- DESCRIPCION: Provisiones mensuales de beneficios sociales. Se generan
--              cuando la modalidad del beneficio es ACUMULADO.
-- =====================================================
CREATE TABLE RHH.PVNM (
    PVNMCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PRDNCDGO NUMBER NOT NULL, -- FK a PeriodoNomina
    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado
    CPNMCDGO NUMBER,          -- FK a ConceptoNomina
    PVNMTPPR NUMBER NOT NULL, -- Tipo de provision (rubro RHH_TIPO_PROVISION)

    PVNMBSCL NUMBER(18,2), -- Base de calculo de la provision
    PVNMVLOR NUMBER(18,2) NOT NULL, -- Valor provisionado en el mes

    PVNMESTD NUMBER DEFAULT 1,
    PVNMFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PVNMUSRR VARCHAR2(60),

    CONSTRAINT PK_PVNM PRIMARY KEY (PVNMCDGO),
    CONSTRAINT FK_PVNM_PRDN FOREIGN KEY (PRDNCDGO) REFERENCES RHH.PRDN(PRDNCDGO),
    CONSTRAINT FK_PVNM_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO),
    CONSTRAINT FK_PVNM_CPNM FOREIGN KEY (CPNMCDGO) REFERENCES RHH.CPNM(CPNMCDGO)
);

CREATE INDEX IDX_PVNM_PRDN ON RHH.PVNM(PRDNCDGO);
CREATE INDEX IDX_PVNM_MPLD ON RHH.PVNM(MPLDCDGO);
CREATE INDEX IDX_PVNM_CPNM ON RHH.PVNM(CPNMCDGO);

COMMENT ON TABLE  RHH.PVNM IS 'Provisiones mensuales de beneficios sociales generadas cuando la modalidad del beneficio es acumulada';
COMMENT ON COLUMN RHH.PVNM.PVNMCDGO IS 'Codigo unico de la provision (PK autoincremental)';
COMMENT ON COLUMN RHH.PVNM.PRDNCDGO IS 'FK a RHH.PRDN (periodo de nomina)';
COMMENT ON COLUMN RHH.PVNM.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.PVNM.CPNMCDGO IS 'FK a RHH.CPNM (concepto que origina la provision)';
COMMENT ON COLUMN RHH.PVNM.PVNMTPPR IS 'Tipo de provision: detalle del rubro RHH_TIPO_PROVISION';
COMMENT ON COLUMN RHH.PVNM.PVNMBSCL IS 'Base sobre la que se calculo la provision';
COMMENT ON COLUMN RHH.PVNM.PVNMVLOR IS 'Valor provisionado en el mes';
COMMENT ON COLUMN RHH.PVNM.PVNMESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.PVNM.PVNMFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.PVNM.PVNMUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.PYIR (ProyeccionImpuestoRenta)
-- DESCRIPCION: Proyeccion anual del impuesto a la renta por empleado.
--              Solo una fila vigente por empleado y anio; las anteriores
--              quedan con PYIRVGNT='N' para conservar la trazabilidad.
-- =====================================================
CREATE TABLE RHH.PYIR (
    PYIRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado
    PYIRANOO NUMBER NOT NULL, -- Anio fiscal
    PYIRMSDS NUMBER NOT NULL, -- Mes desde el que rige la proyeccion

    PYIRINRL NUMBER(18,2), -- Ingresos gravados ya realizados
    PYIRINFT NUMBER(18,2), -- Ingresos gravados futuros proyectados
    PYIRINPR NUMBER(18,2), -- Total de ingresos gravados proyectados
    PYIRAPPR NUMBER(18,2), -- Aporte personal IESS proyectado del anio
    PYIRBSIM NUMBER(18,2), -- Base imponible = ingresos proyectados menos aporte personal
    PYIRIMCS NUMBER(18,2), -- Impuesto causado segun la tabla progresiva
    PYIRGSDC NUMBER(18,2), -- Gastos personales declarados
    PYIRTPGS NUMBER(18,2), -- Tope de gastos personales segun cargas
    PYIRRBJA NUMBER(18,2), -- Rebaja aplicada por gastos personales
    PYIRIMPG NUMBER(18,2), -- Impuesto a pagar del anio
    PYIRRTEF NUMBER(18,2), -- Retenciones ya efectuadas en el anio
    PYIRMSRS NUMBER,       -- Meses restantes del anio
    PYIRRTEM NUMBER(18,2), -- Retencion mensual resultante

    PYIRNCRG NUMBER,                  -- Numero de cargas familiares consideradas
    PYIRCTSF VARCHAR2(1) DEFAULT 'N', -- Aplico tope de enfermedad catastrofica (S/N)
    PYIRVGNT VARCHAR2(1) DEFAULT 'S', -- Es la proyeccion vigente (S/N)
    PYIRMTVO VARCHAR2(300),           -- Motivo de la reproyeccion

    PYIRESTD NUMBER DEFAULT 1,
    PYIRFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PYIRUSRR VARCHAR2(60),

    CONSTRAINT PK_PYIR PRIMARY KEY (PYIRCDGO),
    CONSTRAINT FK_PYIR_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO)
);

CREATE INDEX IDX_PYIR_MPLD ON RHH.PYIR(MPLDCDGO);
CREATE INDEX IDX_PYIR_ANIO ON RHH.PYIR(PYIRANOO);

COMMENT ON TABLE  RHH.PYIR IS 'Proyeccion anual del impuesto a la renta bajo relacion de dependencia, con la retencion mensual resultante';
COMMENT ON COLUMN RHH.PYIR.PYIRCDGO IS 'Codigo unico de la proyeccion (PK autoincremental)';
COMMENT ON COLUMN RHH.PYIR.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.PYIR.PYIRANOO IS 'Anio fiscal de la proyeccion';
COMMENT ON COLUMN RHH.PYIR.PYIRMSDS IS 'Mes a partir del cual rige esta proyeccion';
COMMENT ON COLUMN RHH.PYIR.PYIRINRL IS 'Ingresos gravados ya percibidos en el anio al momento de proyectar';
COMMENT ON COLUMN RHH.PYIR.PYIRINFT IS 'Ingresos gravados que se estima percibira en los meses restantes';
COMMENT ON COLUMN RHH.PYIR.PYIRINPR IS 'Total de ingresos gravados proyectados para el anio';
COMMENT ON COLUMN RHH.PYIR.PYIRAPPR IS 'Aporte personal al IESS proyectado para el anio, deducible de la base';
COMMENT ON COLUMN RHH.PYIR.PYIRBSIM IS 'Base imponible resultante de restar el aporte personal a los ingresos proyectados';
COMMENT ON COLUMN RHH.PYIR.PYIRIMCS IS 'Impuesto causado tras aplicar la tabla progresiva del anio';
COMMENT ON COLUMN RHH.PYIR.PYIRGSDC IS 'Gastos personales declarados por el empleado';
COMMENT ON COLUMN RHH.PYIR.PYIRTPGS IS 'Tope de gastos personales aplicable segun el numero de cargas familiares';
COMMENT ON COLUMN RHH.PYIR.PYIRRBJA IS 'Rebaja efectivamente aplicada por gastos personales';
COMMENT ON COLUMN RHH.PYIR.PYIRIMPG IS 'Impuesto a pagar del anio tras la rebaja';
COMMENT ON COLUMN RHH.PYIR.PYIRRTEF IS 'Retenciones ya efectuadas en el anio, incluidas las de saldo de apertura';
COMMENT ON COLUMN RHH.PYIR.PYIRMSRS IS 'Numero de meses restantes sobre los que se prorratea la retencion';
COMMENT ON COLUMN RHH.PYIR.PYIRRTEM IS 'Retencion mensual resultante que se aplica en el rol';
COMMENT ON COLUMN RHH.PYIR.PYIRNCRG IS 'Numero de cargas familiares consideradas para el tope';
COMMENT ON COLUMN RHH.PYIR.PYIRCTSF IS 'Indica si se aplico el tope ampliado por enfermedad catastrofica (S/N)';
COMMENT ON COLUMN RHH.PYIR.PYIRVGNT IS 'Indica si es la proyeccion vigente (S/N); las anteriores quedan en N';
COMMENT ON COLUMN RHH.PYIR.PYIRMTVO IS 'Motivo por el que se genero esta reproyeccion';
COMMENT ON COLUMN RHH.PYIR.PYIRESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.PYIR.PYIRFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.PYIR.PYIRUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.LQBS (LiquidacionBeneficioSocial)
-- DESCRIPCION: Decimos, fondos de reserva y utilidades liquidados por
--              empleado y periodo del beneficio.
-- =====================================================
CREATE TABLE RHH.LQBS (
    LQBSCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado
    LQBSTPBN NUMBER NOT NULL, -- Tipo de beneficio (rubro RHH_TIPO_BENEFICIO_SOCIAL)
    LQBSANOO NUMBER NOT NULL, -- Anio del beneficio

    LQBSFCHI DATE, -- Inicio del periodo del beneficio
    LQBSFCHF DATE, -- Fin del periodo del beneficio

    LQBSBSCL NUMBER(18,2), -- Base acumulada del beneficio
    LQBSDIAS NUMBER(18,4), -- Dias trabajados en el periodo
    LQBSVLRR NUMBER(18,2), -- Valor calculado del beneficio
    LQBSVLMN NUMBER(18,2) DEFAULT 0, -- Valor ya pagado en forma mensualizada
    LQBSVLPG NUMBER(18,2) DEFAULT 0, -- Valor efectivamente pagado

    PRDNCDGO NUMBER, -- FK al periodo de nomina por el que se pago
    LQBSFCPG DATE,   -- Fecha de pago
    LQBSESTD NUMBER DEFAULT 1,
    LQBSFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LQBSUSRR VARCHAR2(60),

    CONSTRAINT PK_LQBS PRIMARY KEY (LQBSCDGO),
    CONSTRAINT UQ_LQBS_BNF UNIQUE (MPLDCDGO, LQBSTPBN, LQBSANOO),
    CONSTRAINT FK_LQBS_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO),
    CONSTRAINT FK_LQBS_PRDN FOREIGN KEY (PRDNCDGO) REFERENCES RHH.PRDN(PRDNCDGO)
);

CREATE INDEX IDX_LQBS_MPLD ON RHH.LQBS(MPLDCDGO);
CREATE INDEX IDX_LQBS_PRDN ON RHH.LQBS(PRDNCDGO);

COMMENT ON TABLE  RHH.LQBS IS 'Liquidacion de beneficios sociales por empleado: decimos, fondos de reserva y utilidades, con su periodo y su pago';
COMMENT ON COLUMN RHH.LQBS.LQBSCDGO IS 'Codigo unico de la liquidacion del beneficio (PK autoincremental)';
COMMENT ON COLUMN RHH.LQBS.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.LQBS.LQBSTPBN IS 'Tipo de beneficio: detalle del rubro RHH_TIPO_BENEFICIO_SOCIAL';
COMMENT ON COLUMN RHH.LQBS.LQBSANOO IS 'Anio al que corresponde el beneficio';
COMMENT ON COLUMN RHH.LQBS.LQBSFCHI IS 'Fecha de inicio del periodo de acumulacion del beneficio';
COMMENT ON COLUMN RHH.LQBS.LQBSFCHF IS 'Fecha de fin del periodo de acumulacion del beneficio';
COMMENT ON COLUMN RHH.LQBS.LQBSBSCL IS 'Base acumulada sobre la que se calculo el beneficio';
COMMENT ON COLUMN RHH.LQBS.LQBSDIAS IS 'Dias trabajados dentro del periodo del beneficio';
COMMENT ON COLUMN RHH.LQBS.LQBSVLRR IS 'Valor calculado del beneficio';
COMMENT ON COLUMN RHH.LQBS.LQBSVLMN IS 'Valor que ya se pago mensualizado durante el periodo';
COMMENT ON COLUMN RHH.LQBS.LQBSVLPG IS 'Valor efectivamente pagado al empleado';
COMMENT ON COLUMN RHH.LQBS.PRDNCDGO IS 'FK a RHH.PRDN (periodo de nomina por el que se canalizo el pago)';
COMMENT ON COLUMN RHH.LQBS.LQBSFCPG IS 'Fecha en que se pago el beneficio';
COMMENT ON COLUMN RHH.LQBS.LQBSESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.LQBS.LQBSFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.LQBS.LQBSUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.DSRC (DescuentoRecurrente)
-- DESCRIPCION: Prestamos IESS (quirografario e hipotecario), anticipos,
--              prestamos internos, retenciones judiciales y seguros.
-- =====================================================
CREATE TABLE RHH.DSRC (
    DSRCCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado
    CPNMCDGO NUMBER NOT NULL, -- FK a ConceptoNomina con el que se descuenta
    DSRCTPDS NUMBER NOT NULL, -- Tipo de descuento (rubro RHH_TIPO_DESCUENTO_RECURRENTE)

    DSRCNMRO VARCHAR2(50),           -- Numero de referencia del prestamo u obligacion
    DSRCVLOR NUMBER(18,2) NOT NULL,  -- Monto original de la obligacion
    DSRCSLDD NUMBER(18,2) NOT NULL,  -- Saldo pendiente
    DSRCNMCT NUMBER,                 -- Numero total de cuotas
    DSRCCTPG NUMBER DEFAULT 0,       -- Numero de cuotas ya descontadas
    DSRCVLCT NUMBER(18,2),           -- Valor de la cuota mensual
    DSRCPRCN NUMBER(18,6),           -- Porcentaje sobre el neto, en retenciones judiciales

    DSRCFCHI DATE NOT NULL, -- Fecha de inicio del descuento
    DSRCFCHF DATE,          -- Fecha estimada de finalizacion
    DSRCBNFC VARCHAR2(200), -- Beneficiario del descuento
    DSRCOBSR VARCHAR2(500),

    DSRCAPRT VARCHAR2(1) DEFAULT 'N', -- Proviene de saldo de apertura (S/N)
    DSRCESTD NUMBER DEFAULT 1,        -- Estado (rubro RHH_ESTADO_DESCUENTO_RECURRENTE)
    DSRCFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DSRCUSRR VARCHAR2(60),

    CONSTRAINT PK_DSRC PRIMARY KEY (DSRCCDGO),
    CONSTRAINT FK_DSRC_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO),
    CONSTRAINT FK_DSRC_CPNM FOREIGN KEY (CPNMCDGO) REFERENCES RHH.CPNM(CPNMCDGO)
);

CREATE INDEX IDX_DSRC_MPLD ON RHH.DSRC(MPLDCDGO);
CREATE INDEX IDX_DSRC_CPNM ON RHH.DSRC(CPNMCDGO);

COMMENT ON TABLE  RHH.DSRC IS 'Descuentos recurrentes del empleado: prestamos IESS, anticipos, prestamos internos, retenciones judiciales y seguros';
COMMENT ON COLUMN RHH.DSRC.DSRCCDGO IS 'Codigo unico del descuento (PK autoincremental)';
COMMENT ON COLUMN RHH.DSRC.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.DSRC.CPNMCDGO IS 'FK a RHH.CPNM (concepto con el que se refleja en el rol)';
COMMENT ON COLUMN RHH.DSRC.DSRCTPDS IS 'Tipo de descuento: detalle del rubro RHH_TIPO_DESCUENTO_RECURRENTE';
COMMENT ON COLUMN RHH.DSRC.DSRCNMRO IS 'Numero de referencia del prestamo u obligacion';
COMMENT ON COLUMN RHH.DSRC.DSRCVLOR IS 'Monto original de la obligacion';
COMMENT ON COLUMN RHH.DSRC.DSRCSLDD IS 'Saldo pendiente por descontar';
COMMENT ON COLUMN RHH.DSRC.DSRCNMCT IS 'Numero total de cuotas pactadas';
COMMENT ON COLUMN RHH.DSRC.DSRCCTPG IS 'Numero de cuotas ya descontadas';
COMMENT ON COLUMN RHH.DSRC.DSRCVLCT IS 'Valor de la cuota mensual a descontar';
COMMENT ON COLUMN RHH.DSRC.DSRCPRCN IS 'Porcentaje sobre el neto, usado en retenciones judiciales y pensiones alimenticias';
COMMENT ON COLUMN RHH.DSRC.DSRCFCHI IS 'Fecha desde la que se aplica el descuento';
COMMENT ON COLUMN RHH.DSRC.DSRCFCHF IS 'Fecha estimada de finalizacion del descuento';
COMMENT ON COLUMN RHH.DSRC.DSRCBNFC IS 'Beneficiario a quien se entrega el valor descontado';
COMMENT ON COLUMN RHH.DSRC.DSRCOBSR IS 'Observaciones del descuento';
COMMENT ON COLUMN RHH.DSRC.DSRCAPRT IS 'Indica si el descuento proviene de un saldo de apertura de la migracion (S/N)';
COMMENT ON COLUMN RHH.DSRC.DSRCESTD IS 'Estado: detalle del rubro RHH_ESTADO_DESCUENTO_RECURRENTE';
COMMENT ON COLUMN RHH.DSRC.DSRCFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.DSRC.DSRCUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.CTDS (CuotaDescuento)
-- DESCRIPCION: Tabla de amortizacion del descuento recurrente. Una fila
--              por cuota, con la marca de en que periodo se descontó.
-- =====================================================
CREATE TABLE RHH.CTDS (
    CTDSCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    DSRCCDGO NUMBER NOT NULL, -- FK a DescuentoRecurrente
    CTDSNMCT NUMBER NOT NULL, -- Numero de cuota
    CTDSFCVN DATE NOT NULL,   -- Fecha de vencimiento de la cuota

    CTDSTTAL NUMBER(18,2) NOT NULL,  -- Valor total de la cuota
    CTDSCPTL NUMBER(18,2),           -- Componente de capital
    CTDSINTR NUMBER(18,2),           -- Componente de interes
    CTDSVLDS NUMBER(18,2) DEFAULT 0, -- Valor efectivamente descontado
    CTDSSLDD NUMBER(18,2),           -- Saldo tras la cuota

    PRDNCDGO NUMBER, -- FK al periodo en que se descontó
    CTDSESTD NUMBER DEFAULT 1, -- 1=PENDIENTE, 2=DESCONTADA, 3=PARCIAL, 4=ANULADA
    CTDSFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CTDSUSRR VARCHAR2(60),

    CONSTRAINT PK_CTDS PRIMARY KEY (CTDSCDGO),
    CONSTRAINT FK_CTDS_DSRC FOREIGN KEY (DSRCCDGO) REFERENCES RHH.DSRC(DSRCCDGO),
    CONSTRAINT FK_CTDS_PRDN FOREIGN KEY (PRDNCDGO) REFERENCES RHH.PRDN(PRDNCDGO)
);

CREATE INDEX IDX_CTDS_DSRC ON RHH.CTDS(DSRCCDGO);
CREATE INDEX IDX_CTDS_PRDN ON RHH.CTDS(PRDNCDGO);

COMMENT ON TABLE  RHH.CTDS IS 'Tabla de amortizacion de un descuento recurrente: una fila por cuota con su vencimiento y el periodo en que se descontó';
COMMENT ON COLUMN RHH.CTDS.CTDSCDGO IS 'Codigo unico de la cuota (PK autoincremental)';
COMMENT ON COLUMN RHH.CTDS.DSRCCDGO IS 'FK a RHH.DSRC (descuento recurrente al que pertenece)';
COMMENT ON COLUMN RHH.CTDS.CTDSNMCT IS 'Numero de la cuota dentro del plan de amortizacion';
COMMENT ON COLUMN RHH.CTDS.CTDSFCVN IS 'Fecha de vencimiento de la cuota; determina en que periodo se descuenta';
COMMENT ON COLUMN RHH.CTDS.CTDSTTAL IS 'Valor total de la cuota';
COMMENT ON COLUMN RHH.CTDS.CTDSCPTL IS 'Componente de capital de la cuota';
COMMENT ON COLUMN RHH.CTDS.CTDSINTR IS 'Componente de interes de la cuota';
COMMENT ON COLUMN RHH.CTDS.CTDSVLDS IS 'Valor efectivamente descontado; puede ser menor al total si hubo recorte por neto negativo';
COMMENT ON COLUMN RHH.CTDS.CTDSSLDD IS 'Saldo de la obligacion despues de aplicar la cuota';
COMMENT ON COLUMN RHH.CTDS.PRDNCDGO IS 'FK a RHH.PRDN (periodo de nomina en que se descontó la cuota)';
COMMENT ON COLUMN RHH.CTDS.CTDSESTD IS 'Estado de la cuota (1=PENDIENTE, 2=DESCONTADA, 3=PARCIAL, 4=ANULADA)';
COMMENT ON COLUMN RHH.CTDS.CTDSFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.CTDS.CTDSUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.HREX (HoraExtra)
-- DESCRIPCION: Horas extra tipificadas por empleado y fecha, con su
--              aprobacion. Suplementarias, extraordinarias y nocturnas.
-- =====================================================
CREATE TABLE RHH.HREX (
    HREXCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado
    RSMNCDGO NUMBER,          -- FK a ResumenNomina que la origino
    PRDNCDGO NUMBER,          -- FK al periodo en que se pago
    HREXTPHR NUMBER NOT NULL, -- Tipo de hora extra (rubro RHH_TIPO_HORA_EXTRA)

    HREXFCHA DATE NOT NULL,          -- Fecha en que se generaron
    HREXHORS NUMBER(18,4) NOT NULL,  -- Numero de horas
    HREXVLHR NUMBER(18,2),           -- Valor de la hora ordinaria
    HREXRCRG NUMBER(18,6),           -- Porcentaje de recargo aplicado
    HREXVLOR NUMBER(18,2),           -- Valor total a pagar

    HREXAPRB VARCHAR2(1) DEFAULT 'N', -- Aprobada para pago (S/N)
    HREXUSAP VARCHAR2(60),
    HREXFCAP DATE,
    HREXEXCP VARCHAR2(1) DEFAULT 'N', -- Excede el tope legal y requiere aprobacion excepcional (S/N)
    HREXOBSR VARCHAR2(300),

    HREXESTD NUMBER DEFAULT 1,
    HREXFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    HREXUSRR VARCHAR2(60),

    CONSTRAINT PK_HREX PRIMARY KEY (HREXCDGO),
    CONSTRAINT FK_HREX_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO),
    CONSTRAINT FK_HREX_RSMN FOREIGN KEY (RSMNCDGO) REFERENCES RHH.RSMN(RSMNCDGO),
    CONSTRAINT FK_HREX_PRDN FOREIGN KEY (PRDNCDGO) REFERENCES RHH.PRDN(PRDNCDGO)
);

CREATE INDEX IDX_HREX_MPLD ON RHH.HREX(MPLDCDGO);
CREATE INDEX IDX_HREX_RSMN ON RHH.HREX(RSMNCDGO);
CREATE INDEX IDX_HREX_PRDN ON RHH.HREX(PRDNCDGO);

COMMENT ON TABLE  RHH.HREX IS 'Horas extra tipificadas por empleado y fecha, con su recargo, su valor y su aprobacion';
COMMENT ON COLUMN RHH.HREX.HREXCDGO IS 'Codigo unico de la hora extra (PK autoincremental)';
COMMENT ON COLUMN RHH.HREX.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.HREX.RSMNCDGO IS 'FK a RHH.RSMN (resumen diario que la origino)';
COMMENT ON COLUMN RHH.HREX.PRDNCDGO IS 'FK a RHH.PRDN (periodo de nomina en que se pago)';
COMMENT ON COLUMN RHH.HREX.HREXTPHR IS 'Tipo de hora extra: detalle del rubro RHH_TIPO_HORA_EXTRA';
COMMENT ON COLUMN RHH.HREX.HREXFCHA IS 'Fecha en que se generaron las horas extra';
COMMENT ON COLUMN RHH.HREX.HREXHORS IS 'Numero de horas extra generadas';
COMMENT ON COLUMN RHH.HREX.HREXVLHR IS 'Valor de la hora ordinaria del empleado al momento del calculo';
COMMENT ON COLUMN RHH.HREX.HREXRCRG IS 'Porcentaje de recargo aplicado segun el tipo de hora';
COMMENT ON COLUMN RHH.HREX.HREXVLOR IS 'Valor total a pagar por las horas extra';
COMMENT ON COLUMN RHH.HREX.HREXAPRB IS 'Indica si estan aprobadas para pago (S/N); solo las aprobadas entran al rol';
COMMENT ON COLUMN RHH.HREX.HREXUSAP IS 'Usuario que aprobo las horas extra';
COMMENT ON COLUMN RHH.HREX.HREXFCAP IS 'Fecha de aprobacion';
COMMENT ON COLUMN RHH.HREX.HREXEXCP IS 'Indica si exceden el tope legal diario o semanal y requieren aprobacion excepcional (S/N)';
COMMENT ON COLUMN RHH.HREX.HREXOBSR IS 'Observaciones sobre las horas extra';
COMMENT ON COLUMN RHH.HREX.HREXESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.HREX.HREXFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.HREX.HREXUSRR IS 'Usuario que registro';
