-- =====================================================
-- MODULO: RHH (Recursos Humanos) - ASISTENCIA, PAGO Y SALIDAS
-- DESCRIPCION: Carga de marcaciones del biometrico, orden de pago,
--              utilidades y saldos de apertura de la migracion.
-- ORDEN DE EJECUCION: 4 de 9
-- FECHA: 2026-08-19
-- =====================================================


-- =====================================================
-- TABLA: RHH.CRMR (CargaMarcaciones)
-- DESCRIPCION: Cabecera del lote de marcaciones importado del biometrico.
--              El hash SHA-256 impide cargar dos veces el mismo archivo.
-- =====================================================
CREATE TABLE RHH.CRMR (
    CRMRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL, -- FK a Empresa
    FMRCCDGO NUMBER NOT NULL, -- FK a FormatoArchivoMarcacion

    CRMRNMAR VARCHAR2(300) NOT NULL, -- Nombre del archivo cargado
    CRMRHASH VARCHAR2(64) NOT NULL,  -- Hash SHA-256 del archivo
    CRMRFCCR DATE,                   -- Fecha de la carga
    CRMRFCDS DATE,                   -- Fecha desde de las marcaciones del archivo
    CRMRFCHS DATE,                   -- Fecha hasta de las marcaciones del archivo

    CRMRLNTT NUMBER DEFAULT 0, -- Lineas totales del archivo
    CRMRLNOK NUMBER DEFAULT 0, -- Lineas procesadas correctamente
    CRMRLNER NUMBER DEFAULT 0, -- Lineas con error
    CRMRLNDP NUMBER DEFAULT 0, -- Lineas duplicadas descartadas
    CRMRLGGO CLOB,             -- Log del procesamiento

    CRMRESTD NUMBER DEFAULT 1, -- Estado (rubro RHH_ESTADO_CARGA_MARCACIONES)
    CRMRFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CRMRUSRR VARCHAR2(60),

    CONSTRAINT PK_CRMR PRIMARY KEY (CRMRCDGO),
    CONSTRAINT UQ_CRMR_HASH UNIQUE (PJRQCDGO, CRMRHASH),
    CONSTRAINT FK_CRMR_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_CRMR_FMRC FOREIGN KEY (FMRCCDGO) REFERENCES RHH.FMRC(FMRCCDGO)
);

CREATE INDEX IDX_CRMR_PJRQ ON RHH.CRMR(PJRQCDGO);
CREATE INDEX IDX_CRMR_FMRC ON RHH.CRMR(FMRCCDGO);

COMMENT ON TABLE  RHH.CRMR IS 'Cabecera del lote de marcaciones importado del reloj biometrico, con control antiduplicado por hash del archivo';
COMMENT ON COLUMN RHH.CRMR.CRMRCDGO IS 'Codigo unico de la carga (PK autoincremental)';
COMMENT ON COLUMN RHH.CRMR.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.CRMR.FMRCCDGO IS 'FK a RHH.FMRC (formato con el que se interpreto el archivo)';
COMMENT ON COLUMN RHH.CRMR.CRMRNMAR IS 'Nombre del archivo cargado';
COMMENT ON COLUMN RHH.CRMR.CRMRHASH IS 'Hash SHA-256 del contenido del archivo; impide cargar dos veces el mismo';
COMMENT ON COLUMN RHH.CRMR.CRMRFCCR IS 'Fecha en que se realizo la carga';
COMMENT ON COLUMN RHH.CRMR.CRMRFCDS IS 'Fecha de la marcacion mas antigua del archivo';
COMMENT ON COLUMN RHH.CRMR.CRMRFCHS IS 'Fecha de la marcacion mas reciente del archivo';
COMMENT ON COLUMN RHH.CRMR.CRMRLNTT IS 'Numero total de lineas del archivo';
COMMENT ON COLUMN RHH.CRMR.CRMRLNOK IS 'Numero de lineas procesadas correctamente';
COMMENT ON COLUMN RHH.CRMR.CRMRLNER IS 'Numero de lineas rechazadas por error';
COMMENT ON COLUMN RHH.CRMR.CRMRLNDP IS 'Numero de lineas descartadas por duplicidad';
COMMENT ON COLUMN RHH.CRMR.CRMRLGGO IS 'Log detallado del procesamiento del archivo';
COMMENT ON COLUMN RHH.CRMR.CRMRESTD IS 'Estado de la carga: detalle del rubro RHH_ESTADO_CARGA_MARCACIONES';
COMMENT ON COLUMN RHH.CRMR.CRMRFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.CRMR.CRMRUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.RDPG (OrdenPagoNomina)
-- DESCRIPCION: Orden de pago del neto del periodo. Enlaza con el egreso
--              de tesoreria para que la conciliacion bancaria lo case.
-- =====================================================
CREATE TABLE RHH.RDPG (
    RDPGCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL, -- FK a Empresa
    PRDNCDGO NUMBER NOT NULL, -- FK a PeriodoNomina
    CTBNCDGO NUMBER,          -- FK a CuentaBancaria de la que sale el pago

    RDPGNMRO VARCHAR2(50),           -- Numero de la orden
    RDPGFCEM DATE,                   -- Fecha de emision
    RDPGFCAC DATE,                   -- Fecha de acreditacion confirmada
    RDPGTTAL NUMBER(18,2) DEFAULT 0, -- Total a acreditar
    RDPGNMEM NUMBER DEFAULT 0,       -- Numero de empleados incluidos
    RDPGRTAR VARCHAR2(500),          -- Ruta del archivo bancario generado

    ASNTCDGO NUMBER, -- FK al asiento contable de pago
    EGRSCDGO NUMBER, -- FK al egreso de tesoreria

    RDPGESTD NUMBER DEFAULT 1, -- Estado (rubro RHH_ESTADO_ORDEN_PAGO)
    RDPGOBSR VARCHAR2(500),
    RDPGFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RDPGUSRR VARCHAR2(60),

    CONSTRAINT PK_RDPG PRIMARY KEY (RDPGCDGO),
    CONSTRAINT FK_RDPG_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_RDPG_PRDN FOREIGN KEY (PRDNCDGO) REFERENCES RHH.PRDN(PRDNCDGO)
);

CREATE INDEX IDX_RDPG_PJRQ ON RHH.RDPG(PJRQCDGO);
CREATE INDEX IDX_RDPG_PRDN ON RHH.RDPG(PRDNCDGO);

COMMENT ON TABLE  RHH.RDPG IS 'Orden de pago del neto de un periodo de nomina, enlazada al asiento contable y al egreso de tesoreria';
COMMENT ON COLUMN RHH.RDPG.RDPGCDGO IS 'Codigo unico de la orden de pago (PK autoincremental)';
COMMENT ON COLUMN RHH.RDPG.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.RDPG.PRDNCDGO IS 'FK a RHH.PRDN (periodo de nomina que se paga)';
COMMENT ON COLUMN RHH.RDPG.CTBNCDGO IS 'FK a la cuenta bancaria de la empresa desde la que sale el pago';
COMMENT ON COLUMN RHH.RDPG.RDPGNMRO IS 'Numero de la orden de pago';
COMMENT ON COLUMN RHH.RDPG.RDPGFCEM IS 'Fecha de emision de la orden';
COMMENT ON COLUMN RHH.RDPG.RDPGFCAC IS 'Fecha en que el banco confirmo la acreditacion';
COMMENT ON COLUMN RHH.RDPG.RDPGTTAL IS 'Valor total a acreditar en la orden';
COMMENT ON COLUMN RHH.RDPG.RDPGNMEM IS 'Numero de empleados incluidos en la orden';
COMMENT ON COLUMN RHH.RDPG.RDPGRTAR IS 'Ruta del archivo de transferencias generado para el banco';
COMMENT ON COLUMN RHH.RDPG.ASNTCDGO IS 'FK al asiento contable de pago generado (CNT.ASNT)';
COMMENT ON COLUMN RHH.RDPG.EGRSCDGO IS 'FK al egreso de tesoreria generado (TSR.EGRS)';
COMMENT ON COLUMN RHH.RDPG.RDPGESTD IS 'Estado de la orden: detalle del rubro RHH_ESTADO_ORDEN_PAGO';
COMMENT ON COLUMN RHH.RDPG.RDPGOBSR IS 'Observaciones de la orden de pago';
COMMENT ON COLUMN RHH.RDPG.RDPGFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.RDPG.RDPGUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.DRPG (DetalleOrdenPago)
-- DESCRIPCION: Detalle por empleado y cuenta de la orden de pago.
-- =====================================================
CREATE TABLE RHH.DRPG (
    DRPGCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    RDPGCDGO NUMBER NOT NULL, -- FK a OrdenPagoNomina
    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado
    NMNACDGO NUMBER,          -- FK a Nomina
    CBEMCDGO NUMBER,          -- FK a CuentaBancariaEmpleado

    DRPGVLOR NUMBER(18,2) NOT NULL, -- Valor a acreditar
    DRPGNMCT VARCHAR2(30),          -- Numero de cuenta destino (snapshot)
    DRPGTPCT NUMBER,                -- Tipo de cuenta destino (snapshot)
    DRPGBNCO VARCHAR2(100),         -- Banco destino (snapshot)
    DRPGIDNT VARCHAR2(20),          -- Identificacion del beneficiario (snapshot)
    DRPGNMBN VARCHAR2(200),         -- Nombre del beneficiario (snapshot)

    DRPGRCHZ VARCHAR2(1) DEFAULT 'N', -- Fue rechazado por el banco (S/N)
    DRPGMTRC VARCHAR2(300),           -- Motivo del rechazo

    DRPGESTD NUMBER DEFAULT 1,
    DRPGFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DRPGUSRR VARCHAR2(60),

    CONSTRAINT PK_DRPG PRIMARY KEY (DRPGCDGO),
    CONSTRAINT FK_DRPG_RDPG FOREIGN KEY (RDPGCDGO) REFERENCES RHH.RDPG(RDPGCDGO),
    CONSTRAINT FK_DRPG_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO),
    CONSTRAINT FK_DRPG_NMNA FOREIGN KEY (NMNACDGO) REFERENCES RHH.NMNA(NMNACDGO),
    CONSTRAINT FK_DRPG_CBEM FOREIGN KEY (CBEMCDGO) REFERENCES RHH.CBEM(CBEMCDGO)
);

CREATE INDEX IDX_DRPG_RDPG ON RHH.DRPG(RDPGCDGO);
CREATE INDEX IDX_DRPG_MPLD ON RHH.DRPG(MPLDCDGO);
CREATE INDEX IDX_DRPG_NMNA ON RHH.DRPG(NMNACDGO);
CREATE INDEX IDX_DRPG_CBEM ON RHH.DRPG(CBEMCDGO);

COMMENT ON TABLE  RHH.DRPG IS 'Detalle por empleado de la orden de pago de nomina, con snapshot de los datos bancarios al momento de emitir';
COMMENT ON COLUMN RHH.DRPG.DRPGCDGO IS 'Codigo unico del detalle (PK autoincremental)';
COMMENT ON COLUMN RHH.DRPG.RDPGCDGO IS 'FK a RHH.RDPG (orden de pago)';
COMMENT ON COLUMN RHH.DRPG.MPLDCDGO IS 'FK a RHH.MPLD (empleado beneficiario)';
COMMENT ON COLUMN RHH.DRPG.NMNACDGO IS 'FK a RHH.NMNA (nomina de la que sale el neto)';
COMMENT ON COLUMN RHH.DRPG.CBEMCDGO IS 'FK a RHH.CBEM (cuenta bancaria de destino)';
COMMENT ON COLUMN RHH.DRPG.DRPGVLOR IS 'Valor a acreditar al empleado en esta linea';
COMMENT ON COLUMN RHH.DRPG.DRPGNMCT IS 'Numero de cuenta destino congelado al momento de emitir la orden';
COMMENT ON COLUMN RHH.DRPG.DRPGTPCT IS 'Tipo de cuenta destino congelado al momento de emitir la orden';
COMMENT ON COLUMN RHH.DRPG.DRPGBNCO IS 'Nombre del banco destino congelado al momento de emitir la orden';
COMMENT ON COLUMN RHH.DRPG.DRPGIDNT IS 'Identificacion del beneficiario congelada al momento de emitir la orden';
COMMENT ON COLUMN RHH.DRPG.DRPGNMBN IS 'Nombre del beneficiario congelado al momento de emitir la orden';
COMMENT ON COLUMN RHH.DRPG.DRPGRCHZ IS 'Indica si el banco rechazo la acreditacion (S/N)';
COMMENT ON COLUMN RHH.DRPG.DRPGMTRC IS 'Motivo informado por el banco para el rechazo';
COMMENT ON COLUMN RHH.DRPG.DRPGESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.DRPG.DRPGFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.DRPG.DRPGUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.UTLD (Utilidad)
-- DESCRIPCION: Calculo del reparto del 15% por ejercicio.
--              ASOPREP-FCPC no reparte utilidades (CFNM.CFNMAPUT='N'),
--              pero la funcionalidad existe para otras empresas.
-- =====================================================
CREATE TABLE RHH.UTLD (
    UTLDCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL, -- FK a Empresa
    UTLDANOO NUMBER NOT NULL, -- Ejercicio fiscal

    UTLDUTCN NUMBER(18,2) NOT NULL, -- Utilidad contable del ejercicio
    UTLDBS15 NUMBER(18,2),          -- Base total a repartir
    UTLDBS10 NUMBER(18,2),          -- Porcion que se reparte por dias trabajados
    UTLDBS05 NUMBER(18,2),          -- Porcion que se reparte por cargas familiares
    UTLDTTDI NUMBER(18,4),          -- Total de dias trabajados de la empresa
    UTLDTTCG NUMBER,                -- Total de cargas familiares de la empresa
    UTLDVLDI NUMBER(18,6),          -- Valor por dia trabajado
    UTLDVLCG NUMBER(18,6),          -- Valor por carga familiar
    UTLDTPSB NUMBER(18,2),          -- Tope por trabajador en dolares
    UTLDEXCD NUMBER(18,2) DEFAULT 0,-- Excedente total transferido al IESS

    UTLDFCPG DATE,             -- Fecha de pago
    PRDNCDGO NUMBER,           -- FK al periodo por el que se pago
    UTLDESTD NUMBER DEFAULT 1,
    UTLDFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UTLDUSRR VARCHAR2(60),

    CONSTRAINT PK_UTLD PRIMARY KEY (UTLDCDGO),
    CONSTRAINT UQ_UTLD_ANIO UNIQUE (PJRQCDGO, UTLDANOO),
    CONSTRAINT FK_UTLD_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_UTLD_PRDN FOREIGN KEY (PRDNCDGO) REFERENCES RHH.PRDN(PRDNCDGO)
);

CREATE INDEX IDX_UTLD_PJRQ ON RHH.UTLD(PJRQCDGO);
CREATE INDEX IDX_UTLD_PRDN ON RHH.UTLD(PRDNCDGO);

COMMENT ON TABLE  RHH.UTLD IS 'Calculo del reparto de utilidades del ejercicio. La funcionalidad existe para todas las empresas aunque ASOPREP-FCPC no las reparta';
COMMENT ON COLUMN RHH.UTLD.UTLDCDGO IS 'Codigo unico del calculo (PK autoincremental)';
COMMENT ON COLUMN RHH.UTLD.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.UTLD.UTLDANOO IS 'Ejercicio fiscal del reparto';
COMMENT ON COLUMN RHH.UTLD.UTLDUTCN IS 'Utilidad contable del ejercicio informada por contabilidad';
COMMENT ON COLUMN RHH.UTLD.UTLDBS15 IS 'Base total a repartir segun el porcentaje parametrizado';
COMMENT ON COLUMN RHH.UTLD.UTLDBS10 IS 'Porcion de la base que se reparte en funcion de dias trabajados';
COMMENT ON COLUMN RHH.UTLD.UTLDBS05 IS 'Porcion de la base que se reparte en funcion de cargas familiares';
COMMENT ON COLUMN RHH.UTLD.UTLDTTDI IS 'Suma de dias trabajados de todos los empleados del ejercicio';
COMMENT ON COLUMN RHH.UTLD.UTLDTTCG IS 'Suma de cargas familiares de todos los empleados del ejercicio';
COMMENT ON COLUMN RHH.UTLD.UTLDVLDI IS 'Valor unitario por dia trabajado';
COMMENT ON COLUMN RHH.UTLD.UTLDVLCG IS 'Valor unitario por carga familiar';
COMMENT ON COLUMN RHH.UTLD.UTLDTPSB IS 'Tope por trabajador expresado en dolares, resultante del numero de SBU parametrizado';
COMMENT ON COLUMN RHH.UTLD.UTLDEXCD IS 'Excedente total sobre el tope que se transfiere al IESS';
COMMENT ON COLUMN RHH.UTLD.UTLDFCPG IS 'Fecha de pago de las utilidades';
COMMENT ON COLUMN RHH.UTLD.PRDNCDGO IS 'FK a RHH.PRDN (periodo por el que se canalizo el pago)';
COMMENT ON COLUMN RHH.UTLD.UTLDESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.UTLD.UTLDFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.UTLD.UTLDUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.DTUT (DetalleUtilidad)
-- DESCRIPCION: Distribucion de utilidades por empleado.
-- =====================================================
CREATE TABLE RHH.DTUT (
    DTUTCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    UTLDCDGO NUMBER NOT NULL, -- FK a Utilidad
    MPLDCDGO NUMBER NOT NULL, -- FK a Empleado

    DTUTDIAS NUMBER(18,4),           -- Dias trabajados del empleado en el ejercicio
    DTUTNCRG NUMBER DEFAULT 0,       -- Numero de cargas familiares
    DTUTVL10 NUMBER(18,2),           -- Valor por dias trabajados
    DTUTVL05 NUMBER(18,2),           -- Valor por cargas familiares
    DTUTTTAL NUMBER(18,2),           -- Total antes del tope
    DTUTEXCD NUMBER(18,2) DEFAULT 0, -- Excedente sobre el tope, transferido al IESS
    DTUTVLPG NUMBER(18,2),           -- Valor a pagar tras aplicar el tope
    DTUTRTIR NUMBER(18,2) DEFAULT 0, -- Retencion de impuesto a la renta sobre las utilidades

    DTUTESTD NUMBER DEFAULT 1,
    DTUTFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DTUTUSRR VARCHAR2(60),

    CONSTRAINT PK_DTUT PRIMARY KEY (DTUTCDGO),
    CONSTRAINT FK_DTUT_UTLD FOREIGN KEY (UTLDCDGO) REFERENCES RHH.UTLD(UTLDCDGO),
    CONSTRAINT FK_DTUT_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO)
);

CREATE INDEX IDX_DTUT_UTLD ON RHH.DTUT(UTLDCDGO);
CREATE INDEX IDX_DTUT_MPLD ON RHH.DTUT(MPLDCDGO);

COMMENT ON TABLE  RHH.DTUT IS 'Distribucion de utilidades por empleado, con el excedente sobre el tope que se transfiere al IESS';
COMMENT ON COLUMN RHH.DTUT.DTUTCDGO IS 'Codigo unico del detalle (PK autoincremental)';
COMMENT ON COLUMN RHH.DTUT.UTLDCDGO IS 'FK a RHH.UTLD (calculo de utilidades del ejercicio)';
COMMENT ON COLUMN RHH.DTUT.MPLDCDGO IS 'FK a RHH.MPLD (empleado)';
COMMENT ON COLUMN RHH.DTUT.DTUTDIAS IS 'Dias trabajados por el empleado en el ejercicio';
COMMENT ON COLUMN RHH.DTUT.DTUTNCRG IS 'Numero de cargas familiares del empleado que califican';
COMMENT ON COLUMN RHH.DTUT.DTUTVL10 IS 'Valor que le corresponde por dias trabajados';
COMMENT ON COLUMN RHH.DTUT.DTUTVL05 IS 'Valor que le corresponde por cargas familiares';
COMMENT ON COLUMN RHH.DTUT.DTUTTTAL IS 'Total que le corresponde antes de aplicar el tope';
COMMENT ON COLUMN RHH.DTUT.DTUTEXCD IS 'Excedente sobre el tope que se transfiere al IESS';
COMMENT ON COLUMN RHH.DTUT.DTUTVLPG IS 'Valor a pagar al empleado tras aplicar el tope';
COMMENT ON COLUMN RHH.DTUT.DTUTRTIR IS 'Retencion de impuesto a la renta aplicada sobre las utilidades';
COMMENT ON COLUMN RHH.DTUT.DTUTESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.DTUT.DTUTFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.DTUT.DTUTUSRR IS 'Usuario que registro';


-- =====================================================
-- TABLA: RHH.SLAP (SaldoApertura)
-- DESCRIPCION: Saldos de migracion al corte. Se cargan, se validan y se
--              aplican en un paso separado, con reversion trazable.
--              Para ASOPREP el corte es el 31-12-2025.
-- =====================================================
CREATE TABLE RHH.SLAP (
    SLAPCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL,  -- FK a Empresa
    MPLDCDGO NUMBER,           -- FK a Empleado; NULL si aun no se ha podido enlazar
    SLAPIDNT VARCHAR2(20),     -- Identificacion del empleado en el archivo origen
    SLAPFCCR DATE NOT NULL,    -- Fecha de corte de la migracion
    SLAPTPSL NUMBER NOT NULL,  -- Tipo de saldo (rubro RHH_TIPO_SALDO_APERTURA)

    SLAPVLOR NUMBER(18,2) DEFAULT 0, -- Valor del saldo
    SLAPDIAS NUMBER(18,4),           -- Dias, cuando el saldo es de vacaciones o antiguedad
    SLAPFCHA DATE,                   -- Fecha, cuando el saldo es de antiguedad
    SLAPANOO NUMBER,                 -- Anio al que corresponde el saldo
    SLAPNMCT NUMBER,                 -- Numero de cuotas pendientes, en prestamos
    SLAPOBSR VARCHAR2(500),

    SLAPAPLC VARCHAR2(1) DEFAULT 'N', -- Ya fue aplicado (S/N)
    SLAPFCAP DATE,                    -- Fecha de aplicacion
    SLAPRFTB VARCHAR2(30),            -- Tabla destino en la que se materializo
    SLAPRFID NUMBER,                  -- Id del registro creado en la tabla destino

    SLAPESTD NUMBER DEFAULT 1,
    SLAPFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SLAPUSRR VARCHAR2(60),

    CONSTRAINT PK_SLAP PRIMARY KEY (SLAPCDGO),
    CONSTRAINT FK_SLAP_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_SLAP_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO)
);

CREATE INDEX IDX_SLAP_PJRQ ON RHH.SLAP(PJRQCDGO);
CREATE INDEX IDX_SLAP_MPLD ON RHH.SLAP(MPLDCDGO);

COMMENT ON TABLE  RHH.SLAP IS 'Saldos de apertura de la migracion: antiguedad, vacaciones, acumulados de decimos, fondos de reserva y prestamos en curso, con reversion trazable';
COMMENT ON COLUMN RHH.SLAP.SLAPCDGO IS 'Codigo unico del saldo (PK autoincremental)';
COMMENT ON COLUMN RHH.SLAP.PJRQCDGO IS 'FK a Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.SLAP.MPLDCDGO IS 'FK a RHH.MPLD (empleado); queda NULL mientras no se resuelva el enlace por identificacion';
COMMENT ON COLUMN RHH.SLAP.SLAPIDNT IS 'Identificacion del empleado tal como viene en el archivo de migracion';
COMMENT ON COLUMN RHH.SLAP.SLAPFCCR IS 'Fecha de corte de la migracion';
COMMENT ON COLUMN RHH.SLAP.SLAPTPSL IS 'Tipo de saldo: detalle del rubro RHH_TIPO_SALDO_APERTURA';
COMMENT ON COLUMN RHH.SLAP.SLAPVLOR IS 'Valor monetario del saldo de apertura';
COMMENT ON COLUMN RHH.SLAP.SLAPDIAS IS 'Numero de dias, cuando el saldo es de vacaciones pendientes o antiguedad';
COMMENT ON COLUMN RHH.SLAP.SLAPFCHA IS 'Fecha asociada al saldo, por ejemplo la fecha de ingreso para la antiguedad';
COMMENT ON COLUMN RHH.SLAP.SLAPANOO IS 'Anio al que corresponde el saldo acumulado';
COMMENT ON COLUMN RHH.SLAP.SLAPNMCT IS 'Numero de cuotas pendientes, cuando el saldo es un prestamo en curso';
COMMENT ON COLUMN RHH.SLAP.SLAPOBSR IS 'Observaciones del saldo de apertura';
COMMENT ON COLUMN RHH.SLAP.SLAPAPLC IS 'Indica si el saldo ya fue materializado en las tablas operativas (S/N)';
COMMENT ON COLUMN RHH.SLAP.SLAPFCAP IS 'Fecha en que el saldo fue aplicado';
COMMENT ON COLUMN RHH.SLAP.SLAPRFTB IS 'Nombre de la tabla en la que se materializo el saldo, para poder revertirlo';
COMMENT ON COLUMN RHH.SLAP.SLAPRFID IS 'Identificador del registro creado en la tabla destino, para poder revertirlo';
COMMENT ON COLUMN RHH.SLAP.SLAPESTD IS 'Estado del registro (1=ACTIVO)';
COMMENT ON COLUMN RHH.SLAP.SLAPFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.SLAP.SLAPUSRR IS 'Usuario que registro';
