-- =====================================================
-- MODULO: RHH - RUBROS Y DETALLES DE RUBRO
-- DESCRIPCION: Alta de los 44 rubros del modulo (codigoAlterno 179 a 222)
--              en SCP.PRBR y SCP.PDTR, mas el detalle RECURSOS HUMANOS
--              del rubro ModuloSistema (15).
-- ORDEN DE EJECUCION: 6 de 9
-- FECHA: 2026-08-19
-- =====================================================
-- IDS EXPLICITOS, SIN SECUENCIAS
--   Sigue el estilo de docs/logica-negocio/cxp/sql/05-insert-rubros-proceso-carga.sql
--   PRBRCDGO: 180 a 223    (relacion PRBRCDGO = PRBRALTR + 1)
--   PDTRCDGO: 761 a 1049   (289 detalles correlativos)
--   Valores confirmados por el cliente el 2026-08-19.
--
--   NO usar SCP.SQ_PRBRCDGO ni SCP.SQ_PDTRCDGO en este script. Si en la
--   instalacion esas secuencias estan por debajo de estos valores, hay que
--   adelantarlas despues de la carga para que JPA no genere PK repetidas:
--     SELECT SCP.SQ_PRBRCDGO.NEXTVAL FROM DUAL;  -- repetir hasta superar 223
--     SELECT SCP.SQ_PDTRCDGO.NEXTVAL FROM DUAL;  -- repetir hasta superar 1049
--   O bien, mas limpio:
--     ALTER SEQUENCE SCP.SQ_PRBRCDGO RESTART START WITH 224;
--     ALTER SEQUENCE SCP.SQ_PDTRCDGO RESTART START WITH 1050;
--
--   El codigo Java NUNCA referencia estas PK: identifica todo por el par
--   (PRBRALTR del rubro, PDTRALTR del detalle).
--
--   PRBRTPOO se fija en 1. VERIFICAR contra los rubros existentes antes de
--   ejecutar en produccion, por si esa columna clasifica los rubros de
--   alguna forma en la instalacion del cliente.
-- =====================================================


-- =====================================================
-- DETALLE NUEVO DEL RUBRO ModuloSistema (15)
-- Necesario para etiquetar los asientos contables del modulo.
-- =====================================================
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT 761, (SELECT PRBRCDGO FROM SCP.PRBR WHERE PRBRALTR = 15), 'RECURSOS HUMANOS', 5, 1
FROM DUAL;


-- =====================================================
-- 179 / PRBRCDGO 180 - RHH_TIPO_CONCEPTO_NOMINA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (180, 'RHH TIPO DE CONCEPTO DE NOMINA', SYSDATE, 179, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 180, d.DSCR, d.ALTR, 1 FROM (
    SELECT 762 AS CDGO, 'INGRESO'          AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 763, 'EGRESO',          2 FROM DUAL UNION ALL
    SELECT 764, 'APORTE PATRONAL', 3 FROM DUAL UNION ALL
    SELECT 765, 'PROVISION',       4 FROM DUAL UNION ALL
    SELECT 766, 'INFORMATIVO',     5 FROM DUAL
) d;


-- =====================================================
-- 180 / PRBRCDGO 181 - RHH_TIPO_CALCULO_CONCEPTO
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (181, 'RHH TIPO DE CALCULO DEL CONCEPTO', SYSDATE, 180, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 181, d.DSCR, d.ALTR, 1 FROM (
    SELECT 767 AS CDGO, 'VALOR FIJO'             AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 768, 'PORCENTAJE SOBRE BASE', 2 FROM DUAL UNION ALL
    SELECT 769, 'POR CANTIDAD',          3 FROM DUAL UNION ALL
    SELECT 770, 'FORMULA',               4 FROM DUAL UNION ALL
    SELECT 771, 'TABLA PROGRESIVA',      5 FROM DUAL UNION ALL
    SELECT 772, 'DESDE ACUMULADO',       6 FROM DUAL UNION ALL
    SELECT 773, 'MANUAL',                7 FROM DUAL
) d;


-- =====================================================
-- 181 / PRBRCDGO 182 - RHH_BASE_CALCULO
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (182, 'RHH BASE DE CALCULO', SYSDATE, 181, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 182, d.DSCR, d.ALTR, 1 FROM (
    SELECT 774 AS CDGO, 'SUELDO DEL CONTRATO' AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 775, 'IMPONIBLE IESS',     2 FROM DUAL UNION ALL
    SELECT 776, 'GRAVADO IR',         3 FROM DUAL UNION ALL
    SELECT 777, 'SBU',                4 FROM DUAL UNION ALL
    SELECT 778, 'VALOR HORA',         5 FROM DUAL UNION ALL
    SELECT 779, 'TOTAL INGRESOS',     6 FROM DUAL UNION ALL
    SELECT 780, 'NETO',               7 FROM DUAL
) d;


-- =====================================================
-- 182 / PRBRCDGO 183 - RHH_ESTADO_PERIODO_NOMINA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (183, 'RHH ESTADO DEL PERIODO DE NOMINA', SYSDATE, 182, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 183, d.DSCR, d.ALTR, 1 FROM (
    SELECT 781 AS CDGO, 'ABIERTO'       AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 782, 'EN CALCULO',    2 FROM DUAL UNION ALL
    SELECT 783, 'CALCULADO',     3 FROM DUAL UNION ALL
    SELECT 784, 'APROBADO',      4 FROM DUAL UNION ALL
    SELECT 785, 'CONTABILIZADO', 5 FROM DUAL UNION ALL
    SELECT 786, 'PAGADO',        6 FROM DUAL UNION ALL
    SELECT 787, 'CERRADO',       7 FROM DUAL UNION ALL
    SELECT 788, 'ANULADO',       8 FROM DUAL
) d;


-- =====================================================
-- 183 / PRBRCDGO 184 - RHH_ESTADO_NOMINA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (184, 'RHH ESTADO DE LA NOMINA', SYSDATE, 183, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 184, d.DSCR, d.ALTR, 1 FROM (
    SELECT 789 AS CDGO, 'BORRADOR'  AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 790, 'CALCULADA', 2 FROM DUAL UNION ALL
    SELECT 791, 'APROBADA',  3 FROM DUAL UNION ALL
    SELECT 792, 'PAGADA',    4 FROM DUAL UNION ALL
    SELECT 793, 'ANULADA',   5 FROM DUAL UNION ALL
    SELECT 794, 'EXCLUIDA',  6 FROM DUAL
) d;


-- =====================================================
-- 184 / PRBRCDGO 185 - RHH_MODO_PERIODO_NOMINA  <<< EL INTERRUPTOR >>>
-- Define si el periodo genera asientos contables o no.
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (185, 'RHH MODO DEL PERIODO DE NOMINA', SYSDATE, 184, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 185, d.DSCR, d.ALTR, 1 FROM (
    SELECT 795 AS CDGO, 'HISTORICO SIN CONTABILIZAR' AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 796, 'PRODUCTIVO CONTABILIZA',    2 FROM DUAL
) d;


-- =====================================================
-- 185 / PRBRCDGO 186 - RHH_ESTADO_EMPLEADO
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (186, 'RHH ESTADO DEL EMPLEADO', SYSDATE, 185, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 186, d.DSCR, d.ALTR, 1 FROM (
    SELECT 797 AS CDGO, 'ACTIVO'       AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 798, 'CON LICENCIA', 2 FROM DUAL UNION ALL
    SELECT 799, 'SUSPENDIDO',   3 FROM DUAL UNION ALL
    SELECT 800, 'CESANTE',      4 FROM DUAL UNION ALL
    SELECT 801, 'JUBILADO',     5 FROM DUAL
) d;


-- =====================================================
-- 186 / PRBRCDGO 187 - RHH_TIPO_RELACION_LABORAL
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (187, 'RHH TIPO DE RELACION LABORAL', SYSDATE, 186, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 187, d.DSCR, d.ALTR, 1 FROM (
    SELECT 802 AS CDGO, 'INDEFINIDO TIEMPO COMPLETO' AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 803, 'OCASIONAL EVENTUAL',           2 FROM DUAL UNION ALL
    SELECT 804, 'PLAZO FIJO',                   3 FROM DUAL UNION ALL
    SELECT 805, 'JORNADA PARCIAL PERMANENTE',   4 FROM DUAL UNION ALL
    SELECT 806, 'POR HORAS',                    5 FROM DUAL UNION ALL
    SELECT 807, 'SERVICIOS PROFESIONALES SIN DEPENDENCIA', 6 FROM DUAL UNION ALL
    SELECT 808, 'APRENDIZAJE O PASANTIA',       7 FROM DUAL
) d;


-- =====================================================
-- 187 / PRBRCDGO 188 - RHH_REGION_DECIMO_CUARTO
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (188, 'RHH REGION PARA DECIMO CUARTO', SYSDATE, 187, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 188, d.DSCR, d.ALTR, 1 FROM (
    SELECT 809 AS CDGO, 'SIERRA Y AMAZONIA' AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 810, 'COSTA E INSULAR',   2 FROM DUAL
) d;


-- =====================================================
-- 188 / PRBRCDGO 189 - RHH_MODALIDAD_DECIMO_TERCERO
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (189, 'RHH MODALIDAD DECIMO TERCERO', SYSDATE, 188, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 189, d.DSCR, d.ALTR, 1 FROM (
    SELECT 811 AS CDGO, 'MENSUALIZADO' AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 812, 'ACUMULADO',    2 FROM DUAL
) d;


-- =====================================================
-- 189 / PRBRCDGO 190 - RHH_MODALIDAD_DECIMO_CUARTO
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (190, 'RHH MODALIDAD DECIMO CUARTO', SYSDATE, 189, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 190, d.DSCR, d.ALTR, 1 FROM (
    SELECT 813 AS CDGO, 'MENSUALIZADO' AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 814, 'ACUMULADO',    2 FROM DUAL
) d;


-- =====================================================
-- 190 / PRBRCDGO 191 - RHH_MODALIDAD_FONDOS_RESERVA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (191, 'RHH MODALIDAD FONDOS DE RESERVA', SYSDATE, 190, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 191, d.DSCR, d.ALTR, 1 FROM (
    SELECT 815 AS CDGO, 'MENSUALIZADO'         AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 816, 'ACUMULADO EN EL IESS', 2 FROM DUAL UNION ALL
    SELECT 817, 'NO APLICA',            3 FROM DUAL
) d;


-- =====================================================
-- 191 / PRBRCDGO 192 - RHH_TIPO_HORA_EXTRA
-- El PDTRVLRN lleva el porcentaje de recargo: el motor lo lee de aqui.
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (192, 'RHH TIPO DE HORA EXTRA', SYSDATE, 191, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRVLRN, PDTRESTD)
SELECT d.CDGO, 192, d.DSCR, d.ALTR, d.VLRN, 1 FROM (
    SELECT 818 AS CDGO, 'SUPLEMENTARIA 50'    AS DSCR, 1 AS ALTR,  50 AS VLRN FROM DUAL UNION ALL
    SELECT 819, 'EXTRAORDINARIA 100',  2, 100 FROM DUAL UNION ALL
    SELECT 820, 'RECARGO NOCTURNO 25', 3,  25 FROM DUAL
) d;


-- =====================================================
-- 192 / PRBRCDGO 193 - RHH_TIPO_MARCACION
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (193, 'RHH TIPO DE MARCACION', SYSDATE, 192, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 193, d.DSCR, d.ALTR, 1 FROM (
    SELECT 821 AS CDGO, 'ENTRADA'          AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 822, 'SALIDA',            2 FROM DUAL UNION ALL
    SELECT 823, 'SALIDA ALMUERZO',   3 FROM DUAL UNION ALL
    SELECT 824, 'RETORNO ALMUERZO',  4 FROM DUAL UNION ALL
    SELECT 825, 'SALIDA PERMISO',    5 FROM DUAL UNION ALL
    SELECT 826, 'RETORNO PERMISO',   6 FROM DUAL
) d;


-- =====================================================
-- 193 / PRBRCDGO 194 - RHH_ORIGEN_MARCACION
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (194, 'RHH ORIGEN DE LA MARCACION', SYSDATE, 193, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 194, d.DSCR, d.ALTR, 1 FROM (
    SELECT 827 AS CDGO, 'BIOMETRICO'          AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 828, 'MANUAL',               2 FROM DUAL UNION ALL
    SELECT 829, 'IMPORTACION ARCHIVO',  3 FROM DUAL UNION ALL
    SELECT 830, 'APLICACION MOVIL',     4 FROM DUAL UNION ALL
    SELECT 831, 'CORRECCION APROBADA',  5 FROM DUAL
) d;


-- =====================================================
-- 194 / PRBRCDGO 195 - RHH_ESTADO_CARGA_MARCACIONES
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (195, 'RHH ESTADO DE LA CARGA DE MARCACIONES', SYSDATE, 194, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 195, d.DSCR, d.ALTR, 1 FROM (
    SELECT 832 AS CDGO, 'CARGADO'     AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 833, 'VALIDADO',    2 FROM DUAL UNION ALL
    SELECT 834, 'CON ERRORES', 3 FROM DUAL UNION ALL
    SELECT 835, 'CONSOLIDADO', 4 FROM DUAL UNION ALL
    SELECT 836, 'ANULADO',     5 FROM DUAL
) d;


-- =====================================================
-- 195 / PRBRCDGO 196 - RHH_CAUSAL_TERMINACION
-- El PDTRVLRV lleva el articulo del Codigo del Trabajo.
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (196, 'RHH CAUSAL DE TERMINACION LABORAL', SYSDATE, 195, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRVLRV, PDTRESTD)
SELECT d.CDGO, 196, d.DSCR, d.ALTR, d.ARTC, 1 FROM (
    SELECT 837 AS CDGO, 'RENUNCIA VOLUNTARIA'       AS DSCR,  1 AS ALTR, 'Art. 169 num. 2' AS ARTC FROM DUAL UNION ALL
    SELECT 838, 'DESAHUCIO',                 2, 'Art. 184'        FROM DUAL UNION ALL
    SELECT 839, 'VISTO BUENO',               3, 'Art. 172'        FROM DUAL UNION ALL
    SELECT 840, 'DESPIDO INTEMPESTIVO',      4, 'Art. 188'        FROM DUAL UNION ALL
    SELECT 841, 'MUTUO ACUERDO',             5, 'Art. 169 num. 2' FROM DUAL UNION ALL
    SELECT 842, 'TERMINACION DEL PLAZO',     6, 'Art. 169 num. 3' FROM DUAL UNION ALL
    SELECT 843, 'JUBILACION',                7, 'Art. 188'        FROM DUAL UNION ALL
    SELECT 844, 'FALLECIMIENTO',             8, 'Art. 169 num. 7' FROM DUAL UNION ALL
    SELECT 845, 'LIQUIDACION DE LA EMPRESA', 9, 'Art. 193'        FROM DUAL UNION ALL
    SELECT 846, 'CASO FORTUITO',            10, 'Art. 169 num. 6' FROM DUAL
) d;


-- =====================================================
-- 196 / PRBRCDGO 197 - RHH_ESTADO_LIQUIDACION
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (197, 'RHH ESTADO DE LA LIQUIDACION', SYSDATE, 196, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 197, d.DSCR, d.ALTR, 1 FROM (
    SELECT 847 AS CDGO, 'BORRADOR'          AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 848, 'CALCULADA',         2 FROM DUAL UNION ALL
    SELECT 849, 'APROBADA',          3 FROM DUAL UNION ALL
    SELECT 850, 'REGISTRADA EN SUT', 4 FROM DUAL UNION ALL
    SELECT 851, 'PAGADA',            5 FROM DUAL UNION ALL
    SELECT 852, 'ANULADA',           6 FROM DUAL
) d;


-- =====================================================
-- 197 / PRBRCDGO 198 - RHH_TIPO_DESCUENTO_RECURRENTE
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (198, 'RHH TIPO DE DESCUENTO RECURRENTE', SYSDATE, 197, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 198, d.DSCR, d.ALTR, 1 FROM (
    SELECT 853 AS CDGO, 'PRESTAMO QUIROGRAFARIO IESS' AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 854, 'PRESTAMO HIPOTECARIO IESS',   2 FROM DUAL UNION ALL
    SELECT 855, 'ANTICIPO DE SUELDO',          3 FROM DUAL UNION ALL
    SELECT 856, 'PRESTAMO INTERNO',            4 FROM DUAL UNION ALL
    SELECT 857, 'RETENCION JUDICIAL',          5 FROM DUAL UNION ALL
    SELECT 858, 'SEGURO PRIVADO',              6 FROM DUAL UNION ALL
    SELECT 859, 'OTROS',                       7 FROM DUAL
) d;


-- =====================================================
-- 198 / PRBRCDGO 199 - RHH_ESTADO_DESCUENTO_RECURRENTE
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (199, 'RHH ESTADO DEL DESCUENTO RECURRENTE', SYSDATE, 198, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 199, d.DSCR, d.ALTR, 1 FROM (
    SELECT 860 AS CDGO, 'VIGENTE'   AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 861, 'SUSPENDIDO', 2 FROM DUAL UNION ALL
    SELECT 862, 'CANCELADO',  3 FROM DUAL UNION ALL
    SELECT 863, 'ANULADO',    4 FROM DUAL
) d;


-- =====================================================
-- 199 / PRBRCDGO 200 - RHH_TIPO_CUENTA_BANCARIA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (200, 'RHH TIPO DE CUENTA BANCARIA', SYSDATE, 199, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 200, d.DSCR, d.ALTR, 1 FROM (
    SELECT 864 AS CDGO, 'AHORROS'  AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 865, 'CORRIENTE', 2 FROM DUAL
) d;


-- =====================================================
-- 200 / PRBRCDGO 201 - RHH_PARENTESCO_CARGA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (201, 'RHH PARENTESCO DE LA CARGA FAMILIAR', SYSDATE, 200, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 201, d.DSCR, d.ALTR, 1 FROM (
    SELECT 866 AS CDGO, 'CONYUGE'     AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 867, 'CONVIVIENTE', 2 FROM DUAL UNION ALL
    SELECT 868, 'HIJO',        3 FROM DUAL UNION ALL
    SELECT 869, 'PADRE',       4 FROM DUAL UNION ALL
    SELECT 870, 'MADRE',       5 FROM DUAL UNION ALL
    SELECT 871, 'HERMANO',     6 FROM DUAL UNION ALL
    SELECT 872, 'OTRO',        7 FROM DUAL
) d;


-- =====================================================
-- 201 / PRBRCDGO 202 - RHH_TIPO_GASTO_PERSONAL
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (202, 'RHH TIPO DE GASTO PERSONAL', SYSDATE, 201, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 202, d.DSCR, d.ALTR, 1 FROM (
    SELECT 873 AS CDGO, 'VIVIENDA'                 AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 874, 'EDUCACION ARTE Y CULTURA', 2 FROM DUAL UNION ALL
    SELECT 875, 'ALIMENTACION',             3 FROM DUAL UNION ALL
    SELECT 876, 'VESTIMENTA',               4 FROM DUAL UNION ALL
    SELECT 877, 'SALUD',                    5 FROM DUAL UNION ALL
    SELECT 878, 'TURISMO',                  6 FROM DUAL
) d;


-- =====================================================
-- 202 / PRBRCDGO 203 - RHH_TIPO_ACUMULADO
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (203, 'RHH TIPO DE ACUMULADO', SYSDATE, 202, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 203, d.DSCR, d.ALTR, 1 FROM (
    SELECT 879 AS CDGO, 'IMPONIBLE IESS'         AS DSCR,  1 AS ALTR FROM DUAL UNION ALL
    SELECT 880, 'GRAVADO IR',             2 FROM DUAL UNION ALL
    SELECT 881, 'BASE DECIMO TERCERO',    3 FROM DUAL UNION ALL
    SELECT 882, 'BASE DECIMO CUARTO',     4 FROM DUAL UNION ALL
    SELECT 883, 'BASE FONDOS DE RESERVA', 5 FROM DUAL UNION ALL
    SELECT 884, 'BASE UTILIDADES',        6 FROM DUAL UNION ALL
    SELECT 885, 'BASE VACACIONES',        7 FROM DUAL UNION ALL
    SELECT 886, 'APORTE PERSONAL',        8 FROM DUAL UNION ALL
    SELECT 887, 'RETENCION IR',           9 FROM DUAL UNION ALL
    SELECT 888, 'DIAS TRABAJADOS',       10 FROM DUAL
) d;


-- =====================================================
-- 203 / PRBRCDGO 204 - RHH_TIPO_BENEFICIO_SOCIAL
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (204, 'RHH TIPO DE BENEFICIO SOCIAL', SYSDATE, 203, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 204, d.DSCR, d.ALTR, 1 FROM (
    SELECT 889 AS CDGO, 'DECIMO TERCERO'    AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 890, 'DECIMO CUARTO',     2 FROM DUAL UNION ALL
    SELECT 891, 'FONDOS DE RESERVA', 3 FROM DUAL UNION ALL
    SELECT 892, 'VACACIONES',        4 FROM DUAL UNION ALL
    SELECT 893, 'UTILIDADES',        5 FROM DUAL
) d;


-- =====================================================
-- 204 / PRBRCDGO 205 - RHH_TIPO_NOVEDAD_IESS
-- El PDTRVLRN lleva el plazo legal en dias para reportar la novedad.
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (205, 'RHH TIPO DE NOVEDAD IESS', SYSDATE, 204, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRVLRN, PDTRESTD)
SELECT d.CDGO, 205, d.DSCR, d.ALTR, d.DIAS, 1 FROM (
    SELECT 894 AS CDGO, 'AVISO DE ENTRADA'          AS DSCR, 1 AS ALTR, 15 AS DIAS FROM DUAL UNION ALL
    SELECT 895, 'AVISO DE SALIDA',           2, 3 FROM DUAL UNION ALL
    SELECT 896, 'MODIFICACION DE SUELDO',    3, 3 FROM DUAL UNION ALL
    SELECT 897, 'NOVEDAD FONDOS DE RESERVA', 4, 3 FROM DUAL UNION ALL
    SELECT 898, 'CAMBIO DE MODALIDAD',       5, 3 FROM DUAL
) d;


-- =====================================================
-- 205 / PRBRCDGO 206 - RHH_ESTADO_NOVEDAD_IESS
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (206, 'RHH ESTADO DE LA NOVEDAD IESS', SYSDATE, 205, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 206, d.DSCR, d.ALTR, 1 FROM (
    SELECT 899 AS CDGO, 'PENDIENTE' AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 900, 'ENVIADA',   2 FROM DUAL UNION ALL
    SELECT 901, 'ACEPTADA',  3 FROM DUAL UNION ALL
    SELECT 902, 'RECHAZADA', 4 FROM DUAL UNION ALL
    SELECT 903, 'ANULADA',   5 FROM DUAL
) d;


-- =====================================================
-- 206 / PRBRCDGO 207 - RHH_TIPO_PROVISION
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (207, 'RHH TIPO DE PROVISION', SYSDATE, 206, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 207, d.DSCR, d.ALTR, 1 FROM (
    SELECT 904 AS CDGO, 'DECIMO TERCERO'      AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 905, 'DECIMO CUARTO',       2 FROM DUAL UNION ALL
    SELECT 906, 'VACACIONES',          3 FROM DUAL UNION ALL
    SELECT 907, 'FONDOS DE RESERVA',   4 FROM DUAL UNION ALL
    SELECT 908, 'APORTE PATRONAL',     5 FROM DUAL UNION ALL
    SELECT 909, 'JUBILACION PATRONAL', 6 FROM DUAL UNION ALL
    SELECT 910, 'DESAHUCIO',           7 FROM DUAL
) d;


-- =====================================================
-- 207 / PRBRCDGO 208 - RHH_TIPO_AUSENCIA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (208, 'RHH TIPO DE AUSENCIA', SYSDATE, 207, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 208, d.DSCR, d.ALTR, 1 FROM (
    SELECT 911 AS CDGO, 'FALTA INJUSTIFICADA'      AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 912, 'PERMISO CON GOCE',         2 FROM DUAL UNION ALL
    SELECT 913, 'PERMISO SIN GOCE',         3 FROM DUAL UNION ALL
    SELECT 914, 'ENFERMEDAD IESS',          4 FROM DUAL UNION ALL
    SELECT 915, 'ACCIDENTE LABORAL',        5 FROM DUAL UNION ALL
    SELECT 916, 'MATERNIDAD O PATERNIDAD',  6 FROM DUAL UNION ALL
    SELECT 917, 'CALAMIDAD DOMESTICA',      7 FROM DUAL UNION ALL
    SELECT 918, 'VACACIONES',               8 FROM DUAL UNION ALL
    SELECT 919, 'COMISION DE SERVICIOS',    9 FROM DUAL
) d;


-- =====================================================
-- 208 / PRBRCDGO 209 - RHH_ESTADO_ORDEN_PAGO
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (209, 'RHH ESTADO DE LA ORDEN DE PAGO', SYSDATE, 208, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 209, d.DSCR, d.ALTR, 1 FROM (
    SELECT 920 AS CDGO, 'GENERADA'          AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 921, 'ENVIADA AL BANCO',  2 FROM DUAL UNION ALL
    SELECT 922, 'CONFIRMADA',        3 FROM DUAL UNION ALL
    SELECT 923, 'RECHAZADA PARCIAL', 4 FROM DUAL UNION ALL
    SELECT 924, 'ANULADA',           5 FROM DUAL
) d;


-- =====================================================
-- 209 / PRBRCDGO 210 - RHH_FORMATO_ARCHIVO_MARCACION
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (210, 'RHH FORMATO DEL ARCHIVO DE MARCACION', SYSDATE, 209, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 210, d.DSCR, d.ALTR, 1 FROM (
    SELECT 925 AS CDGO, 'ANCHO FIJO' AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 926, 'DELIMITADO', 2 FROM DUAL UNION ALL
    SELECT 927, 'CSV',        3 FROM DUAL UNION ALL
    SELECT 928, 'EXCEL',      4 FROM DUAL
) d;


-- =====================================================
-- 210 / PRBRCDGO 211 - RHH_TIPO_JORNADA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (211, 'RHH TIPO DE JORNADA', SYSDATE, 210, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 211, d.DSCR, d.ALTR, 1 FROM (
    SELECT 929 AS CDGO, 'COMPLETA'            AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 930, 'PARCIAL PERMANENTE',  2 FROM DUAL UNION ALL
    SELECT 931, 'POR HORAS',           3 FROM DUAL UNION ALL
    SELECT 932, 'TELETRABAJO',         4 FROM DUAL UNION ALL
    SELECT 933, 'NOCTURNA',            5 FROM DUAL
) d;


-- =====================================================
-- 211 / PRBRCDGO 212 - RHH_TIPO_SALDO_APERTURA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (212, 'RHH TIPO DE SALDO DE APERTURA', SYSDATE, 211, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 212, d.DSCR, d.ALTR, 1 FROM (
    SELECT 934 AS CDGO, 'ANTIGUEDAD'                   AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 935, 'VACACIONES PENDIENTES',        2 FROM DUAL UNION ALL
    SELECT 936, 'DECIMO TERCERO ACUMULADO',     3 FROM DUAL UNION ALL
    SELECT 937, 'DECIMO CUARTO ACUMULADO',      4 FROM DUAL UNION ALL
    SELECT 938, 'FONDOS DE RESERVA ACUMULADOS', 5 FROM DUAL UNION ALL
    SELECT 939, 'PRESTAMO IESS',                6 FROM DUAL UNION ALL
    SELECT 940, 'PRESTAMO INTERNO',             7 FROM DUAL UNION ALL
    SELECT 941, 'IR RETENIDO EN EL ANIO',       8 FROM DUAL
) d;


-- =====================================================
-- 212 / PRBRCDGO 213 - RHH_TIPO_PERIODO_NOMINA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (213, 'RHH TIPO DE PERIODO DE NOMINA', SYSDATE, 212, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 213, d.DSCR, d.ALTR, 1 FROM (
    SELECT 942 AS CDGO, 'MENSUAL'              AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 943, 'QUINCENAL',            2 FROM DUAL UNION ALL
    SELECT 944, 'DECIMO TERCERO',       3 FROM DUAL UNION ALL
    SELECT 945, 'DECIMO CUARTO',        4 FROM DUAL UNION ALL
    SELECT 946, 'UTILIDADES',           5 FROM DUAL UNION ALL
    SELECT 947, 'LIQUIDACION',          6 FROM DUAL UNION ALL
    SELECT 948, 'BONO EXTRAORDINARIO',  7 FROM DUAL
) d;


-- =====================================================
-- 213 / PRBRCDGO 214 - RHH_ORIGEN_RENGLON
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (214, 'RHH ORIGEN DEL RENGLON DE NOMINA', SYSDATE, 213, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 214, d.DSCR, d.ALTR, 1 FROM (
    SELECT 949 AS CDGO, 'CALCULO AUTOMATICO'         AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 950, 'NOVEDAD DEL PERIODO',        2 FROM DUAL UNION ALL
    SELECT 951, 'DESCUENTO RECURRENTE',       3 FROM DUAL UNION ALL
    SELECT 952, 'HORA EXTRA',                 4 FROM DUAL UNION ALL
    SELECT 953, 'CONCEPTO FIJO DEL EMPLEADO', 5 FROM DUAL UNION ALL
    SELECT 954, 'INGRESO MANUAL',             6 FROM DUAL
) d;


-- =====================================================
-- 214 / PRBRCDGO 215 - RHH_LINEA_ASIENTO  <<< SEMANTICA DE DTPLAXL1 >>>
-- Identifica el rol de cada linea dentro de la plantilla contable.
-- El proceso busca su linea con:
--   SELECT ... FROM CNT.DTPL WHERE PLNSCDGO = :plantilla AND DTPLAXL1 = :codigoAlternoLinea
-- Rangos: 1-29 rol de pagos, 30-49 provisiones, 50-59 pago, 60-79 liquidacion.
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (215, 'RHH LINEA DEL ASIENTO CONTABLE', SYSDATE, 214, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 215, d.DSCR, d.ALTR, 1 FROM (
    -- Asiento de ROL DE PAGOS
    SELECT 955 AS CDGO, 'GASTO SUELDOS Y SALARIOS'      AS DSCR,  1 AS ALTR FROM DUAL UNION ALL
    SELECT 956, 'GASTO HORAS EXTRA',                 2 FROM DUAL UNION ALL
    SELECT 957, 'GASTO APORTE PATRONAL IESS',        3 FROM DUAL UNION ALL
    SELECT 958, 'GASTO IECE Y SECAP',                4 FROM DUAL UNION ALL
    SELECT 959, 'GASTO FONDOS DE RESERVA',           5 FROM DUAL UNION ALL
    SELECT 960, 'GASTO DECIMO TERCERO',              6 FROM DUAL UNION ALL
    SELECT 961, 'GASTO DECIMO CUARTO',               7 FROM DUAL UNION ALL
    SELECT 962, 'IESS POR PAGAR APORTE PERSONAL',   10 FROM DUAL UNION ALL
    SELECT 963, 'IESS POR PAGAR APORTE PATRONAL',   11 FROM DUAL UNION ALL
    SELECT 964, 'IESS POR PAGAR PRESTAMOS',         12 FROM DUAL UNION ALL
    SELECT 965, 'SRI RETENCION EN LA FUENTE RD',    13 FROM DUAL UNION ALL
    SELECT 966, 'CUENTAS POR COBRAR EMPLEADOS',     14 FROM DUAL UNION ALL
    SELECT 967, 'RETENCIONES JUDICIALES POR PAGAR', 15 FROM DUAL UNION ALL
    SELECT 968, 'FONDOS DE RESERVA POR PAGAR',      16 FROM DUAL UNION ALL
    SELECT 969, 'DECIMOS POR PAGAR',                17 FROM DUAL UNION ALL
    SELECT 970, 'SUELDOS POR PAGAR',                18 FROM DUAL UNION ALL
    -- Asiento de PROVISIONES
    SELECT 971, 'GASTO PROVISION DECIMO TERCERO',       30 FROM DUAL UNION ALL
    SELECT 972, 'GASTO PROVISION DECIMO CUARTO',        31 FROM DUAL UNION ALL
    SELECT 973, 'GASTO PROVISION VACACIONES',           32 FROM DUAL UNION ALL
    SELECT 974, 'GASTO PROVISION FONDOS DE RESERVA',    33 FROM DUAL UNION ALL
    SELECT 975, 'GASTO PROVISION JUBILACION PATRONAL',  34 FROM DUAL UNION ALL
    SELECT 976, 'GASTO PROVISION DESAHUCIO',            35 FROM DUAL UNION ALL
    SELECT 977, 'PROVISION DECIMO TERCERO POR PAGAR',   40 FROM DUAL UNION ALL
    SELECT 978, 'PROVISION DECIMO CUARTO POR PAGAR',    41 FROM DUAL UNION ALL
    SELECT 979, 'PROVISION VACACIONES POR PAGAR',       42 FROM DUAL UNION ALL
    SELECT 980, 'PROVISION FONDOS DE RESERVA POR PAGAR',43 FROM DUAL UNION ALL
    SELECT 981, 'PROVISION JUBILACION PATRONAL',        44 FROM DUAL UNION ALL
    SELECT 982, 'PROVISION DESAHUCIO',                  45 FROM DUAL UNION ALL
    -- Asiento de PAGO
    SELECT 983, 'SUELDOS POR PAGAR DEBE',               50 FROM DUAL UNION ALL
    SELECT 984, 'BANCO',                                51 FROM DUAL UNION ALL
    -- Asiento de LIQUIDACION
    SELECT 985, 'GASTO DESAHUCIO',                      60 FROM DUAL UNION ALL
    SELECT 986, 'GASTO DESPIDO INTEMPESTIVO',           61 FROM DUAL UNION ALL
    SELECT 987, 'GASTO JUBILACION PATRONAL',            62 FROM DUAL UNION ALL
    SELECT 988, 'GASTO SUELDOS LIQUIDACION',            63 FROM DUAL UNION ALL
    SELECT 989, 'LIQUIDACIONES POR PAGAR',              70 FROM DUAL
) d;


-- =====================================================
-- 215 / PRBRCDGO 216 - RHH_CAMPO_ARCHIVO_MARCACION
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (216, 'RHH CAMPO DEL ARCHIVO DE MARCACION', SYSDATE, 215, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 216, d.DSCR, d.ALTR, 1 FROM (
    SELECT 990 AS CDGO, 'ID EMPLEADO'    AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 991, 'FECHA',          2 FROM DUAL UNION ALL
    SELECT 992, 'HORA',           3 FROM DUAL UNION ALL
    SELECT 993, 'FECHA Y HORA',   4 FROM DUAL UNION ALL
    SELECT 994, 'TIPO MARCACION', 5 FROM DUAL UNION ALL
    SELECT 995, 'ID DISPOSITIVO', 6 FROM DUAL UNION ALL
    SELECT 996, 'IDENTIFICACION', 7 FROM DUAL
) d;


-- =====================================================
-- 216 / PRBRCDGO 217 - RHH_ENTIDAD_RECAUDADORA
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (217, 'RHH ENTIDAD RECAUDADORA', SYSDATE, 216, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 217, d.DSCR, d.ALTR, 1 FROM (
    SELECT  997 AS CDGO, 'IESS'                    AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT  998, 'SRI',                      2 FROM DUAL UNION ALL
    SELECT  999, 'JUZGADO',                  3 FROM DUAL UNION ALL
    SELECT 1000, 'INSTITUCION FINANCIERA',   4 FROM DUAL UNION ALL
    SELECT 1001, 'EMPRESA',                  5 FROM DUAL UNION ALL
    SELECT 1002, 'OTRO',                     6 FROM DUAL
) d;


-- =====================================================
-- 217 / PRBRCDGO 218 - RHH_TIPO_CAMBIO_HISTORIAL
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (218, 'RHH TIPO DE CAMBIO EN EL HISTORIAL', SYSDATE, 217, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 218, d.DSCR, d.ALTR, 1 FROM (
    SELECT 1003 AS CDGO, 'INGRESO'            AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 1004, 'ASCENSO',            2 FROM DUAL UNION ALL
    SELECT 1005, 'CAMBIO DE SUELDO',   3 FROM DUAL UNION ALL
    SELECT 1006, 'CAMBIO DE AREA',     4 FROM DUAL UNION ALL
    SELECT 1007, 'CAMBIO DE JORNADA',  5 FROM DUAL UNION ALL
    SELECT 1008, 'TERMINACION',        6 FROM DUAL UNION ALL
    SELECT 1009, 'REINGRESO',          7 FROM DUAL
) d;


-- =====================================================
-- 218 / PRBRCDGO 219 - RHH_GENERO
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (219, 'RHH GENERO', SYSDATE, 218, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 219, d.DSCR, d.ALTR, 1 FROM (
    SELECT 1010 AS CDGO, 'MASCULINO' AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 1011, 'FEMENINO',  2 FROM DUAL UNION ALL
    SELECT 1012, 'OTRO',      3 FROM DUAL
) d;


-- =====================================================
-- 219 / PRBRCDGO 220 - RHH_ESTADO_CIVIL
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (220, 'RHH ESTADO CIVIL', SYSDATE, 219, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 220, d.DSCR, d.ALTR, 1 FROM (
    SELECT 1013 AS CDGO, 'SOLTERO'        AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 1014, 'CASADO',          2 FROM DUAL UNION ALL
    SELECT 1015, 'DIVORCIADO',      3 FROM DUAL UNION ALL
    SELECT 1016, 'VIUDO',           4 FROM DUAL UNION ALL
    SELECT 1017, 'UNION DE HECHO',  5 FROM DUAL
) d;


-- =====================================================
-- 220 / PRBRCDGO 221 - RHH_NIVEL_INSTRUCCION
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (221, 'RHH NIVEL DE INSTRUCCION', SYSDATE, 220, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 221, d.DSCR, d.ALTR, 1 FROM (
    SELECT 1018 AS CDGO, 'PRIMARIA'     AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 1019, 'SECUNDARIA',   2 FROM DUAL UNION ALL
    SELECT 1020, 'TECNICO',      3 FROM DUAL UNION ALL
    SELECT 1021, 'TERCER NIVEL', 4 FROM DUAL UNION ALL
    SELECT 1022, 'CUARTO NIVEL', 5 FROM DUAL UNION ALL
    SELECT 1023, 'NINGUNA',      6 FROM DUAL
) d;

COMMIT;




-- =====================================================
-- 221 / PRBRCDGO 222 - RHH_ROL_CONCEPTO_MOTOR
-- =====================================================
-- Identifica que papel cumple un concepto de RHH.CPNM dentro del motor de
-- calculo. Sustituye a la deteccion por la terna (tipo de concepto, tipo de
-- calculo, base de calculo), que era discriminante en el catalogo inicial pero
-- deja de serlo en cuanto el cliente agrega conceptos propios: un "Bono
-- navideno" definido como INGRESO / FORMULA / SBU colisionaria con el decimo
-- cuarto y el motor tomaria el equivocado sin avisar.
--
-- Se asigna en el script 08 con un UPDATE. Los conceptos ordinarios lo dejan en
-- NULL y el motor los trata genericamente.
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (222, 'RHH ROL DEL CONCEPTO EN EL MOTOR', SYSDATE, 221, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 222, d.DSCR, d.ALTR, 1 FROM (
    SELECT 1024 AS CDGO, 'APORTE PERSONAL'        AS DSCR,  1 AS ALTR FROM DUAL UNION ALL
    SELECT 1025, 'APORTE PATRONAL',         2 FROM DUAL UNION ALL
    SELECT 1026, 'IECE',                    3 FROM DUAL UNION ALL
    SELECT 1027, 'SECAP',                   4 FROM DUAL UNION ALL
    SELECT 1028, 'FONDOS DE RESERVA',       5 FROM DUAL UNION ALL
    SELECT 1029, 'DECIMO TERCERO',          6 FROM DUAL UNION ALL
    SELECT 1030, 'DECIMO CUARTO',           7 FROM DUAL UNION ALL
    SELECT 1031, 'IMPUESTO A LA RENTA',     8 FROM DUAL UNION ALL
    SELECT 1032, 'HORA SUPLEMENTARIA',      9 FROM DUAL UNION ALL
    SELECT 1033, 'HORA EXTRAORDINARIA',    10 FROM DUAL UNION ALL
    SELECT 1034, 'RECARGO NOCTURNO',       11 FROM DUAL UNION ALL
    SELECT 1035, 'PRESTAMO QUIROGRAFARIO', 12 FROM DUAL UNION ALL
    SELECT 1036, 'PRESTAMO HIPOTECARIO',   13 FROM DUAL UNION ALL
    SELECT 1037, 'ANTICIPO DE SUELDO',     14 FROM DUAL UNION ALL
    SELECT 1038, 'PRESTAMO INTERNO',       15 FROM DUAL UNION ALL
    SELECT 1039, 'RETENCION JUDICIAL',     16 FROM DUAL UNION ALL
    SELECT 1044, 'PROVISION DECIMO TERCERO',       17 FROM DUAL UNION ALL
    SELECT 1045, 'PROVISION DECIMO CUARTO',        18 FROM DUAL UNION ALL
    SELECT 1046, 'PROVISION VACACIONES',           19 FROM DUAL UNION ALL
    SELECT 1047, 'PROVISION FONDOS DE RESERVA',    20 FROM DUAL UNION ALL
    SELECT 1048, 'PROVISION JUBILACION PATRONAL',  21 FROM DUAL UNION ALL
    SELECT 1049, 'PROVISION DESAHUCIO',            22 FROM DUAL
) d;


-- =====================================================
-- 222 / PRBRCDGO 223 - RHH_ESTADO_CUOTA_DESCUENTO
-- =====================================================
-- Estados de RHH.CTDS.CTDSESTD. Hasta ahora los valores vivian solo en un
-- comentario del DDL, que es justo lo que prohibe la regla 2 del maestro.
--
-- NO reutilizar com.saa.rubros.EstadoCuotaPrestamo: pertenece al modulo de
-- Credito y describe otro dominio.
-- =====================================================
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (223, 'RHH ESTADO DE LA CUOTA DE DESCUENTO', SYSDATE, 222, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 223, d.DSCR, d.ALTR, 1 FROM (
    SELECT 1040 AS CDGO, 'PENDIENTE'  AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 1041, 'DESCONTADA', 2 FROM DUAL UNION ALL
    SELECT 1042, 'PARCIAL',    3 FROM DUAL UNION ALL
    SELECT 1043, 'ANULADA',    4 FROM DUAL
) d;

-- =====================================================
-- VERIFICACION
-- =====================================================
-- 1) Deben quedar 44 rubros con PRBRCDGO del 180 al 223:
-- SELECT COUNT(*) FROM SCP.PRBR WHERE PRBRALTR BETWEEN 179 AND 222;   -- 44
-- SELECT MIN(PRBRCDGO), MAX(PRBRCDGO) FROM SCP.PRBR
--  WHERE PRBRALTR BETWEEN 179 AND 222;                                -- 180 y 223
--
-- 2) La relacion PRBRCDGO = PRBRALTR + 1 debe cumplirse en las 44 filas:
-- SELECT PRBRALTR, PRBRCDGO FROM SCP.PRBR
--  WHERE PRBRALTR BETWEEN 179 AND 222 AND PRBRCDGO <> PRBRALTR + 1;   -- cero filas
--
-- 3) Deben quedar 289 detalles con PDTRCDGO del 761 al 1049, sin huecos:
-- SELECT COUNT(*), MIN(PDTRCDGO), MAX(PDTRCDGO) FROM SCP.PDTR
--  WHERE PDTRCDGO BETWEEN 761 AND 1049;                               -- 289, 761, 1049
--
-- 4) Detalles por rubro:
-- SELECT r.PRBRALTR, r.PRBRDSCR, COUNT(d.PDTRCDGO) AS DETALLES
--   FROM SCP.PRBR r LEFT JOIN SCP.PDTR d ON d.PRBRCDGO = r.PRBRCDGO
--  WHERE r.PRBRALTR BETWEEN 179 AND 222
--  GROUP BY r.PRBRALTR, r.PRBRDSCR ORDER BY r.PRBRALTR;
--
-- 5) El rol del motor debe quedar asignado y sin duplicados tras el script 08:
-- SELECT CPNMROLM, COUNT(*) FROM RHH.CPNM
--  WHERE CPNMROLM IS NOT NULL GROUP BY CPNMROLM HAVING COUNT(*) > 1;  -- cero filas
--
-- 6) IMPORTANTE - adelantar las secuencias para que JPA no repita PK:
-- ALTER SEQUENCE SCP.SQ_PRBRCDGO RESTART START WITH 224;
-- ALTER SEQUENCE SCP.SQ_PDTRCDGO RESTART START WITH 1050;
