-- =====================================================
-- MODULO: RHH - HUECOS DE MODELO DE LAS FASES 5 A 9
-- DESCRIPCION: Cierra los dos huecos que las fases 5-9 chocarian de
--              inmediato: la cuenta marcadora sin lugar donde guardarse
--              y la falta de trazabilidad de las salidas oficiales.
-- ORDEN DE EJECUCION: 13 (despues del 12)
-- PARAMETROS: ninguno. El esquema RHH y los rubros de SCP son globales, y la
--             cuenta marcadora se asigna a todas las empresas por igual.
-- FECHA: 2026-08-19
-- =====================================================
-- QUE HACE
--   PASO 1  RHH.CFNM.CFNMCTMR  -- la cuenta marcadora, hoy el literal 9678
--   PASO 2  Rubro alterno 223  -- RHH TIPO DE SALIDA OFICIAL
--   PASO 3  RHH.SLOF           -- registro de cada salida oficial generada
--   PASO 4  Adelantar las secuencias de rubro
--
-- POR QUE EL PASO 1
--   El §6.2 del plan de backend obliga a validarCuentasContables a buscar
--   PLNNCDGO = 9678, no IS NULL, porque CNT.DTPL.PLNNCDGO es NOT NULL y el
--   script 09 no pudo dejar las lineas sin cuenta. Escribir 9678 en Java
--   incumple la regla 1 del maestro: ningun valor normativo en el codigo.
--   Con esta columna la validacion lee el marcador de CFNM y un cambio de
--   marcador se resuelve con un UPDATE.
--
-- POR QUE EL PASO 3
--   La fase 9 emite RDEP, formulario 107, planilla IESS y formularios MDT.
--   Los DATOS de esas salidas ya estan persistidos --RNGL, ACMN, LQBS--, asi
--   que regenerar un archivo es deterministico y no hace falta duplicarlos.
--   Lo que no existe en ninguna tabla es el HECHO de la presentacion: cuando
--   se genero, quien, contra que archivo, y sobre todo si ya se presento al
--   organismo y con que numero de comprobante. Eso es dato de negocio y es
--   lo unico que persiste SLOF.
--
--   Se descarto reusar RPR.EJRC: su EJRCTPEJ es un rubro del modulo de
--   reportes a la Superintendencia y no tiene empleado, que el formulario
--   107 necesita porque se emite uno por persona.
-- =====================================================


-- =====================================================
-- PASO 1: LA CUENTA MARCADORA COMO PARAMETRO
-- =====================================================
ALTER TABLE RHH.CFNM ADD (
    CFNMCTMR NUMBER DEFAULT 9678 -- PLNNCDGO de la cuenta marcadora
);

COMMENT ON COLUMN RHH.CFNM.CFNMCTMR IS 'PLNNCDGO de la cuenta contable MARCADORA. Una linea de plantilla que todavia apunte a esta cuenta esta sin configurar: validarCuentasContables la reporta y bloquea la contabilizacion. No es una cuenta real de ningun asiento';

-- Las filas que ya existen se quedan con el marcador vigente.
UPDATE RHH.CFNM SET CFNMCTMR = 9678 WHERE CFNMCTMR IS NULL;


-- =====================================================
-- PASO 2: RUBRO 223 - TIPO DE SALIDA OFICIAL
-- =====================================================
-- Recordatorio de la asimetria de SCP.PRBR: PRBRCDGO es la PK y PRBRALTR
-- el codigo alterno, y van corridos en uno. El rubro alterno 223 es la PK 224.
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (224, 'RHH TIPO DE SALIDA OFICIAL', SYSDATE, 223, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 224, d.DSCR, d.ALTR, 1 FROM (
    SELECT 1050 AS CDGO, 'RDEP'                          AS DSCR, 1 AS ALTR FROM DUAL UNION ALL
    SELECT 1051, 'FORMULARIO 107',                    2 FROM DUAL UNION ALL
    SELECT 1052, 'PLANILLA IESS',                     3 FROM DUAL UNION ALL
    SELECT 1053, 'FORMULARIO MDT DECIMO TERCERO',     4 FROM DUAL UNION ALL
    SELECT 1054, 'FORMULARIO MDT DECIMO CUARTO',      5 FROM DUAL UNION ALL
    SELECT 1055, 'FORMULARIO MDT UTILIDADES',         6 FROM DUAL UNION ALL
    SELECT 1056, 'ACTA DE FINIQUITO SUT',             7 FROM DUAL
) d;


-- =====================================================
-- PASO 3: RHH.SLOF - SALIDA OFICIAL GENERADA
-- =====================================================
CREATE TABLE RHH.SLOF (
    SLOFCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    -- FK a Empresa
    PJRQCDGO NUMBER NOT NULL,

    -- QUE SALIDA ES
    SLOFTPSL NUMBER NOT NULL,        -- Tipo de salida: detalle del rubro 223
    SLOFANOO NUMBER NOT NULL,        -- Ejercicio fiscal
    SLOFMESS NUMBER,                 -- Mes; nulo en las salidas anuales
    MPLDCDGO NUMBER,                 -- Empleado; nulo en las salidas consolidadas

    -- EL ARCHIVO
    SLOFRUTA VARCHAR2(500),          -- Ruta del archivo generado
    SLOFNMAR VARCHAR2(200),          -- Nombre del archivo
    SLOFHASH VARCHAR2(64),           -- SHA-256 del contenido generado
    SLOFFCGN DATE,                   -- Fecha de generacion

    -- LA PRESENTACION AL ORGANISMO
    SLOFFCPR DATE,                   -- Fecha en que se presento
    SLOFNRCM VARCHAR2(60),           -- Numero de comprobante devuelto por el organismo
    SLOFOBSR VARCHAR2(500),          -- Observaciones

    -- AUDITORIA
    SLOFESTD NUMBER DEFAULT 1,
    SLOFFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SLOFUSRR VARCHAR2(60),

    CONSTRAINT PK_SLOF PRIMARY KEY (SLOFCDGO),
    CONSTRAINT FK_SLOF_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_SLOF_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO)
);

-- Indice de busqueda e idempotencia. NO es unico a proposito: SLOFMESS y
-- MPLDCDGO son nulos en las salidas anuales y consolidadas, y Oracle no
-- considera duplicadas dos filas donde alguna columna de la clave es nula,
-- de modo que un UNIQUE no impediria nada justo en los casos que importan.
-- La idempotencia la resuelve el servicio: busca la salida del periodo y la
-- actualiza si existe.
CREATE INDEX IX_SLOF_BUSQ ON RHH.SLOF (PJRQCDGO, SLOFTPSL, SLOFANOO, SLOFMESS);
CREATE INDEX IX_SLOF_MPLD ON RHH.SLOF (MPLDCDGO);

COMMENT ON TABLE  RHH.SLOF IS 'Registro de cada salida oficial generada: RDEP, formulario 107, planilla IESS, formularios MDT y acta de finiquito. No duplica los datos --que ya viven en RNGL, ACMN y LQBS-- sino el hecho de la generacion y de la presentacion al organismo';
COMMENT ON COLUMN RHH.SLOF.SLOFCDGO IS 'Codigo de la salida oficial';
COMMENT ON COLUMN RHH.SLOF.PJRQCDGO IS 'Empresa a la que pertenece la salida';
COMMENT ON COLUMN RHH.SLOF.SLOFTPSL IS 'Tipo de salida: detalle del rubro RHH_TIPO_SALIDA_OFICIAL (223)';
COMMENT ON COLUMN RHH.SLOF.SLOFANOO IS 'Ejercicio fiscal al que corresponde la salida';
COMMENT ON COLUMN RHH.SLOF.SLOFMESS IS 'Mes al que corresponde la salida. Nulo en las salidas anuales como el RDEP';
COMMENT ON COLUMN RHH.SLOF.MPLDCDGO IS 'Empleado al que corresponde la salida. Nulo en las salidas consolidadas; informado en el formulario 107 y en el acta de finiquito';
COMMENT ON COLUMN RHH.SLOF.SLOFRUTA IS 'Ruta del archivo generado, bajo la raiz de saa.upload.dir';
COMMENT ON COLUMN RHH.SLOF.SLOFNMAR IS 'Nombre del archivo generado';
COMMENT ON COLUMN RHH.SLOF.SLOFHASH IS 'SHA-256 del contenido generado, para detectar que el archivo presentado no es el que produjo el sistema';
COMMENT ON COLUMN RHH.SLOF.SLOFFCGN IS 'Fecha en que el sistema genero el archivo';
COMMENT ON COLUMN RHH.SLOF.SLOFFCPR IS 'Fecha en que el archivo se presento al organismo de control. Nula mientras no se presente';
COMMENT ON COLUMN RHH.SLOF.SLOFNRCM IS 'Numero de comprobante o de tramite devuelto por el organismo al recibir la presentacion';
COMMENT ON COLUMN RHH.SLOF.SLOFOBSR IS 'Observaciones de la generacion o de la presentacion';
COMMENT ON COLUMN RHH.SLOF.SLOFESTD IS 'Estado del registro: 1 activo, 0 anulado';
COMMENT ON COLUMN RHH.SLOF.SLOFFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.SLOF.SLOFUSRR IS 'Usuario que registro';


-- =====================================================
-- PASO 4: ADELANTAR LAS SECUENCIAS DE RUBRO
-- =====================================================
ALTER SEQUENCE SCP.SQ_PRBRCDGO RESTART START WITH 225;
ALTER SEQUENCE SCP.SQ_PDTRCDGO RESTART START WITH 1057;

COMMIT;


-- =====================================================
-- VERIFICACION
-- =====================================================
-- 1) La cuenta marcadora quedo parametrizada (una fila por empresa, valor 9678):
-- SELECT PJRQCDGO, CFNMCTMR FROM RHH.CFNM;
--
-- 2) El rubro 223 tiene 7 detalles:
-- SELECT r.PRBRALTR, r.PRBRDSCR, COUNT(d.PDTRCDGO)
--   FROM SCP.PRBR r LEFT JOIN SCP.PDTR d ON d.PRBRCDGO = r.PRBRCDGO
--  WHERE r.PRBRALTR = 223 GROUP BY r.PRBRALTR, r.PRBRDSCR;
--
-- 3) SLOF existe y esta vacia:
-- SELECT COUNT(*) FROM RHH.SLOF;
--
-- 4) BARRIDO DE NOT NULL OCULTOS - hacerlo ahora, antes de que las fases 5 a 9
--    escriban en MRCC, RSMN, LQDC, TMLQ, RLPG, CRMR, RDPG, DRPG, UTLD y DTUT.
--    En este esquema los NOT NULL estan declarados como CHECK con nombre de
--    sistema, asi que all_tab_columns.nullable dice 'Y' y no sirve para auditar.
--    Es como se encontro el defecto de RBROCDGO que corrigio el script 12:
--
-- SELECT table_name, search_condition_vc FROM all_constraints
--  WHERE owner = 'RHH' AND constraint_type = 'C'
--    AND search_condition_vc LIKE '%NOT NULL%'
--    AND table_name IN ('MRCC','RSMN','LQDC','TMLQ','RLPG','CRMR','RDPG','DRPG','UTLD','DTUT')
--  ORDER BY table_name;
--
--    Contrastar cada columna obligatoria contra las que el codigo llena.
--    Cualquier columna obligatoria que ninguna entidad JPA mapee es un bloqueo
--    de insercion: reportarla ANTES de escribir el servicio que la usa.
