-- =====================================================
-- MODULO: RHH - FORMATO PARAMETRIZABLE DEL ARCHIVO BANCARIO
-- DESCRIPCION: RHH.FMBN y RHH.DFMB, el espejo de salida de FMRC/DFMR.
--              Cierra el hueco 1 reportado por el backend al entregar la
--              fase 6: generarArchivoBancario no tenia donde leer el formato
--              y lanzaba explicando que falta.
-- ORDEN DE EJECUCION: 14 (despues del 13)
-- PARAMETROS: ninguno
-- FECHA: 2026-08-19
-- =====================================================
-- DISENO
--   Misma filosofia que el importador de marcaciones: el formato es DATO.
--   Cuando el banco de ASOPREP entregue su especificacion, se crea un FMBN
--   con sus DFMB y no se toca codigo. Un segundo banco es otra fila.
--
--   La cabecera y el pie se definen como PLANTILLAS DE TEXTO con
--   marcadores, no como filas de detalle: los bancos los piden como lineas
--   literales con dos o tres valores incrustados, y una plantilla los
--   expresa sin duplicar la maquinaria de campos. Marcadores reconocidos:
--     {FECHA}      fecha de proceso, con el formato de FMBNFRFC
--     {CONTADOR}   numero de registros de detalle
--     {TOTAL}      suma de los valores, con el formato de importes
--     {EMPRESA}    nombre de la empresa
--     {SECUENCIAL} numero de la orden (RDPGNMRO)
--
--   El tipo de formato (ancho fijo / delimitado) REUTILIZA el rubro 209
--   RHH_FORMATO_ARCHIVO_MARCACION: es el mismo catalogo --el nombre quedo
--   corto de miras, describe cualquier archivo plano--. No se crea un
--   rubro gemelo con los mismos dos valores.
-- =====================================================


-- =====================================================
-- PASO 1: RUBRO 224 - CAMPO DEL ARCHIVO BANCARIO
-- =====================================================
-- Que dato va en cada campo del detalle. PK 225 = alterno 224.
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (225, 'RHH CAMPO DEL ARCHIVO BANCARIO', SYSDATE, 224, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRALTR, PDTRESTD)
SELECT d.CDGO, 225, d.DSCR, d.ALTR, 1 FROM (
    SELECT 1057 AS CDGO, 'SECUENCIAL'                 AS DSCR,  1 AS ALTR FROM DUAL UNION ALL
    SELECT 1058, 'IDENTIFICACION DEL BENEFICIARIO',  2 FROM DUAL UNION ALL
    SELECT 1059, 'NOMBRE DEL BENEFICIARIO',          3 FROM DUAL UNION ALL
    SELECT 1060, 'NUMERO DE CUENTA',                 4 FROM DUAL UNION ALL
    SELECT 1061, 'TIPO DE CUENTA',                   5 FROM DUAL UNION ALL
    SELECT 1062, 'CODIGO DEL BANCO',                 6 FROM DUAL UNION ALL
    SELECT 1063, 'VALOR',                            7 FROM DUAL UNION ALL
    SELECT 1064, 'MONEDA',                           8 FROM DUAL UNION ALL
    SELECT 1065, 'REFERENCIA',                       9 FROM DUAL UNION ALL
    SELECT 1066, 'FECHA DE PROCESO',                10 FROM DUAL UNION ALL
    SELECT 1067, 'LITERAL FIJO',                    11 FROM DUAL
) d;


-- =====================================================
-- PASO 2: RHH.FMBN - FORMATO DEL ARCHIVO BANCARIO
-- =====================================================
CREATE TABLE RHH.FMBN (
    FMBNCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    PJRQCDGO NUMBER NOT NULL,        -- FK a Empresa

    FMBNNMBR VARCHAR2(100) NOT NULL, -- Nombre del formato
    FMBNBNCO VARCHAR2(100),          -- Banco al que corresponde
    FMBNTPFR NUMBER NOT NULL,        -- Tipo: detalle del rubro 209 (1 ancho fijo, 2 delimitado)
    FMBNDLMT VARCHAR2(5),            -- Delimitador, cuando es delimitado
    FMBNEXTN VARCHAR2(10),           -- Extension del archivo (txt, csv, ...)
    FMBNCDFC VARCHAR2(20),           -- Codificacion (UTF-8, ISO-8859-1, ...)
    FMBNFRFC VARCHAR2(20),           -- Formato de fecha (ddMMyyyy, ...)
    FMBNCBCR VARCHAR2(1000),         -- Plantilla de la cabecera; nula = sin cabecera
    FMBNPIEE VARCHAR2(1000),         -- Plantilla del pie; nula = sin pie
    FMBNMPTC VARCHAR2(200),          -- Mapa de tipo de cuenta: alterno rubro 199=codigo banco (1=AH;2=CC)

    FMBNESTD NUMBER DEFAULT 1,
    FMBNFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FMBNUSRR VARCHAR2(60),

    CONSTRAINT PK_FMBN PRIMARY KEY (FMBNCDGO),
    CONSTRAINT FK_FMBN_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO)
);

CREATE INDEX IX_FMBN_PJRQ ON RHH.FMBN (PJRQCDGO);

COMMENT ON TABLE  RHH.FMBN IS 'Formato del archivo bancario de la orden de pago de nomina. Espejo de salida de FMRC: el formato del banco es dato, no codigo. La cabecera y el pie son plantillas con marcadores {FECHA} {CONTADOR} {TOTAL} {EMPRESA} {SECUENCIAL}';
COMMENT ON COLUMN RHH.FMBN.FMBNCDGO IS 'Codigo del formato';
COMMENT ON COLUMN RHH.FMBN.PJRQCDGO IS 'Empresa a la que pertenece el formato';
COMMENT ON COLUMN RHH.FMBN.FMBNNMBR IS 'Nombre del formato';
COMMENT ON COLUMN RHH.FMBN.FMBNBNCO IS 'Banco al que corresponde el formato';
COMMENT ON COLUMN RHH.FMBN.FMBNTPFR IS 'Tipo de formato: detalle del rubro RHH_FORMATO_ARCHIVO_MARCACION (209), que aplica a cualquier archivo plano: 1 ancho fijo, 2 delimitado';
COMMENT ON COLUMN RHH.FMBN.FMBNDLMT IS 'Caracter delimitador cuando el tipo es delimitado';
COMMENT ON COLUMN RHH.FMBN.FMBNEXTN IS 'Extension del archivo generado';
COMMENT ON COLUMN RHH.FMBN.FMBNCDFC IS 'Codificacion de caracteres del archivo generado';
COMMENT ON COLUMN RHH.FMBN.FMBNFRFC IS 'Formato de las fechas dentro del archivo, patron java.time';
COMMENT ON COLUMN RHH.FMBN.FMBNCBCR IS 'Plantilla de la linea de cabecera, con marcadores. Nula si el banco no pide cabecera';
COMMENT ON COLUMN RHH.FMBN.FMBNPIEE IS 'Plantilla de la linea de pie, con marcadores. Nula si el banco no pide pie';
COMMENT ON COLUMN RHH.FMBN.FMBNMPTC IS 'Mapa del tipo de cuenta al codigo del banco, formato alternoRubro199=codigo separado por punto y coma, p. ej. 1=AH;2=CC';
COMMENT ON COLUMN RHH.FMBN.FMBNESTD IS 'Estado del formato: 1 activo, 0 inactivo';
COMMENT ON COLUMN RHH.FMBN.FMBNFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.FMBN.FMBNUSRR IS 'Usuario que registro';


-- =====================================================
-- PASO 3: RHH.DFMB - DETALLE DEL FORMATO (CAMPOS DE LA LINEA DE DETALLE)
-- =====================================================
CREATE TABLE RHH.DFMB (
    DFMBCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    FMBNCDGO NUMBER NOT NULL,        -- FK al formato
    DFMBCMPO NUMBER NOT NULL,        -- Que dato va: detalle del rubro 224
    DFMBORDN NUMBER NOT NULL,        -- Orden del campo dentro de la linea
    DFMBINCO NUMBER,                 -- Posicion de inicio (ancho fijo), base 1
    DFMBLNGT NUMBER,                 -- Longitud (ancho fijo)
    DFMBRLLN VARCHAR2(1),            -- Lado del relleno: I izquierda, D derecha
    DFMBCRLL VARCHAR2(1),            -- Caracter de relleno (0, espacio, ...)
    DFMBDCML NUMBER,                 -- Numero de decimales del importe
    DFMBSPDC VARCHAR2(1) DEFAULT 'N',-- Incluye separador decimal (S/N)
    DFMBFRFC VARCHAR2(20),           -- Formato de fecha propio del campo; nulo = el de FMBN
    DFMBVLFJ VARCHAR2(100),          -- Valor cuando el campo es LITERAL FIJO

    DFMBESTD NUMBER DEFAULT 1,
    DFMBFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DFMBUSRR VARCHAR2(60),

    CONSTRAINT PK_DFMB PRIMARY KEY (DFMBCDGO),
    CONSTRAINT FK_DFMB_FMBN FOREIGN KEY (FMBNCDGO) REFERENCES RHH.FMBN(FMBNCDGO),
    CONSTRAINT UQ_DFMB_ORDN UNIQUE (FMBNCDGO, DFMBORDN)
);

COMMENT ON TABLE  RHH.DFMB IS 'Campos de la linea de detalle del archivo bancario, uno por columna del archivo, en el orden en que se escriben';
COMMENT ON COLUMN RHH.DFMB.DFMBCDGO IS 'Codigo del campo';
COMMENT ON COLUMN RHH.DFMB.FMBNCDGO IS 'Formato al que pertenece el campo';
COMMENT ON COLUMN RHH.DFMB.DFMBCMPO IS 'Dato que va en el campo: detalle del rubro RHH_CAMPO_ARCHIVO_BANCARIO (224)';
COMMENT ON COLUMN RHH.DFMB.DFMBORDN IS 'Orden del campo dentro de la linea de detalle';
COMMENT ON COLUMN RHH.DFMB.DFMBINCO IS 'Posicion de inicio del campo en formato de ancho fijo, base 1';
COMMENT ON COLUMN RHH.DFMB.DFMBLNGT IS 'Longitud del campo en formato de ancho fijo';
COMMENT ON COLUMN RHH.DFMB.DFMBRLLN IS 'Lado del relleno hasta la longitud: I izquierda, D derecha';
COMMENT ON COLUMN RHH.DFMB.DFMBCRLL IS 'Caracter con el que se rellena';
COMMENT ON COLUMN RHH.DFMB.DFMBDCML IS 'Decimales del importe cuando el campo es VALOR o TOTAL';
COMMENT ON COLUMN RHH.DFMB.DFMBSPDC IS 'Indica si el importe lleva separador decimal (S) o va en centavos corridos (N)';
COMMENT ON COLUMN RHH.DFMB.DFMBFRFC IS 'Formato de fecha propio del campo; nulo usa el general del formato';
COMMENT ON COLUMN RHH.DFMB.DFMBVLFJ IS 'Texto literal cuando el campo es LITERAL FIJO';
COMMENT ON COLUMN RHH.DFMB.DFMBESTD IS 'Estado del campo: 1 activo, 0 inactivo';
COMMENT ON COLUMN RHH.DFMB.DFMBFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.DFMB.DFMBUSRR IS 'Usuario que registro';


-- =====================================================
-- PASO 4: LA FK QUE EL SCRIPT 04 NO DECLARO
-- =====================================================
-- RDPG.CTBNCDGO apunta a TSR.CNBC (PK CNBCCDGO) solo por comentario. La
-- entidad ya lo resuelve con referencedColumnName; la base debe decirlo
-- tambien.
ALTER TABLE RHH.RDPG ADD CONSTRAINT FK_RDPG_CNBC
    FOREIGN KEY (CTBNCDGO) REFERENCES TSR.CNBC(CNBCCDGO);
CREATE INDEX IX_RDPG_CNBC ON RHH.RDPG (CTBNCDGO);


-- =====================================================
-- PASO 5: ADELANTAR LAS SECUENCIAS DE RUBRO
-- =====================================================
ALTER SEQUENCE SCP.SQ_PRBRCDGO RESTART START WITH 226;
ALTER SEQUENCE SCP.SQ_PDTRCDGO RESTART START WITH 1068;

COMMIT;


-- =====================================================
-- VERIFICACION
-- =====================================================
-- 1) El rubro 224 tiene 11 detalles:
-- SELECT r.PRBRALTR, COUNT(*) FROM SCP.PRBR r JOIN SCP.PDTR d ON d.PRBRCDGO = r.PRBRCDGO
--  WHERE r.PRBRALTR = 224 GROUP BY r.PRBRALTR;
--
-- 2) Las dos tablas existen y estan vacias:
-- SELECT (SELECT COUNT(*) FROM RHH.FMBN) FMBN, (SELECT COUNT(*) FROM RHH.DFMB) DFMB FROM DUAL;
--
-- 3) La FK nueva de RDPG:
-- SELECT constraint_name FROM all_constraints
--  WHERE owner = 'RHH' AND table_name = 'RDPG' AND constraint_name = 'FK_RDPG_CNBC';
--
-- 4) PARA EL HUECO DEL EGRESO (decision aparte): confirmar si TSR.EGRS
--    permite titular y producto en nulo. El Javadoc de Egreso declara el
--    titular opcional; falta ver la base:
-- SELECT column_name, nullable FROM all_tab_columns
--  WHERE owner = 'TSR' AND table_name = 'EGRS'
--    AND column_name IN ('EGRSTTLR','EGRSPRDP');
