-- =====================================================
-- MODULO: RHH - VALORES ESPERADOS DE ENERO 2026, DEL ROL Y DE LA PLANILLA
-- DESCRIPCION: Carga RHH.CTRL con lo que ASOPREP pago y lo que el IESS
--              cobro, para que CONTRASTE_MES_CONTRA_ROL_REAL.sql tenga
--              contra que comparar.
-- ORDEN DE EJECUCION: 31
-- FECHA: 2026-08-20
-- =====================================================
-- LA REGLA 6, QUE ES LA RAZON DE ESTE ARCHIVO
--   Ningun numero de aqui sale de un calculo nuestro. Vienen de la hoja
--   ENERO del libro ROL ENERO 2026.xlsb y de la planilla del IESS del
--   periodo 2026-01, transcritos en REF-02 §7 y REF-03 §1.5.
--
--   Si los calcularamos con nuestros parametros, la comparacion se cuadraria
--   a si misma y no seria un control. Por eso CTRLFNTE guarda el origen de
--   cada fila: ROL o PLANILLA.
--
-- LO QUE SE CARGA, Y LO QUE NO
--   Se cargan los conceptos que el rol de enero trae con valor, y los cinco
--   totales. **No se cargan los ceros**: una columna vacia en el rol no es
--   una afirmacion del cliente, y cargarla como 0,00 convertiria un silencio
--   en un dato. El FULL OUTER JOIN del contraste ya destapa lo que nosotros
--   generemos de mas.
--
-- LAS TRES DIFERENCIAS QUE VAN A SALIR, Y NO SON DEFECTOS
--   Estan documentadas en PLAN-CARGA-HISTORICA-ASOPREP.md. Se cargan los
--   valores del cliente **tal cual**, sin ajustar, porque ajustar el valor
--   externo para que cuadre con el nuestro es exactamente lo que la regla 6
--   prohibe:
--
--   1. **El par de VACACIONES.** El rol de enero lleva 823,19 como ingreso y
--      823,19 como descuento, a las 22 personas: es presentacion de la
--      provision y netea a cero. Nuestro motor produce una provision
--      (CPNMALTR 52), no el par. Van a salir dos diferencias de 823,19 en
--      INGRESOS y DESCUENTOS que se cancelan en LIQUIDO.
--   2. **Los dias de Mendez Torres.** El rol dice 15, calculaDiasTrabajados
--      va a decir 30. El importe -- 241,00 -- si cuadra.
--   3. **La cedula de Bravo Caiza.** Aqui va la correcta, 2150051205, la del
--      aviso al IESS. Las hojas de rol traen 1714531405, que es la de
--      Benitez Montes.
--
-- POR QUE TORRES CHAVEZ Y BENITEZ MONTES NO ESTAN EN EL ROL
--   Salieron el 15 y el 16 de enero y se les pago por finiquito, no por rol.
--   Sus 22 companeros si estan. Pero **si estan en la planilla del IESS**,
--   con 1.000,00 y 373,33 -- por eso el bloque de PLANILLA tiene 24 filas y
--   el de ROL 22. Esa asimetria es correcta y es la que explica la
--   diferencia de 1.373,33 entre las dos masas.
-- =====================================================


-- =====================================================
-- PASO 0: CREAR LA TABLA SI NO EXISTE
-- =====================================================
-- El contrato es el del paso 0 de CONTRASTE_MES_CONTRA_ROL_REAL.sql.
-- Descomentar solo la primera vez.
/*
CREATE TABLE RHH.CTRL (
    CTRLCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CTRLANOO NUMBER NOT NULL,
    CTRLMESS NUMBER NOT NULL,
    CTRLIDNT VARCHAR2(20) NOT NULL,
    CTRLALTR NUMBER,
    CTRLTOTL VARCHAR2(20),
    CTRLVLOR NUMBER(18,2) NOT NULL,
    CTRLFNTE VARCHAR2(20) NOT NULL,
    CTRLFCHR DATE DEFAULT SYSDATE,
    CTRLUSRR VARCHAR2(60),
    CONSTRAINT PK_CTRL PRIMARY KEY (CTRLCDGO),
    CONSTRAINT CK_CTRL_UNO CHECK ((CTRLALTR IS NULL) <> (CTRLTOTL IS NULL))
);
CREATE INDEX IX_CTRL_BUSQ ON RHH.CTRL (CTRLANOO, CTRLMESS, CTRLIDNT);
COMMENT ON TABLE RHH.CTRL IS 'Valores esperados del rol real y de la planilla del IESS. NO se deriva de ningun calculo del sistema';
*/

-- Repetible: borra lo de este mes antes de recargar.
DELETE FROM RHH.CTRL WHERE CTRLANOO = 2026 AND CTRLMESS = 1;


-- =====================================================
-- EL ROL DE ENERO -- hoja ENERO, 22 trabajadores
-- =====================================================
-- Columnas del rol -> CPNMALTR:
--   RMU              ->  1   Sueldo
--   VACACIONES       -> (par ingreso/descuento, ver arriba: no se carga
--                        como concepto, solo dentro de los totales)
--   DM 13er.         ->  5   Decimo tercero mensualizado
--   DM 14to.         ->  6   Decimo cuarto mensualizado
--   APORTE PERSONAL  -> 20   Aporte personal IESS
--   PRT QUIROG       -> 23   Prestamo quirografario IESS
--   PRT HIPOT        -> 24   Prestamo hipotecario IESS
--   ANTIC SUELD      -> 25   Anticipo de sueldo
INSERT INTO RHH.CTRL (CTRLANOO, CTRLMESS, CTRLIDNT, CTRLALTR, CTRLVLOR, CTRLFNTE, CTRLUSRR)
SELECT 2026, 1, d.CED, d.ALTR, d.VLOR, 'ROL', 'CARGA' FROM (
    -- Sueldo (concepto 1)
    SELECT '1717991341' CED, 1 ALTR,  700.00 VLOR FROM DUAL UNION ALL
    SELECT '2150051205', 1,  373.33 FROM DUAL UNION ALL
    SELECT '1753528379', 1,  482.00 FROM DUAL UNION ALL
    SELECT '1719624809', 1,  700.00 FROM DUAL UNION ALL
    SELECT '1720245735', 1,  482.00 FROM DUAL UNION ALL
    SELECT '1716501778', 1,  482.00 FROM DUAL UNION ALL
    SELECT '1311981953', 1,  800.00 FROM DUAL UNION ALL
    SELECT '1715156574', 1,  700.00 FROM DUAL UNION ALL
    SELECT '1750302984', 1,  700.00 FROM DUAL UNION ALL
    SELECT '1716120769', 1, 2000.00 FROM DUAL UNION ALL
    SELECT '1004350904', 1,  241.00 FROM DUAL UNION ALL
    SELECT '0103179537', 1, 1546.00 FROM DUAL UNION ALL
    SELECT '1717649873', 1,  550.00 FROM DUAL UNION ALL
    SELECT '1723962849', 1,  900.00 FROM DUAL UNION ALL
    SELECT '1726657164', 1,  700.00 FROM DUAL UNION ALL
    SELECT '0909917759', 1, 1500.00 FROM DUAL UNION ALL
    SELECT '2100192463', 1,  500.00 FROM DUAL UNION ALL
    SELECT '1725996498', 1, 1500.00 FROM DUAL UNION ALL
    SELECT '0801999855', 1,  700.00 FROM DUAL UNION ALL
    SELECT '1712362720', 1, 1500.00 FROM DUAL UNION ALL
    SELECT '1712232659', 1, 2200.00 FROM DUAL UNION ALL
    SELECT '1307779064', 1,  500.00 FROM DUAL UNION ALL
    -- Decimo tercero mensualizado (concepto 5) - solo los tres MENSUAL
    SELECT '1715156574', 5,   58.33 FROM DUAL UNION ALL
    SELECT '1716120769', 5,  166.67 FROM DUAL UNION ALL
    SELECT '0103179537', 5,  128.83 FROM DUAL UNION ALL
    -- Decimo cuarto mensualizado (concepto 6) - los mismos tres
    SELECT '1715156574', 6,   40.17 FROM DUAL UNION ALL
    SELECT '1716120769', 6,   40.17 FROM DUAL UNION ALL
    SELECT '0103179537', 6,   40.17 FROM DUAL UNION ALL
    -- Aporte personal IESS 9,45% (concepto 20) - los 22
    SELECT '1717991341', 20,  66.15 FROM DUAL UNION ALL
    SELECT '2150051205', 20,  35.28 FROM DUAL UNION ALL
    SELECT '1753528379', 20,  45.55 FROM DUAL UNION ALL
    SELECT '1719624809', 20,  66.15 FROM DUAL UNION ALL
    SELECT '1720245735', 20,  45.55 FROM DUAL UNION ALL
    SELECT '1716501778', 20,  45.55 FROM DUAL UNION ALL
    SELECT '1311981953', 20,  75.60 FROM DUAL UNION ALL
    SELECT '1715156574', 20,  66.15 FROM DUAL UNION ALL
    SELECT '1750302984', 20,  66.15 FROM DUAL UNION ALL
    SELECT '1716120769', 20, 189.00 FROM DUAL UNION ALL
    SELECT '1004350904', 20,  22.77 FROM DUAL UNION ALL
    SELECT '0103179537', 20, 146.10 FROM DUAL UNION ALL
    SELECT '1717649873', 20,  51.97 FROM DUAL UNION ALL
    SELECT '1723962849', 20,  85.05 FROM DUAL UNION ALL
    SELECT '1726657164', 20,  66.15 FROM DUAL UNION ALL
    SELECT '0909917759', 20, 141.75 FROM DUAL UNION ALL
    SELECT '2100192463', 20,  47.25 FROM DUAL UNION ALL
    SELECT '1725996498', 20, 141.75 FROM DUAL UNION ALL
    SELECT '0801999855', 20,  66.15 FROM DUAL UNION ALL
    SELECT '1712362720', 20, 141.75 FROM DUAL UNION ALL
    SELECT '1712232659', 20, 207.90 FROM DUAL UNION ALL
    SELECT '1307779064', 20,  47.25 FROM DUAL UNION ALL
    -- Prestamo quirografario IESS (concepto 23)
    SELECT '1719624809', 23,  14.42 FROM DUAL UNION ALL
    SELECT '1716120769', 23, 157.21 FROM DUAL UNION ALL
    -- Prestamo hipotecario IESS (concepto 24)
    SELECT '1715156574', 24, 490.00 FROM DUAL UNION ALL
    SELECT '1716120769', 24, 379.85 FROM DUAL UNION ALL
    SELECT '0909917759', 24, 145.29 FROM DUAL UNION ALL
    -- Anticipo de sueldo (concepto 25)
    SELECT '1719624809', 25, 350.00 FROM DUAL UNION ALL
    SELECT '1726657164', 25, 350.00 FROM DUAL
) d;


-- =====================================================
-- LOS TOTALES DE CABECERA, DEL ROL
-- =====================================================
-- INGRESOS y DESCUENTOS van **con las vacaciones dentro**, tal como el rol
-- las pago: 823,19 en cada lado. La diferencia contra lo nuestro va a salir
-- y es la documentada en el §4.1 del plan.
INSERT INTO RHH.CTRL (CTRLANOO, CTRLMESS, CTRLIDNT, CTRLTOTL, CTRLVLOR, CTRLFNTE, CTRLUSRR)
SELECT 2026, 1, d.CED, d.TOTL, d.VLOR, 'ROL', 'CARGA' FROM (
    SELECT '1717991341' CED, 'INGRESOS' TOTL,  729.17 VLOR FROM DUAL UNION ALL
    SELECT '1717991341', 'DESCUENTOS',   95.32 FROM DUAL UNION ALL
    SELECT '1717991341', 'LIQUIDO',     633.85 FROM DUAL UNION ALL
    SELECT '2150051205', 'INGRESOS',    388.89 FROM DUAL UNION ALL
    SELECT '2150051205', 'DESCUENTOS',   50.84 FROM DUAL UNION ALL
    SELECT '2150051205', 'LIQUIDO',     338.05 FROM DUAL UNION ALL
    SELECT '1753528379', 'INGRESOS',    502.08 FROM DUAL UNION ALL
    SELECT '1753528379', 'DESCUENTOS',   65.63 FROM DUAL UNION ALL
    SELECT '1753528379', 'LIQUIDO',     436.45 FROM DUAL UNION ALL
    SELECT '1719624809', 'INGRESOS',    729.17 FROM DUAL UNION ALL
    SELECT '1719624809', 'DESCUENTOS',  459.74 FROM DUAL UNION ALL
    SELECT '1719624809', 'LIQUIDO',     269.43 FROM DUAL UNION ALL
    SELECT '1720245735', 'INGRESOS',    502.08 FROM DUAL UNION ALL
    SELECT '1720245735', 'DESCUENTOS',   65.63 FROM DUAL UNION ALL
    SELECT '1720245735', 'LIQUIDO',     436.45 FROM DUAL UNION ALL
    SELECT '1716501778', 'INGRESOS',    502.08 FROM DUAL UNION ALL
    SELECT '1716501778', 'DESCUENTOS',   65.63 FROM DUAL UNION ALL
    SELECT '1716501778', 'LIQUIDO',     436.45 FROM DUAL UNION ALL
    SELECT '1311981953', 'INGRESOS',    833.33 FROM DUAL UNION ALL
    SELECT '1311981953', 'DESCUENTOS',  108.93 FROM DUAL UNION ALL
    SELECT '1311981953', 'LIQUIDO',     724.40 FROM DUAL UNION ALL
    SELECT '1715156574', 'INGRESOS',    827.67 FROM DUAL UNION ALL
    SELECT '1715156574', 'DESCUENTOS',  585.32 FROM DUAL UNION ALL
    SELECT '1715156574', 'LIQUIDO',     242.35 FROM DUAL UNION ALL
    SELECT '1750302984', 'INGRESOS',    729.17 FROM DUAL UNION ALL
    SELECT '1750302984', 'DESCUENTOS',   95.32 FROM DUAL UNION ALL
    SELECT '1750302984', 'LIQUIDO',     633.85 FROM DUAL UNION ALL
    SELECT '1716120769', 'INGRESOS',   2290.17 FROM DUAL UNION ALL
    SELECT '1716120769', 'DESCUENTOS',  809.39 FROM DUAL UNION ALL
    SELECT '1716120769', 'LIQUIDO',    1480.77 FROM DUAL UNION ALL
    SELECT '1004350904', 'INGRESOS',    251.04 FROM DUAL UNION ALL
    SELECT '1004350904', 'DESCUENTOS',   32.82 FROM DUAL UNION ALL
    SELECT '1004350904', 'LIQUIDO',     218.23 FROM DUAL UNION ALL
    SELECT '0103179537', 'INGRESOS',   1779.42 FROM DUAL UNION ALL
    SELECT '0103179537', 'DESCUENTOS',  210.51 FROM DUAL UNION ALL
    SELECT '0103179537', 'LIQUIDO',    1568.90 FROM DUAL UNION ALL
    SELECT '1717649873', 'INGRESOS',    572.92 FROM DUAL UNION ALL
    SELECT '1717649873', 'DESCUENTOS',   74.89 FROM DUAL UNION ALL
    SELECT '1717649873', 'LIQUIDO',     498.02 FROM DUAL UNION ALL
    SELECT '1723962849', 'INGRESOS',    937.50 FROM DUAL UNION ALL
    SELECT '1723962849', 'DESCUENTOS',  122.55 FROM DUAL UNION ALL
    SELECT '1723962849', 'LIQUIDO',     814.95 FROM DUAL UNION ALL
    SELECT '1726657164', 'INGRESOS',    729.17 FROM DUAL UNION ALL
    SELECT '1726657164', 'DESCUENTOS',  445.32 FROM DUAL UNION ALL
    SELECT '1726657164', 'LIQUIDO',     283.85 FROM DUAL UNION ALL
    SELECT '0909917759', 'INGRESOS',   1562.50 FROM DUAL UNION ALL
    SELECT '0909917759', 'DESCUENTOS',  349.54 FROM DUAL UNION ALL
    SELECT '0909917759', 'LIQUIDO',    1212.96 FROM DUAL UNION ALL
    SELECT '2100192463', 'INGRESOS',    520.83 FROM DUAL UNION ALL
    SELECT '2100192463', 'DESCUENTOS',   68.08 FROM DUAL UNION ALL
    SELECT '2100192463', 'LIQUIDO',     452.75 FROM DUAL UNION ALL
    SELECT '1725996498', 'INGRESOS',   1562.50 FROM DUAL UNION ALL
    SELECT '1725996498', 'DESCUENTOS',  204.25 FROM DUAL UNION ALL
    SELECT '1725996498', 'LIQUIDO',    1358.25 FROM DUAL UNION ALL
    SELECT '0801999855', 'INGRESOS',    729.17 FROM DUAL UNION ALL
    SELECT '0801999855', 'DESCUENTOS',   95.32 FROM DUAL UNION ALL
    SELECT '0801999855', 'LIQUIDO',     633.85 FROM DUAL UNION ALL
    SELECT '1712362720', 'INGRESOS',   1562.50 FROM DUAL UNION ALL
    SELECT '1712362720', 'DESCUENTOS',  204.25 FROM DUAL UNION ALL
    SELECT '1712362720', 'LIQUIDO',    1358.25 FROM DUAL UNION ALL
    SELECT '1712232659', 'INGRESOS',   2291.67 FROM DUAL UNION ALL
    SELECT '1712232659', 'DESCUENTOS',  299.57 FROM DUAL UNION ALL
    SELECT '1712232659', 'LIQUIDO',    1992.10 FROM DUAL UNION ALL
    SELECT '1307779064', 'INGRESOS',    520.83 FROM DUAL UNION ALL
    SELECT '1307779064', 'DESCUENTOS',   68.08 FROM DUAL UNION ALL
    SELECT '1307779064', 'LIQUIDO',     452.75 FROM DUAL
) d;


-- =====================================================
-- EL CONTROL 2: LA PLANILLA DEL IESS DEL PERIODO 2026-01
-- =====================================================
-- TOTAL_IESS = SUELDO x 20,60 % (aporte personal 9,45 + patronal 11,15).
-- **No incluye el 1 % de CCC**, que en la planilla va aparte y en nuestro
-- modelo es IECE + SECAP.
--
-- Son 24 filas y no 22: Torres Chavez y Benitez Montes salieron a mitad de
-- mes y se les pago por finiquito, asi que no estan en el rol pero SI en la
-- planilla, con 1.000,00 y 373,33. Esa asimetria explica la diferencia de
-- 1.373,33 entre las dos masas salariales.
INSERT INTO RHH.CTRL (CTRLANOO, CTRLMESS, CTRLIDNT, CTRLTOTL, CTRLVLOR, CTRLFNTE, CTRLUSRR)
SELECT 2026, 1, d.CED, 'TOTAL_IESS', ROUND(d.SLDO * 0.206, 2), 'PLANILLA', 'CARGA' FROM (
    SELECT '1717991341' CED,  700.00 SLDO FROM DUAL UNION ALL
    SELECT '1714531405',      373.33 FROM DUAL UNION ALL   -- Benitez Montes
    SELECT '2150051205',      373.33 FROM DUAL UNION ALL   -- Bravo Caiza
    SELECT '1753528379',      482.00 FROM DUAL UNION ALL
    SELECT '1719624809',      700.00 FROM DUAL UNION ALL
    SELECT '1720245735',      482.00 FROM DUAL UNION ALL
    SELECT '1716501778',      482.00 FROM DUAL UNION ALL
    SELECT '1311981953',      800.00 FROM DUAL UNION ALL
    SELECT '1715156574',      700.00 FROM DUAL UNION ALL
    SELECT '1750302984',      700.00 FROM DUAL UNION ALL
    SELECT '1716120769',     2000.00 FROM DUAL UNION ALL
    SELECT '1004350904',      241.00 FROM DUAL UNION ALL
    SELECT '0103179537',     1546.00 FROM DUAL UNION ALL
    SELECT '1717649873',      550.00 FROM DUAL UNION ALL
    SELECT '1723962849',      900.00 FROM DUAL UNION ALL
    SELECT '1726657164',      700.00 FROM DUAL UNION ALL
    SELECT '0909917759',     1500.00 FROM DUAL UNION ALL
    SELECT '2100192463',      500.00 FROM DUAL UNION ALL
    SELECT '1725996498',     1500.00 FROM DUAL UNION ALL
    SELECT '0801999855',      700.00 FROM DUAL UNION ALL
    SELECT '1712362720',     1500.00 FROM DUAL UNION ALL
    SELECT '0602237265',     1000.00 FROM DUAL UNION ALL   -- Torres Chavez
    SELECT '1712232659',     2200.00 FROM DUAL UNION ALL
    SELECT '1307779064',      500.00 FROM DUAL
) d;

COMMIT;


-- =====================================================
-- COMPROBACION DE LA CARGA -- contra los totales del cliente
-- =====================================================
SELECT CTRLFNTE, COUNT(*) AS FILAS, COUNT(DISTINCT CTRLIDNT) AS PERSONAS
  FROM RHH.CTRL WHERE CTRLANOO = 2026 AND CTRLMESS = 1
 GROUP BY CTRLFNTE ORDER BY CTRLFNTE;
-- Esperado: PLANILLA 24 filas / 24 personas · ROL 123 filas / 22 personas
--   (123 = 57 conceptos + 66 totales; los conceptos son 22 sueldos, 3 y 3
--    decimos, 22 aportes, 2 quirografarios, 3 hipotecarios y 2 anticipos)

-- Los totales del rol, que tienen que dar los del libro:
SELECT CTRLTOTL, ROUND(SUM(CTRLVLOR), 2) AS TOTAL
  FROM RHH.CTRL WHERE CTRLANOO = 2026 AND CTRLMESS = 1 AND CTRLFNTE = 'ROL'
   AND CTRLTOTL IS NOT NULL
 GROUP BY CTRLTOTL ORDER BY CTRLTOTL;
-- Esperado: DESCUENTOS 4.576,93 · INGRESOS 21.053,86 · LIQUIDO 16.476,91

-- Y los conceptos, contra las columnas del rol:
SELECT CTRLALTR, ROUND(SUM(CTRLVLOR), 2) AS TOTAL, COUNT(*) AS PERSONAS
  FROM RHH.CTRL WHERE CTRLANOO = 2026 AND CTRLMESS = 1 AND CTRLALTR IS NOT NULL
 GROUP BY CTRLALTR ORDER BY CTRLALTR;
-- Esperado:  1 -> 19.756,33 / 22   (RMU)
--            5 ->    353,83 /  3   (DM 13er, los tres mensualizados)
--            6 ->    120,51 /  3   (DM 14to)
--           20 ->  1.866,97 / 22   (aporte personal)
--           23 ->    171,63 /  2   (quirografarios, cuadra con el IESS)
--           24 ->  1.015,14 /  3   (hipotecarios, cuadra con el IESS)
--           25 ->    700,00 /  2   (anticipos)

-- El control 2, que es el que manda:
SELECT ROUND(SUM(CTRLVLOR), 2) AS TOTAL_IESS_PLANILLA
  FROM RHH.CTRL WHERE CTRLANOO = 2026 AND CTRLMESS = 1 AND CTRLTOTL = 'TOTAL_IESS';
-- Esperado: 4.352,72 -- el aporte del 20,60 % del comprobante del IESS.


-- =====================================================
-- LO QUE FALTA PARA CONTRASTAR
-- =====================================================
-- 1. Las dos liquidaciones de enero, por pantalla.
-- 2. Calcular el periodo de enero.
-- 3. Correr CONTRASTE_MES_CONTRA_ROL_REAL.sql con ANIO=2026 y MES=1.
--
-- Y mirar el bloque 4 ANTES que los otros: una consulta de diferencias vacia
-- solo significa «no hay diferencias» si de verdad se comparo algo.
