-- =====================================================
-- MODULO: RHH - INSTRUMENTO DE CONTRASTE DE LA CALIBRACION
-- DESCRIPCION: Enfrenta lo que calculo el sistema contra lo que ASOPREP pago
--              de verdad, persona por persona y concepto por concepto, y
--              SOLO SACA LAS DIFERENCIAS. Si el mes cuadra, sale vacio.
-- FECHA: 2026-08-20 - Solo consulta: no modifica nada.
-- =====================================================
-- POR QUE EXISTE
--   Contrastar 22 personas contra el rol real leyendo una tabla de 24
--   columnas es como se cuela un descuadre de dos dolares que nadie ve. Y
--   hay que hacerlo seis veces, una por mes.
--
-- DOS REGLAS DE DISENO, LAS DOS DE LA REGLA 6 DEL MAESTRO
--   1. LOS VALORES ESPERADOS NO SE DERIVAN DE NADA NUESTRO. Salen del rol
--      que ASOPREP pago y de la planilla que el IESS cobro. Calcularlos con
--      nuestros propios parametros haria que la comparacion se cuadrara a si
--      misma: seria el motor confirmandose, no un control.
--   2. NO SE REDONDEA NI SE AGRUPA PARA CUADRAR. La consulta muestra lo que
--      hay. Las diferencias que YA SABEMOS que van a salir --los 30 dias de
--      Mendez Torres en vez de 15, y el ajuste manual de 0,10 de Calderon en
--      junio y julio-- se reconocen leyendolas, no escondiendolas bajo una
--      tolerancia. Una tolerancia que tapa una diferencia conocida tapa
--      tambien la que no conocemos.
--
--   No hace falta redondear para comparar: las columnas son NUMBER(18,2) y
--   Oracle guarda decimal exacto, asi que cualquier diferencia que salga es
--   real y no un artefacto de coma flotante.
--
-- LO QUE NO ES
--   No es un "cuadro si / cuadro no". Una fila de salida no significa que el
--   sistema este mal: significa que hay que mirar cual de los dos lados lo
--   esta. En marzo y en abril el sistema DEBE discrepar de la planilla, y una
--   coincidencia seria el error.
--
-- ORDEN DE LECTURA
--   BLOQUE 4 PRIMERO, siempre. Los bloques de diferencias vacios solo
--   significan "no hay diferencias" si de verdad se comparo algo; con la
--   tabla de contraste sin cargar salen vacios y parecen un exito.
--   Despues el 3 --el control que manda--, despues el 1 y el 2, y el 1B se
--   mira aunque todo cuadre.
--
-- QUE SALE VACIO Y QUE NO
--   Bloques 1, 2, 3 y el descuadre patronal del 1B: VACIOS si el mes cuadra.
--   Bloques 1B y 4: SALEN SIEMPRE, son informativos.
-- =====================================================


-- =====================================================
-- PASO 0: LA TABLA DE CONTRASTE - contrato de carga
-- =====================================================
-- Se carga desde el rol real y desde la planilla, un mes cada vez. Sobrevive
-- entre meses: ANIO y MES la particionan.
--
-- EXACTAMENTE UNA de CTRLALTR y CTRLTOTL viene informada en cada fila:
--   - CTRLALTR : codigo alterno de RHH.CPNM (CPNMALTR). Es la clave estable
--                de un concepto, la misma que usan los DTO. Una fila por
--                persona y concepto.
--   - CTRLTOTL : para lo que no es un renglon sino un total de la cabecera.
--                Palabras reservadas, sin inventar otras:
--                  INGRESOS   -> NMNATING
--                  DESCUENTOS -> NMNATDSC
--                  LIQUIDO    -> NMNANETO
--                  DIAS       -> NMNADITR
--                  TOTAL_IESS -> NMNAAPPR + NMNAAPPT   (control 2)
--
-- CTRLFNTE deja escrito de donde salio el numero, que es lo que hace que la
-- regla 6 se pueda auditar despues: ROL o PLANILLA.
--
/*
CREATE TABLE RHH.CTRL (
    CTRLCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CTRLANOO NUMBER NOT NULL,          -- Anio del periodo contrastado
    CTRLMESS NUMBER NOT NULL,          -- Mes del periodo contrastado
    CTRLIDNT VARCHAR2(20) NOT NULL,    -- Identificacion del empleado
    CTRLALTR NUMBER,                   -- CPNMALTR del concepto, o nulo si es un total
    CTRLTOTL VARCHAR2(20),             -- Palabra reservada del total, o nulo si es un concepto
    CTRLVLOR NUMBER(18,2) NOT NULL,    -- El valor que el cliente pago o el IESS cobro
    CTRLFNTE VARCHAR2(20) NOT NULL,    -- ROL o PLANILLA
    CTRLFCHR DATE DEFAULT SYSDATE,
    CTRLUSRR VARCHAR2(60),
    CONSTRAINT PK_CTRL PRIMARY KEY (CTRLCDGO),
    CONSTRAINT CK_CTRL_UNO CHECK ((CTRLALTR IS NULL) <> (CTRLTOTL IS NULL))
);
CREATE INDEX IX_CTRL_BUSQ ON RHH.CTRL (CTRLANOO, CTRLMESS, CTRLIDNT);
COMMENT ON TABLE  RHH.CTRL IS 'Valores esperados del rol real y de la planilla del IESS, para contrastar la calibracion. NO se deriva de ningun calculo del sistema';
*/
--
-- El CHECK CK_CTRL_UNO es el que impide la fila ambigua: exactamente una de
-- las dos claves informada. Sin el, una fila con las dos aparece dos veces en
-- la salida y una con ninguna no aparece nunca.
--
-- OJO: no nombrar CTRLFCHR en el INSERT. Tiene DEFAULT SYSDATE y, si el
-- esquema le pone ademas un CHECK NOT NULL como al resto, nombrarla con nulo
-- explicito la hace fallar. Es la mina de PRDNFCHR.


-- =====================================================
-- PARAMETROS
-- =====================================================
-- Una tabla de UNA fila con el mes a contrastar. Se cambia con un UPDATE y
-- todas las consultas la leen por JOIN. Funciona igual en SQL Developer,
-- DBeaver, sqlplus o JDBC: no depende de variables de sustitucion (&ANIO),
-- que solo entiende SQL*Plus y que en DBeaver dan "Index 0 out of bounds".
--
-- Primera vez:
--   CREATE TABLE RHH.CTRL_PARAM (ANIO NUMBER NOT NULL, MES NUMBER NOT NULL);
--   INSERT INTO RHH.CTRL_PARAM VALUES (2026, 1);
--   COMMIT;
-- Cada mes:
--   UPDATE RHH.CTRL_PARAM SET ANIO = 2026, MES = 2;  COMMIT;
--
-- Comprobar antes de correr nada:
SELECT ANIO, MES, SYSTIMESTAMP AS MOMENTO FROM RHH.CTRL_PARAM;


-- =====================================================
-- BLOQUE 1: DIFERENCIAS POR CONCEPTO -- SOLO LO QUE EL ROL IMPRIME
-- =====================================================
-- FULL OUTER JOIN a proposito: un LEFT JOIN solo veria lo que el sistema
-- calculo de mas o de menos, y se le escaparia EL CASO MAS GRAVE -- un
-- concepto que el rol tiene y el sistema NO GENERO. Ese renglon ausente no
-- produce ninguna fila en nuestro lado, asi que solo aparece si la union lo
-- trae desde el lado del cliente.
--
-- SE COMPARAN SOLO LOS TIPOS 1 (INGRESO) Y 2 (EGRESO), y no es una omision:
-- el rol de ASOPREP imprime ingresos y egresos, y no tiene columnas de
-- provision ni de aporte patronal. Nuestro motor si los genera --provision de
-- vacaciones, provisiones de decimos de los acumulados, patronal, IECE y
-- SECAP--, asi que compararlos aqui produciria una veintena de filas de "lo
-- tenemos y ellos no" que NO son diferencias.
--
-- Y veinte filas esperadas son el sitio perfecto para que se pierda la unica
-- que si lo es. Van al bloque 1B, aparte y a la vista: no se esconden, se
-- separan de lo que tiene contrapartida.
WITH nuestro AS (
    SELECT m.MPLDIDNT           AS IDENTIFICACION,
           c.CPNMALTR           AS ALTERNO,
           MAX(c.CPNMNMBR)      AS CONCEPTO,
           SUM(r.RNGLVLRO)      AS VALOR,
           COUNT(*)             AS RENGLONES
      FROM RHH.RNGL r
      JOIN RHH.NMNA n ON n.NMNACDGO = r.NMNACDGO
      JOIN RHH.PRDN p ON p.PRDNCDGO = n.PRDNCDGO
      JOIN RHH.MPLD m ON m.MPLDCDGO = n.MPLDCDGO
      LEFT JOIN RHH.CPNM c ON c.CPNMCDGO = r.CPNMCDGO
     JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1
       AND NVL(r.RNGLTPCN, c.CPNMTPCN) IN (1, 2)
     GROUP BY m.MPLDIDNT, c.CPNMALTR
),
suyo AS (
    SELECT CTRLIDNT AS IDENTIFICACION, CTRLALTR AS ALTERNO, SUM(CTRLVLOR) AS VALOR
      FROM RHH.CTRL
     JOIN RHH.CTRL_PARAM q ON q.ANIO = CTRLANOO AND q.MES = CTRLMESS
     WHERE 1 = 1 AND CTRLALTR IS NOT NULL
     GROUP BY CTRLIDNT, CTRLALTR
)
SELECT NVL(a.IDENTIFICACION, b.IDENTIFICACION) AS IDENTIFICACION,
       NVL(a.ALTERNO, b.ALTERNO)               AS ALTERNO,
       a.CONCEPTO,
       a.VALOR                                 AS NUESTRO,
       b.VALOR                                 AS DEL_ROL,
       NVL(a.VALOR,0) - NVL(b.VALOR,0)         AS DIFERENCIA,
       CASE WHEN a.IDENTIFICACION IS NULL THEN 'EL SISTEMA NO LO GENERO'
            WHEN b.IDENTIFICACION IS NULL THEN 'NO ESTA EN EL ROL'
            WHEN a.RENGLONES > 1          THEN 'OJO: ' || a.RENGLONES || ' RENGLONES DEL MISMO CONCEPTO'
            ELSE 'IMPORTE DISTINTO' END        AS QUE_PASA
  FROM nuestro a
  FULL OUTER JOIN suyo b
    ON b.IDENTIFICACION = a.IDENTIFICACION AND b.ALTERNO = a.ALTERNO
 WHERE a.VALOR IS NULL
    OR b.VALOR IS NULL
    OR a.VALOR <> b.VALOR
 ORDER BY ABS(NVL(a.VALOR,0) - NVL(b.VALOR,0)) DESC, 1, 2;


-- =====================================================
-- BLOQUE 1B: LO QUE EL ROL NO IMPRIME -- INFORMATIVO, NO ES UNA DIFERENCIA
-- =====================================================
-- Patronales y provisiones. Aqui NO hay nada contra que comparar, asi que
-- este bloque no dice "esta mal": dice "esto es lo que el sistema produjo y
-- el rol no muestra". Sale siempre, tambien cuando el mes cuadra.
--
-- Que no tenga contrapartida en el rol NO significa que no tenga control:
--   - Los patronales --patronal, IECE y SECAP-- los controla el BLOQUE 3, el
--     TOTAL IESS de la planilla, que es el control 2 y el que manda.
--   - Las provisiones no las controla nadie contra el cliente, y por eso hay
--     que poder mirarlas: son el pasivo que la empresa acumula.
--
-- Las provisiones viven en RHH.PVNM, no en RHH.RNGL: el motor las escribe en
-- su propia tabla porque no son renglones del rol.
SELECT 'PATRONAL' AS CLASE,
       c.CPNMALTR AS ALTERNO,
       c.CPNMNMBR AS CONCEPTO,
       COUNT(DISTINCT n.MPLDCDGO) AS PERSONAS,
       SUM(r.RNGLVLRO)            AS TOTAL
  FROM RHH.RNGL r
  JOIN RHH.NMNA n ON n.NMNACDGO = r.NMNACDGO
  JOIN RHH.PRDN p ON p.PRDNCDGO = n.PRDNCDGO
  LEFT JOIN RHH.CPNM c ON c.CPNMCDGO = r.CPNMCDGO
 JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1
   AND NVL(r.RNGLTPCN, c.CPNMTPCN) = 3
 GROUP BY c.CPNMALTR, c.CPNMNMBR
UNION ALL
SELECT 'PROVISION', c.CPNMALTR, c.CPNMNMBR,
       COUNT(DISTINCT v.MPLDCDGO), SUM(v.PVNMVLOR)
  FROM RHH.PVNM v
  JOIN RHH.PRDN p ON p.PRDNCDGO = v.PRDNCDGO
  LEFT JOIN RHH.CPNM c ON c.CPNMCDGO = v.CPNMCDGO
 JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1
 GROUP BY c.CPNMALTR, c.CPNMNMBR
 ORDER BY 1, 2;


-- Y el contraste que si tienen los patronales: la cabecera de NMNA debe
-- cumplir NMNATTPT = NMNAAPPT + NMNAIESC. Es el mismo control impreso que
-- lleva el reporte de resumen de aportes, y delata una nomina calculada
-- antes del reparto por rol. Sale vacio si esta bien.
SELECT m.MPLDIDNT AS IDENTIFICACION,
       n.NMNAAPPT AS APORTE_PATRONAL,
       n.NMNAIESC AS IECE_SECAP,
       n.NMNATTPT AS TOTAL_PATRONAL,
       NVL(n.NMNATTPT,0) - (NVL(n.NMNAAPPT,0) + NVL(n.NMNAIESC,0)) AS DESCUADRE
  FROM RHH.NMNA n
  JOIN RHH.PRDN p ON p.PRDNCDGO = n.PRDNCDGO
  JOIN RHH.MPLD m ON m.MPLDCDGO = n.MPLDCDGO
 JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1
   AND NVL(n.NMNATTPT,0) <> NVL(n.NMNAAPPT,0) + NVL(n.NMNAIESC,0)
 ORDER BY 5 DESC;


-- =====================================================
-- BLOQUE 2: DIFERENCIAS EN LOS TOTALES DE LA CABECERA
-- =====================================================
-- Un total puede cuadrar con dos conceptos mal que se compensan, asi que este
-- bloque NO sustituye al primero: lo acompana. Si el bloque 1 sale vacio y
-- este no, el error esta en la cabecera y no en los renglones.
WITH nuestro AS (
    SELECT m.MPLDIDNT AS IDENTIFICACION, 'INGRESOS'   AS TOTAL, n.NMNATING AS VALOR
      FROM RHH.NMNA n JOIN RHH.PRDN p ON p.PRDNCDGO = n.PRDNCDGO
      JOIN RHH.MPLD m ON m.MPLDCDGO = n.MPLDCDGO
     JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1
    UNION ALL
    SELECT m.MPLDIDNT, 'DESCUENTOS', n.NMNATDSC
      FROM RHH.NMNA n JOIN RHH.PRDN p ON p.PRDNCDGO = n.PRDNCDGO
      JOIN RHH.MPLD m ON m.MPLDCDGO = n.MPLDCDGO
     JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1
    UNION ALL
    SELECT m.MPLDIDNT, 'LIQUIDO', n.NMNANETO
      FROM RHH.NMNA n JOIN RHH.PRDN p ON p.PRDNCDGO = n.PRDNCDGO
      JOIN RHH.MPLD m ON m.MPLDCDGO = n.MPLDCDGO
     JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1
    -- DIAS NO SE COMPARA: el rol de ASOPREP no trae dias trabajados como
    -- total y CTRL no los carga, asi que cada persona saldria como "NO ESTA
    -- EN EL ROL" sin que sea una diferencia. Se deja comentado por si un
    -- cliente futuro si los imprime. Los dias de Mendez Torres (30 vs 15)
    -- estan documentados aparte en el plan.
    -- UNION ALL
    -- SELECT m.MPLDIDNT, 'DIAS', n.NMNADITR ...
),
suyo AS (
    SELECT CTRLIDNT AS IDENTIFICACION, CTRLTOTL AS TOTAL, CTRLVLOR AS VALOR
      FROM RHH.CTRL
     JOIN RHH.CTRL_PARAM q ON q.ANIO = CTRLANOO AND q.MES = CTRLMESS
     WHERE 1 = 1 AND CTRLTOTL IS NOT NULL
       AND CTRLTOTL <> 'TOTAL_IESS'
)
SELECT NVL(a.IDENTIFICACION, b.IDENTIFICACION) AS IDENTIFICACION,
       NVL(a.TOTAL, b.TOTAL)                   AS TOTAL,
       a.VALOR                                 AS NUESTRO,
       b.VALOR                                 AS DEL_ROL,
       NVL(a.VALOR,0) - NVL(b.VALOR,0)         AS DIFERENCIA,
       CASE WHEN a.IDENTIFICACION IS NULL THEN 'NO TIENE NOMINA CALCULADA'
            WHEN b.IDENTIFICACION IS NULL THEN 'NO ESTA EN EL ROL'
            ELSE 'IMPORTE DISTINTO' END        AS QUE_PASA
  FROM nuestro a
  FULL OUTER JOIN suyo b
    ON b.IDENTIFICACION = a.IDENTIFICACION AND b.TOTAL = a.TOTAL
 WHERE a.VALOR IS NULL OR b.VALOR IS NULL OR a.VALOR <> b.VALOR
 ORDER BY ABS(NVL(a.VALOR,0) - NVL(b.VALOR,0)) DESC, 1, 2;


-- =====================================================
-- BLOQUE 3: CONTROL 2 - TOTAL IESS AFILIADO POR AFILIADO
-- =====================================================
-- ES EL CONTROL QUE MANDA, y no por ser el mas exacto sino por la regla 6:
-- la planilla la emite el IESS, asi que NO PUEDE COMPARTIR UN ERROR CON
-- NUESTRO MOTOR. El liquido contra el rol si puede -- los dos salen de la
-- misma base imponible, y un error en esa base cuadraria consigo mismo.
--
-- Si este bloque sale vacio, la base imponible del motor es correcta aunque
-- el rol tuviera erratas.
WITH nuestro AS (
    SELECT m.MPLDIDNT AS IDENTIFICACION,
           n.NMNAAPPR AS PERSONAL,
           n.NMNAAPPT AS PATRONAL,
           NVL(n.NMNAAPPR,0) + NVL(n.NMNAAPPT,0) AS TOTAL_IESS,
           n.NMNABSIE AS BASE_IMPONIBLE
      FROM RHH.NMNA n
      JOIN RHH.PRDN p ON p.PRDNCDGO = n.PRDNCDGO
      JOIN RHH.MPLD m ON m.MPLDCDGO = n.MPLDCDGO
     JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1
),
suyo AS (
    SELECT CTRLIDNT AS IDENTIFICACION, CTRLVLOR AS TOTAL_IESS
      FROM RHH.CTRL
     JOIN RHH.CTRL_PARAM q ON q.ANIO = CTRLANOO AND q.MES = CTRLMESS
     WHERE 1 = 1
       AND CTRLTOTL = 'TOTAL_IESS' AND CTRLFNTE = 'PLANILLA'
)
SELECT NVL(a.IDENTIFICACION, b.IDENTIFICACION)      AS IDENTIFICACION,
       a.BASE_IMPONIBLE,
       a.PERSONAL,
       a.PATRONAL,
       a.TOTAL_IESS                                 AS NUESTRO,
       b.TOTAL_IESS                                 AS DE_LA_PLANILLA,
       NVL(a.TOTAL_IESS,0) - NVL(b.TOTAL_IESS,0)    AS DIFERENCIA,
       CASE WHEN a.IDENTIFICACION IS NULL THEN 'EN LA PLANILLA Y SIN NOMINA'
            WHEN b.IDENTIFICACION IS NULL THEN 'CON NOMINA Y SIN PLANILLA'
            ELSE 'IMPORTE DISTINTO' END             AS QUE_PASA
  FROM nuestro a
  FULL OUTER JOIN suyo b ON b.IDENTIFICACION = a.IDENTIFICACION
 WHERE a.TOTAL_IESS IS NULL
    OR b.TOTAL_IESS IS NULL
    OR a.TOTAL_IESS <> b.TOTAL_IESS
 ORDER BY ABS(NVL(a.TOTAL_IESS,0) - NVL(b.TOTAL_IESS,0)) DESC, 1;


-- =====================================================
-- BLOQUE 4: QUE LA COMPARACION SEA COMPLETA
-- =====================================================
-- Una consulta de diferencias vacia significa "no hay diferencias" solo si
-- de verdad se comparo algo. Con la tabla de contraste sin cargar, los tres
-- bloques salen vacios y parecen un exito.
--
-- Ademas, esta es la consulta que situa la salida EN EL TIEMPO. Una salida
-- de comprobacion sin momento es ambigua, y en este proyecto ya costo dos
-- veces: la ultima, diez minutos discutiendo un tipo de saldo porque una
-- consulta era anterior a una reversion.
SELECT SYSTIMESTAMP                                              AS MOMENTO,
       (SELECT COUNT(*) FROM RHH.CTRL
         JOIN RHH.CTRL_PARAM q ON q.ANIO = CTRLANOO AND q.MES = CTRLMESS
     WHERE 1 = 1)              AS FILAS_ESPERADAS,
       (SELECT COUNT(DISTINCT CTRLIDNT) FROM RHH.CTRL
         JOIN RHH.CTRL_PARAM q ON q.ANIO = CTRLANOO AND q.MES = CTRLMESS
     WHERE 1 = 1)              AS PERSONAS_ESPERADAS,
       (SELECT COUNT(*) FROM RHH.NMNA n JOIN RHH.PRDN p ON p.PRDNCDGO = n.PRDNCDGO
         JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1)          AS NOMINAS_CALCULADAS,
       (SELECT COUNT(*) FROM RHH.RNGL r JOIN RHH.NMNA n ON n.NMNACDGO = r.NMNACDGO
          JOIN RHH.PRDN p ON p.PRDNCDGO = n.PRDNCDGO
         JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1)          AS RENGLONES_CALCULADOS,
       (SELECT MAX(p.PRDNESTD) FROM RHH.PRDN p
         JOIN RHH.CTRL_PARAM q ON q.ANIO = p.PRDNANOO AND q.MES = p.PRDNMSEE
     WHERE 1 = 1)          AS ESTADO_PERIODO
  FROM DUAL;


-- =====================================================
-- BLOQUE 5: CONCEPTOS DEL CATALOGO, PARA MAPEAR EL ROL
-- =====================================================
-- El rol de ASOPREP trae columnas con nombre propio -- ANTIC SUELD,
-- VACACIONES, D. TERCERO... -- y la tabla de contraste las guarda por
-- CPNMALTR. Esta es la equivalencia, y se mira UNA vez al preparar la carga.
SELECT CPNMALTR AS ALTERNO, CPNMNMBR AS CONCEPTO,
       CASE CPNMTPCN WHEN 1 THEN 'INGRESO' WHEN 2 THEN 'EGRESO'
                     WHEN 3 THEN 'PATRONAL' WHEN 4 THEN 'PROVISION'
                     ELSE TO_CHAR(CPNMTPCN) END AS TIPO,
       CPNMROLM AS ROL_MOTOR
  FROM RHH.CPNM
 WHERE CPNMESTD = 1
 ORDER BY CPNMTPCN, CPNMALTR;
